// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_duration_samples.fbs".

#pragma once

#include "../datatypes/uint64.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Number of PCM samples per channel produced by decoding a single `components::AudioChunk`.
    ///
    /// Kept as an explicit column so that the viewer and downstream queries do
    /// not need to decode the payload to know its span. For Opus this is
    /// typically `sample_rate * frame_size_ms / 1000` (e.g. 480 samples for 20 ms
    /// at 24 kHz).
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioDurationSamples {
        rerun::datatypes::UInt64 samples;

      public:
        AudioDurationSamples() = default;

        AudioDurationSamples(rerun::datatypes::UInt64 samples_) : samples(samples_) {}

        AudioDurationSamples& operator=(rerun::datatypes::UInt64 samples_) {
            samples = samples_;
            return *this;
        }

        AudioDurationSamples(uint64_t value_) : samples(value_) {}

        AudioDurationSamples& operator=(uint64_t value_) {
            samples = value_;
            return *this;
        }

        /// Cast to the underlying UInt64 datatype
        operator rerun::datatypes::UInt64() const {
            return samples;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt64) == sizeof(components::AudioDurationSamples));

    /// \private
    template <>
    struct Loggable<components::AudioDurationSamples> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioDurationSamples";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt64>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioDurationSamples` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioDurationSamples* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(
                    &instances->samples,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
