// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_stream_id.fbs".

#pragma once

#include "../datatypes/uint64.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Stream continuity marker.
    ///
    /// Rows that share a `stream_id` are considered parts of the same logical
    /// capture; a change in `stream_id` signals a recorder restart or resync and
    /// is treated as an implicit discontinuity.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioStreamId {
        rerun::datatypes::UInt64 id;

      public:
        AudioStreamId() = default;

        AudioStreamId(rerun::datatypes::UInt64 id_) : id(id_) {}

        AudioStreamId& operator=(rerun::datatypes::UInt64 id_) {
            id = id_;
            return *this;
        }

        AudioStreamId(uint64_t value_) : id(value_) {}

        AudioStreamId& operator=(uint64_t value_) {
            id = value_;
            return *this;
        }

        /// Cast to the underlying UInt64 datatype
        operator rerun::datatypes::UInt64() const {
            return id;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt64) == sizeof(components::AudioStreamId));

    /// \private
    template <>
    struct Loggable<components::AudioStreamId> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioStreamId";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt64>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioStreamId` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioStreamId* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(&instances->id, num_instances);
            }
        }
    };
} // namespace rerun
