// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_timestamp.fbs".

#pragma once

#include "../datatypes/audio_timestamp.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Timestamp inside an `archetypes::AssetAudio`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioTimestamp {
        rerun::datatypes::AudioTimestamp timestamp;

      public:
        AudioTimestamp() = default;

        AudioTimestamp(rerun::datatypes::AudioTimestamp timestamp_) : timestamp(timestamp_) {}

        AudioTimestamp& operator=(rerun::datatypes::AudioTimestamp timestamp_) {
            timestamp = timestamp_;
            return *this;
        }

        AudioTimestamp(int64_t timestamp_ns_) : timestamp(timestamp_ns_) {}

        AudioTimestamp& operator=(int64_t timestamp_ns_) {
            timestamp = timestamp_ns_;
            return *this;
        }

        /// Cast to the underlying AudioTimestamp datatype
        operator rerun::datatypes::AudioTimestamp() const {
            return timestamp;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::AudioTimestamp) == sizeof(components::AudioTimestamp));

    /// \private
    template <>
    struct Loggable<components::AudioTimestamp> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioTimestamp";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::AudioTimestamp>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioTimestamp` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioTimestamp* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::AudioTimestamp>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::AudioTimestamp>::to_arrow(
                    &instances->timestamp,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
