// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_sequence_number.fbs".

#pragma once

#include "../datatypes/uint64.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Monotonic per-stream sequence number for a chunk.
    ///
    /// Useful for gap detection: a jump greater than 1 between successive rows
    /// (within the same `components::AudioStreamId`) surfaces a missing segment
    /// to the viewer without requiring payload inspection.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioSequenceNumber {
        rerun::datatypes::UInt64 seq;

      public:
        AudioSequenceNumber() = default;

        AudioSequenceNumber(rerun::datatypes::UInt64 seq_) : seq(seq_) {}

        AudioSequenceNumber& operator=(rerun::datatypes::UInt64 seq_) {
            seq = seq_;
            return *this;
        }

        AudioSequenceNumber(uint64_t value_) : seq(value_) {}

        AudioSequenceNumber& operator=(uint64_t value_) {
            seq = value_;
            return *this;
        }

        /// Cast to the underlying UInt64 datatype
        operator rerun::datatypes::UInt64() const {
            return seq;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt64) == sizeof(components::AudioSequenceNumber));

    /// \private
    template <>
    struct Loggable<components::AudioSequenceNumber> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioSequenceNumber";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt64>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioSequenceNumber` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioSequenceNumber* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(&instances->seq, num_instances);
            }
        }
    };
} // namespace rerun
