// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_chunk.fbs".

#pragma once

#include "../collection.hpp"
#include "../datatypes/blob.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace rerun::components {
    /// **Component**: A time-bounded, decodable segment of encoded audio.
    ///
    /// A chunk is the fundamental temporal unit of an `archetypes::AudioStream`:
    /// each logged row represents one segment that can be handed to the decoder
    /// without referencing data from any other row (any cross-segment decoder
    /// state is reset at segment boundaries marked by `components::AudioDiscontinuity`
    /// or `components::AudioSeekable`).
    ///
    /// The row's timeline timestamp is treated as the presentation timestamp (PTS)
    /// of the first sample in the chunk. The number of PCM samples produced per
    /// channel is carried alongside in `components::AudioDurationSamples`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioChunk {
        rerun::datatypes::Blob buffer;

      public:
        AudioChunk() = default;

        AudioChunk(rerun::datatypes::Blob buffer_) : buffer(std::move(buffer_)) {}

        AudioChunk& operator=(rerun::datatypes::Blob buffer_) {
            buffer = std::move(buffer_);
            return *this;
        }

        AudioChunk(rerun::Collection<uint8_t> data_) : buffer(std::move(data_)) {}

        AudioChunk& operator=(rerun::Collection<uint8_t> data_) {
            buffer = std::move(data_);
            return *this;
        }

        /// Cast to the underlying Blob datatype
        operator rerun::datatypes::Blob() const {
            return buffer;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Blob) == sizeof(components::AudioChunk));

    /// \private
    template <>
    struct Loggable<components::AudioChunk> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioChunk";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Blob>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioChunk` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioChunk* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Blob>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Blob>::to_arrow(
                    &instances->buffer,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
