// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_sample_rate.fbs".

#pragma once

#include "../datatypes/uint32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Audio sample rate in Hertz.
    ///
    /// Typical values: `8000`, `16000`, `24000`, `44100`, `48000`.
    ///
    /// For Opus, this is the decoder's reported output rate; libopus will
    /// internally resample to this value.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioSampleRate {
        rerun::datatypes::UInt32 hz;

      public:
        AudioSampleRate() = default;

        AudioSampleRate(rerun::datatypes::UInt32 hz_) : hz(hz_) {}

        AudioSampleRate& operator=(rerun::datatypes::UInt32 hz_) {
            hz = hz_;
            return *this;
        }

        AudioSampleRate(uint32_t value_) : hz(value_) {}

        AudioSampleRate& operator=(uint32_t value_) {
            hz = value_;
            return *this;
        }

        /// Cast to the underlying UInt32 datatype
        operator rerun::datatypes::UInt32() const {
            return hz;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt32) == sizeof(components::AudioSampleRate));

    /// \private
    template <>
    struct Loggable<components::AudioSampleRate> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioSampleRate";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt32>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioSampleRate` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioSampleRate* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(&instances->hz, num_instances);
            }
        }
    };
} // namespace rerun
