// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_event_kind.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt8Type;
    using UInt8Builder = NumericBuilder<UInt8Type>;
} // namespace arrow

namespace rerun::components {
    /// **Component**: Semantic class of an audio-aligned point event.
    ///
    /// Point events are used for instantaneous state changes and milestones that
    /// should be inspectable on the same timeline as audio, waveform summaries, and
    /// annotation spans.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    enum class AudioEventKind : uint8_t {

        /// Decoder reset or reconfiguration.
        DecoderReset = 1,

        /// ASR segment finalized.
        AsrFinalized = 2,

        /// Diarization speaker changed.
        DiarizationSwitch = 3,

        /// Barge-in or interruption detected.
        BargeIn = 4,

        /// Endpointing decision committed.
        EndpointCommit = 5,

        /// Agent/model state transition.
        AgentStateTransition = 6,

        /// Turn-taking policy changed.
        TurnPolicyChange = 7,

        /// Latency milestone or timing marker.
        LatencyMilestone = 8,

        /// Source discontinuity, stream hole, or timestamp jump.
        Discontinuity = 9,
    };
} // namespace rerun::components

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<components::AudioEventKind> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioEventKind";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::components::AudioEventKind` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioEventKind* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt8Builder* builder, const components::AudioEventKind* elements,
            size_t num_elements
        );
    };
} // namespace rerun
