// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_discontinuity.fbs".

#pragma once

#include "../datatypes/bool.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Marks a chunk as resuming after a gap or recorder reset.
    ///
    /// When true, the decoder state must be flushed before processing this chunk
    /// and any accumulated resampler / overlap-add state discarded. Chunks
    /// without this component are assumed continuous with the previous chunk on
    /// the same timeline + `components::AudioStreamId`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioDiscontinuity {
        rerun::datatypes::Bool is_discontinuity;

      public:
        AudioDiscontinuity() = default;

        AudioDiscontinuity(rerun::datatypes::Bool is_discontinuity_)
            : is_discontinuity(is_discontinuity_) {}

        AudioDiscontinuity& operator=(rerun::datatypes::Bool is_discontinuity_) {
            is_discontinuity = is_discontinuity_;
            return *this;
        }

        AudioDiscontinuity(bool value_) : is_discontinuity(value_) {}

        AudioDiscontinuity& operator=(bool value_) {
            is_discontinuity = value_;
            return *this;
        }

        /// Cast to the underlying Bool datatype
        operator rerun::datatypes::Bool() const {
            return is_discontinuity;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Bool) == sizeof(components::AudioDiscontinuity));

    /// \private
    template <>
    struct Loggable<components::AudioDiscontinuity> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioDiscontinuity";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Bool>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioDiscontinuity` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioDiscontinuity* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Bool>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Bool>::to_arrow(
                    &instances->is_discontinuity,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
