// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_priming_delay.fbs".

#pragma once

#include "../datatypes/uint32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Number of PCM samples at the beginning of a stream to discard (encoder pre-roll).
    ///
    /// For Opus this is the pre-skip reported in the Ogg-Opus header (typically
    /// 312 samples at 48 kHz). When logging raw packets without a container,
    /// record the value here so the decoder can trim output at stream start.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioPrimingDelay {
        rerun::datatypes::UInt32 samples;

      public:
        AudioPrimingDelay() = default;

        AudioPrimingDelay(rerun::datatypes::UInt32 samples_) : samples(samples_) {}

        AudioPrimingDelay& operator=(rerun::datatypes::UInt32 samples_) {
            samples = samples_;
            return *this;
        }

        AudioPrimingDelay(uint32_t value_) : samples(value_) {}

        AudioPrimingDelay& operator=(uint32_t value_) {
            samples = value_;
            return *this;
        }

        /// Cast to the underlying UInt32 datatype
        operator rerun::datatypes::UInt32() const {
            return samples;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt32) == sizeof(components::AudioPrimingDelay));

    /// \private
    template <>
    struct Loggable<components::AudioPrimingDelay> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioPrimingDelay";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt32>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioPrimingDelay` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioPrimingDelay* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(
                    &instances->samples,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
