// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_annotation_kind.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt8Type;
    using UInt8Builder = NumericBuilder<UInt8Type>;
} // namespace arrow

namespace rerun::components {
    /// **Component**: Semantic class of an audio-aligned time span.
    ///
    /// These variants cover the common observability lanes for speech and agent
    /// replay. Use `components::KeyValuePairs` on the archetype for domain-specific
    /// labels that do not need to become schema.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    enum class AudioAnnotationKind : uint8_t {

        /// A finalized or partial ASR utterance.
        AsrUtterance = 1,

        /// A word-level alignment span.
        Word = 2,

        /// A token-level alignment span.
        Token = 3,

        /// A diarization speaker turn.
        SpeakerTurn = 4,

        /// Voice activity detection region.
        Vad = 5,

        /// Endpointing or turn-boundary decision window.
        Endpointing = 6,

        /// Synthesized speech emitted by a TTS/model output path.
        Tts = 7,

        /// Overlap, interruption, or barge-in region.
        Interruption = 8,

        /// Region marked for error analysis or review.
        ErrorRegion = 9,
    };
} // namespace rerun::components

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<components::AudioAnnotationKind> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioAnnotationKind";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::components::AudioAnnotationKind` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioAnnotationKind* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt8Builder* builder, const components::AudioAnnotationKind* elements,
            size_t num_elements
        );
    };
} // namespace rerun
