// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_seekable.fbs".

#pragma once

#include "../datatypes/bool.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Marks a chunk as an independent seek target.
    ///
    /// A seekable chunk can be handed to the decoder without replaying any
    /// earlier chunk. Default is true for codecs whose segments are always
    /// self-contained (e.g. Opus); codecs with inter-frame dependencies should
    /// set this false on non-key segments.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioSeekable {
        rerun::datatypes::Bool is_seekable;

      public:
        AudioSeekable() = default;

        AudioSeekable(rerun::datatypes::Bool is_seekable_) : is_seekable(is_seekable_) {}

        AudioSeekable& operator=(rerun::datatypes::Bool is_seekable_) {
            is_seekable = is_seekable_;
            return *this;
        }

        AudioSeekable(bool value_) : is_seekable(value_) {}

        AudioSeekable& operator=(bool value_) {
            is_seekable = value_;
            return *this;
        }

        /// Cast to the underlying Bool datatype
        operator rerun::datatypes::Bool() const {
            return is_seekable;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Bool) == sizeof(components::AudioSeekable));

    /// \private
    template <>
    struct Loggable<components::AudioSeekable> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioSeekable";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Bool>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioSeekable` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioSeekable* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Bool>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Bool>::to_arrow(
                    &instances->is_seekable,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
