// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_channel_count.fbs".

#pragma once

#include "../datatypes/uint16.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Number of audio channels.
    ///
    /// Must match the channel count reported by the decoder for the stream's
    /// `components::AudioCodec`. The interleaving order is defined by
    /// `components::AudioChannelLayout`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioChannelCount {
        rerun::datatypes::UInt16 count;

      public:
        AudioChannelCount() = default;

        AudioChannelCount(rerun::datatypes::UInt16 count_) : count(count_) {}

        AudioChannelCount& operator=(rerun::datatypes::UInt16 count_) {
            count = count_;
            return *this;
        }

        AudioChannelCount(uint16_t value_) : count(value_) {}

        AudioChannelCount& operator=(uint16_t value_) {
            count = value_;
            return *this;
        }

        /// Cast to the underlying UInt16 datatype
        operator rerun::datatypes::UInt16() const {
            return count;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt16) == sizeof(components::AudioChannelCount));

    /// \private
    template <>
    struct Loggable<components::AudioChannelCount> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioChannelCount";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt16>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::AudioChannelCount` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioChannelCount* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt16>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt16>::to_arrow(
                    &instances->count,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
