// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_channel_layout.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt32Type;
    using UInt32Builder = NumericBuilder<UInt32Type>;
} // namespace arrow

namespace rerun::components {
    /// **Component**: Speaker arrangement for the channels in an audio stream.
    ///
    /// Layouts follow `WebAudio` / `WebCodecs` conventions; unsupported or exotic
    /// arrangements should log `components::AudioChannelLayout::Unspecified` and
    /// are treated as raw interleaved channels by the viewer.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    enum class AudioChannelLayout : uint32_t {

        /// Single channel.
        Mono = 0x1,

        /// L, R.
        Stereo = 0x2,

        /// L, R, C.
        Lcr = 0x3,

        /// L, R, LS, RS.
        Quad = 0x4,

        /// L, R, C, LS, RS (no LFE).
        FiveDot = 0x5,

        /// L, R, C, LFE, LS, RS.
        FiveDotOne = 0x6,

        /// L, R, C, LFE, LS, RS, SL, SR.
        SevenDotOne = 0x8,

        /// First-order ambisonics (W, Y, Z, X). 4 channels.
        Ambisonic1stOrder = 0xA,
    };
} // namespace rerun::components

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<components::AudioChannelLayout> {
        static constexpr std::string_view ComponentType = "rerun.components.AudioChannelLayout";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::components::AudioChannelLayout` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AudioChannelLayout* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt32Builder* builder, const components::AudioChannelLayout* elements,
            size_t num_elements
        );
    };
} // namespace rerun
