// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_event_kind.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]
#![allow(non_camel_case_types)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Semantic class of an audio-aligned point event.
///
/// Point events are used for instantaneous state changes and milestones that
/// should be inspectable on the same timeline as audio, waveform summaries, and
/// annotation spans.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
#[repr(u8)]
pub enum AudioEventKind {
    /// Decoder reset or reconfiguration.
    DecoderReset = 1,

    /// ASR segment finalized.
    AsrFinalized = 2,

    /// Diarization speaker changed.
    DiarizationSwitch = 3,

    /// Barge-in or interruption detected.
    BargeIn = 4,

    /// Endpointing decision committed.
    EndpointCommit = 5,

    /// Agent/model state transition.
    AgentStateTransition = 6,

    /// Turn-taking policy changed.
    TurnPolicyChange = 7,

    /// Latency milestone or timing marker.
    LatencyMilestone = 8,

    /// Source discontinuity, stream hole, or timestamp jump.
    Discontinuity = 9,
}

impl ::re_types_core::Component for AudioEventKind {
    #[inline]
    fn name() -> ComponentType {
        "rerun.components.AudioEventKind".into()
    }
}

::re_types_core::macros::impl_into_cow!(AudioEventKind);

impl ::re_types_core::Loggable for AudioEventKind {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::UInt8
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let (somes, data0): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    let datum = datum.map(|datum| *datum as u8);
                    (datum.is_some(), datum)
                })
                .unzip();
            let data0_validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(PrimitiveArray::<UInt8Type>::new(
                ScalarBuffer::from(
                    data0
                        .into_iter()
                        .map(|v| v.unwrap_or_default())
                        .collect::<Vec<_>>(),
                ),
                data0_validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok(arrow_data
            .as_any()
            .downcast_ref::<UInt8Array>()
            .ok_or_else(|| {
                let expected = Self::arrow_datatype();
                let actual = arrow_data.data_type().clone();
                DeserializationError::datatype_mismatch(expected, actual)
            })
            .with_context("rerun.components.AudioEventKind#enum")?
            .into_iter()
            .map(|typ| match typ {
                Some(val) => <Self as ::re_types_core::reflection::Enum>::try_from_integer(val)
                    .map(Some)
                    .ok_or_else(|| {
                        DeserializationError::missing_union_arm(
                            Self::arrow_datatype(),
                            "<invalid>",
                            val as _,
                        )
                    }),
                None => Ok(None),
            })
            .collect::<DeserializationResult<Vec<Option<_>>>>()
            .with_context("rerun.components.AudioEventKind")?)
    }
}

impl std::fmt::Display for AudioEventKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::DecoderReset => write!(f, "DecoderReset"),
            Self::AsrFinalized => write!(f, "AsrFinalized"),
            Self::DiarizationSwitch => write!(f, "DiarizationSwitch"),
            Self::BargeIn => write!(f, "BargeIn"),
            Self::EndpointCommit => write!(f, "EndpointCommit"),
            Self::AgentStateTransition => write!(f, "AgentStateTransition"),
            Self::TurnPolicyChange => write!(f, "TurnPolicyChange"),
            Self::LatencyMilestone => write!(f, "LatencyMilestone"),
            Self::Discontinuity => write!(f, "Discontinuity"),
        }
    }
}

impl ::re_types_core::reflection::Enum for AudioEventKind {
    type Repr = u8;

    #[inline]
    fn variants() -> &'static [Self] {
        &[
            Self::DecoderReset,
            Self::AsrFinalized,
            Self::DiarizationSwitch,
            Self::BargeIn,
            Self::EndpointCommit,
            Self::AgentStateTransition,
            Self::TurnPolicyChange,
            Self::LatencyMilestone,
            Self::Discontinuity,
        ]
    }

    #[inline]
    fn docstring_md(self) -> &'static str {
        match self {
            Self::DecoderReset => "Decoder reset or reconfiguration.",
            Self::AsrFinalized => "ASR segment finalized.",
            Self::DiarizationSwitch => "Diarization speaker changed.",
            Self::BargeIn => "Barge-in or interruption detected.",
            Self::EndpointCommit => "Endpointing decision committed.",
            Self::AgentStateTransition => "Agent/model state transition.",
            Self::TurnPolicyChange => "Turn-taking policy changed.",
            Self::LatencyMilestone => "Latency milestone or timing marker.",
            Self::Discontinuity => "Source discontinuity, stream hole, or timestamp jump.",
        }
    }

    #[inline]
    fn try_from_integer(value: u8) -> Option<Self> {
        Self::variants()
            .get((value as usize).wrapping_sub(1))
            .copied()
    }
}

impl ::re_byte_size::SizeBytes for AudioEventKind {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        0
    }

    #[inline]
    fn is_pod() -> bool {
        true
    }
}
