// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_chunk.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: A time-bounded, decodable segment of encoded audio.
///
/// A chunk is the fundamental temporal unit of an [`archetypes::AudioStream`][crate::archetypes::AudioStream]:
/// each logged row represents one segment that can be handed to the decoder
/// without referencing data from any other row (any cross-segment decoder
/// state is reset at segment boundaries marked by [`components::AudioDiscontinuity`][crate::components::AudioDiscontinuity]
/// or [`components::AudioSeekable`][crate::components::AudioSeekable]).
///
/// The row's timeline timestamp is treated as the presentation timestamp (PTS)
/// of the first sample in the chunk. The number of PCM samples produced per
/// channel is carried alongside in [`components::AudioDurationSamples`][crate::components::AudioDurationSamples].
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Eq)]
#[repr(transparent)]
pub struct AudioChunk(pub crate::datatypes::Blob);

impl ::re_types_core::WrapperComponent for AudioChunk {
    type Datatype = crate::datatypes::Blob;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.AudioChunk".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(AudioChunk);

impl<T: Into<crate::datatypes::Blob>> From<T> for AudioChunk {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::Blob> for AudioChunk {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::Blob {
        &self.0
    }
}

impl std::ops::Deref for AudioChunk {
    type Target = crate::datatypes::Blob;

    #[inline]
    fn deref(&self) -> &crate::datatypes::Blob {
        &self.0
    }
}

impl std::ops::DerefMut for AudioChunk {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::Blob {
        &mut self.0
    }
}

impl ::re_byte_size::SizeBytes for AudioChunk {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.0.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::Blob>::is_pod()
    }
}
