// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_channel_layout.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]
#![allow(non_camel_case_types)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Speaker arrangement for the channels in an audio stream.
///
/// Layouts follow `WebAudio` / `WebCodecs` conventions; unsupported or exotic
/// arrangements should log [`components::AudioChannelLayout::Unspecified`][crate::components::AudioChannelLayout::Unspecified] and
/// are treated as raw interleaved channels by the viewer.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
#[repr(u32)]
pub enum AudioChannelLayout {
    /// Single channel.
    Mono = 0x1,

    /// L, R.
    Stereo = 0x2,

    /// L, R, C.
    Lcr = 0x3,

    /// L, R, LS, RS.
    Quad = 0x4,

    /// L, R, C, LS, RS (no LFE).
    FiveDot = 0x5,

    /// L, R, C, LFE, LS, RS.
    FiveDotOne = 0x6,

    /// L, R, C, LFE, LS, RS, SL, SR.
    SevenDotOne = 0x8,

    /// First-order ambisonics (W, Y, Z, X). 4 channels.
    Ambisonic1stOrder = 0xA,
}

impl ::re_types_core::Component for AudioChannelLayout {
    #[inline]
    fn name() -> ComponentType {
        "rerun.components.AudioChannelLayout".into()
    }
}

::re_types_core::macros::impl_into_cow!(AudioChannelLayout);

impl ::re_types_core::Loggable for AudioChannelLayout {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::UInt32
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let (somes, data0): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    let datum = datum.map(|datum| *datum as u32);
                    (datum.is_some(), datum)
                })
                .unzip();
            let data0_validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(PrimitiveArray::<UInt32Type>::new(
                ScalarBuffer::from(
                    data0
                        .into_iter()
                        .map(|v| v.unwrap_or_default())
                        .collect::<Vec<_>>(),
                ),
                data0_validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok(arrow_data
            .as_any()
            .downcast_ref::<UInt32Array>()
            .ok_or_else(|| {
                let expected = Self::arrow_datatype();
                let actual = arrow_data.data_type().clone();
                DeserializationError::datatype_mismatch(expected, actual)
            })
            .with_context("rerun.components.AudioChannelLayout#enum")?
            .into_iter()
            .map(|typ| match typ {
                Some(val) => <Self as ::re_types_core::reflection::Enum>::try_from_integer(val)
                    .map(Some)
                    .ok_or_else(|| {
                        DeserializationError::missing_union_arm(
                            Self::arrow_datatype(),
                            "<invalid>",
                            val as _,
                        )
                    }),
                None => Ok(None),
            })
            .collect::<DeserializationResult<Vec<Option<_>>>>()
            .with_context("rerun.components.AudioChannelLayout")?)
    }
}

impl std::fmt::Display for AudioChannelLayout {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Mono => write!(f, "Mono"),
            Self::Stereo => write!(f, "Stereo"),
            Self::Lcr => write!(f, "Lcr"),
            Self::Quad => write!(f, "Quad"),
            Self::FiveDot => write!(f, "FiveDot"),
            Self::FiveDotOne => write!(f, "FiveDotOne"),
            Self::SevenDotOne => write!(f, "SevenDotOne"),
            Self::Ambisonic1stOrder => write!(f, "Ambisonic1stOrder"),
        }
    }
}

impl ::re_types_core::reflection::Enum for AudioChannelLayout {
    type Repr = u32;

    #[inline]
    fn variants() -> &'static [Self] {
        &[
            Self::Mono,
            Self::Stereo,
            Self::Lcr,
            Self::Quad,
            Self::FiveDot,
            Self::FiveDotOne,
            Self::SevenDotOne,
            Self::Ambisonic1stOrder,
        ]
    }

    #[inline]
    fn docstring_md(self) -> &'static str {
        match self {
            Self::Mono => "Single channel.",
            Self::Stereo => "L, R.",
            Self::Lcr => "L, R, C.",
            Self::Quad => "L, R, LS, RS.",
            Self::FiveDot => "L, R, C, LS, RS (no LFE).",
            Self::FiveDotOne => "L, R, C, LFE, LS, RS.",
            Self::SevenDotOne => "L, R, C, LFE, LS, RS, SL, SR.",
            Self::Ambisonic1stOrder => "First-order ambisonics (W, Y, Z, X). 4 channels.",
        }
    }

    #[inline]
    fn try_from_integer(value: u32) -> Option<Self> {
        match value {
            0x1 => Some(Self::Mono),
            0x2 => Some(Self::Stereo),
            0x3 => Some(Self::Lcr),
            0x4 => Some(Self::Quad),
            0x5 => Some(Self::FiveDot),
            0x6 => Some(Self::FiveDotOne),
            0x8 => Some(Self::SevenDotOne),
            0xA => Some(Self::Ambisonic1stOrder),
            _ => None,
        }
    }
}

impl ::re_byte_size::SizeBytes for AudioChannelLayout {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        0
    }

    #[inline]
    fn is_pod() -> bool {
        true
    }
}
