// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_codec.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]
#![allow(non_camel_case_types)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: The codec used to encode audio stored in [`components::AudioChunk`][crate::components::AudioChunk].
///
/// Enum values are the big-endian packing of the `WebCodecs` audio codec string
/// (same convention used by [`components::VideoCodec`][crate::components::VideoCodec]).
///
/// Support of these codecs by the Rerun Viewer is platform dependent.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
#[repr(u32)]
pub enum AudioCodec {
    /// Free Lossless Audio Codec (FLAC).
    ///
    /// Each [`components::AudioChunk`][crate::components::AudioChunk] is expected to contain one or more complete FLAC frames.
    ///
    /// Enum value is the fourcc for `'flac'` (the `WebCodecs` string for FLAC) in big endian.
    Flac = 0x666C6163,

    /// Opus — RFC 6716.
    ///
    /// Streams are expected to contain one or more raw Opus packets per
    /// [`components::AudioChunk`][crate::components::AudioChunk]. Any sample rate supported by the decoder
    /// (8/12/16/24/48 kHz) is valid. Libopus handles internal resampling to
    /// 48 kHz but the logged [`components::AudioSampleRate`][crate::components::AudioSampleRate] is treated as
    /// authoritative for downstream analysis.
    ///
    /// Enum value is the fourcc for `'opus'` (the `WebCodecs` string for Opus) in big endian.
    Opus = 0x6F707573,
}

impl ::re_types_core::Component for AudioCodec {
    #[inline]
    fn name() -> ComponentType {
        "rerun.components.AudioCodec".into()
    }
}

::re_types_core::macros::impl_into_cow!(AudioCodec);

impl ::re_types_core::Loggable for AudioCodec {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::UInt32
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let (somes, data0): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    let datum = datum.map(|datum| *datum as u32);
                    (datum.is_some(), datum)
                })
                .unzip();
            let data0_validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(PrimitiveArray::<UInt32Type>::new(
                ScalarBuffer::from(
                    data0
                        .into_iter()
                        .map(|v| v.unwrap_or_default())
                        .collect::<Vec<_>>(),
                ),
                data0_validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok(arrow_data
            .as_any()
            .downcast_ref::<UInt32Array>()
            .ok_or_else(|| {
                let expected = Self::arrow_datatype();
                let actual = arrow_data.data_type().clone();
                DeserializationError::datatype_mismatch(expected, actual)
            })
            .with_context("rerun.components.AudioCodec#enum")?
            .into_iter()
            .map(|typ| match typ {
                Some(val) => <Self as ::re_types_core::reflection::Enum>::try_from_integer(val)
                    .map(Some)
                    .ok_or_else(|| {
                        DeserializationError::missing_union_arm(
                            Self::arrow_datatype(),
                            "<invalid>",
                            val as _,
                        )
                    }),
                None => Ok(None),
            })
            .collect::<DeserializationResult<Vec<Option<_>>>>()
            .with_context("rerun.components.AudioCodec")?)
    }
}

impl std::fmt::Display for AudioCodec {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Flac => write!(f, "Flac"),
            Self::Opus => write!(f, "Opus"),
        }
    }
}

impl ::re_types_core::reflection::Enum for AudioCodec {
    type Repr = u32;

    #[inline]
    fn variants() -> &'static [Self] {
        &[Self::Flac, Self::Opus]
    }

    #[inline]
    fn docstring_md(self) -> &'static str {
        match self {
            Self::Flac => {
                "Free Lossless Audio Codec (FLAC).\n\nEach [`components.AudioChunk`](https://rerun.io/docs/reference/types/components/audio_chunk?speculative-link) is expected to contain one or more complete FLAC frames.\n\nEnum value is the fourcc for `'flac'` (the `WebCodecs` string for FLAC) in big endian."
            }
            Self::Opus => {
                "Opus — RFC 6716.\n\nStreams are expected to contain one or more raw Opus packets per\n[`components.AudioChunk`](https://rerun.io/docs/reference/types/components/audio_chunk?speculative-link). Any sample rate supported by the decoder\n(8/12/16/24/48 kHz) is valid. Libopus handles internal resampling to\n48 kHz but the logged [`components.AudioSampleRate`](https://rerun.io/docs/reference/types/components/audio_sample_rate?speculative-link) is treated as\nauthoritative for downstream analysis.\n\nEnum value is the fourcc for `'opus'` (the `WebCodecs` string for Opus) in big endian."
            }
        }
    }

    #[inline]
    fn try_from_integer(value: u32) -> Option<Self> {
        match value {
            0x666C6163 => Some(Self::Flac),
            0x6F707573 => Some(Self::Opus),
            _ => None,
        }
    }
}

impl ::re_byte_size::SizeBytes for AudioCodec {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        0
    }

    #[inline]
    fn is_pod() -> bool {
        true
    }
}
