// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_sequence_number.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Monotonic per-stream sequence number for a chunk.
///
/// Useful for gap detection: a jump greater than 1 between successive rows
/// (within the same [`components::AudioStreamId`][crate::components::AudioStreamId]) surfaces a missing segment
/// to the viewer without requiring payload inspection.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[repr(transparent)]
pub struct AudioSequenceNumber(pub crate::datatypes::UInt64);

impl ::re_types_core::WrapperComponent for AudioSequenceNumber {
    type Datatype = crate::datatypes::UInt64;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.AudioSequenceNumber".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(AudioSequenceNumber);

impl<T: Into<crate::datatypes::UInt64>> From<T> for AudioSequenceNumber {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::UInt64> for AudioSequenceNumber {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::UInt64 {
        &self.0
    }
}

impl std::ops::Deref for AudioSequenceNumber {
    type Target = crate::datatypes::UInt64;

    #[inline]
    fn deref(&self) -> &crate::datatypes::UInt64 {
        &self.0
    }
}

impl std::ops::DerefMut for AudioSequenceNumber {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::UInt64 {
        &mut self.0
    }
}

impl ::re_byte_size::SizeBytes for AudioSequenceNumber {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.0.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::UInt64>::is_pod()
    }
}
