// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_duration_samples.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Number of PCM samples per channel produced by decoding a single [`components::AudioChunk`][crate::components::AudioChunk].
///
/// Kept as an explicit column so that the viewer and downstream queries do
/// not need to decode the payload to know its span. For Opus this is
/// typically `sample_rate * frame_size_ms / 1000` (e.g. 480 samples for 20 ms
/// at 24 kHz).
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[repr(transparent)]
pub struct AudioDurationSamples(pub crate::datatypes::UInt64);

impl ::re_types_core::WrapperComponent for AudioDurationSamples {
    type Datatype = crate::datatypes::UInt64;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.AudioDurationSamples".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(AudioDurationSamples);

impl<T: Into<crate::datatypes::UInt64>> From<T> for AudioDurationSamples {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::UInt64> for AudioDurationSamples {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::UInt64 {
        &self.0
    }
}

impl std::ops::Deref for AudioDurationSamples {
    type Target = crate::datatypes::UInt64;

    #[inline]
    fn deref(&self) -> &crate::datatypes::UInt64 {
        &self.0
    }
}

impl std::ops::DerefMut for AudioDurationSamples {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::UInt64 {
        &mut self.0
    }
}

impl ::re_byte_size::SizeBytes for AudioDurationSamples {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.0.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::UInt64>::is_pod()
    }
}
