// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

#include "asset_audio.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AssetAudio AssetAudio::clear_fields() {
        auto archetype = AssetAudio();
        archetype.blob =
            ComponentBatch::empty<rerun::components::Blob>(Descriptor_blob).value_or_throw();
        archetype.media_type =
            ComponentBatch::empty<rerun::components::MediaType>(Descriptor_media_type)
                .value_or_throw();
        archetype.codec =
            ComponentBatch::empty<rerun::components::AudioCodec>(Descriptor_codec).value_or_throw();
        archetype.sample_rate =
            ComponentBatch::empty<rerun::components::AudioSampleRate>(Descriptor_sample_rate)
                .value_or_throw();
        archetype.channel_count =
            ComponentBatch::empty<rerun::components::AudioChannelCount>(Descriptor_channel_count)
                .value_or_throw();
        archetype.channel_layout =
            ComponentBatch::empty<rerun::components::AudioChannelLayout>(Descriptor_channel_layout)
                .value_or_throw();
        archetype.duration_samples = ComponentBatch::empty<rerun::components::AudioDurationSamples>(
                                         Descriptor_duration_samples
        )
                                         .value_or_throw();
        archetype.source_id =
            ComponentBatch::empty<rerun::components::AudioSourceId>(Descriptor_source_id)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AssetAudio::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(8);
        if (blob.has_value()) {
            columns.push_back(blob.value().partitioned(lengths_).value_or_throw());
        }
        if (media_type.has_value()) {
            columns.push_back(media_type.value().partitioned(lengths_).value_or_throw());
        }
        if (codec.has_value()) {
            columns.push_back(codec.value().partitioned(lengths_).value_or_throw());
        }
        if (sample_rate.has_value()) {
            columns.push_back(sample_rate.value().partitioned(lengths_).value_or_throw());
        }
        if (channel_count.has_value()) {
            columns.push_back(channel_count.value().partitioned(lengths_).value_or_throw());
        }
        if (channel_layout.has_value()) {
            columns.push_back(channel_layout.value().partitioned(lengths_).value_or_throw());
        }
        if (duration_samples.has_value()) {
            columns.push_back(duration_samples.value().partitioned(lengths_).value_or_throw());
        }
        if (source_id.has_value()) {
            columns.push_back(source_id.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AssetAudio::columns() {
        if (blob.has_value()) {
            return columns(std::vector<uint32_t>(blob.value().length(), 1));
        }
        if (media_type.has_value()) {
            return columns(std::vector<uint32_t>(media_type.value().length(), 1));
        }
        if (codec.has_value()) {
            return columns(std::vector<uint32_t>(codec.value().length(), 1));
        }
        if (sample_rate.has_value()) {
            return columns(std::vector<uint32_t>(sample_rate.value().length(), 1));
        }
        if (channel_count.has_value()) {
            return columns(std::vector<uint32_t>(channel_count.value().length(), 1));
        }
        if (channel_layout.has_value()) {
            return columns(std::vector<uint32_t>(channel_layout.value().length(), 1));
        }
        if (duration_samples.has_value()) {
            return columns(std::vector<uint32_t>(duration_samples.value().length(), 1));
        }
        if (source_id.has_value()) {
            return columns(std::vector<uint32_t>(source_id.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AssetAudio>::as_batches(
        const archetypes::AssetAudio& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(8);

        if (archetype.blob.has_value()) {
            cells.push_back(archetype.blob.value());
        }
        if (archetype.media_type.has_value()) {
            cells.push_back(archetype.media_type.value());
        }
        if (archetype.codec.has_value()) {
            cells.push_back(archetype.codec.value());
        }
        if (archetype.sample_rate.has_value()) {
            cells.push_back(archetype.sample_rate.value());
        }
        if (archetype.channel_count.has_value()) {
            cells.push_back(archetype.channel_count.value());
        }
        if (archetype.channel_layout.has_value()) {
            cells.push_back(archetype.channel_layout.value());
        }
        if (archetype.duration_samples.has_value()) {
            cells.push_back(archetype.duration_samples.value());
        }
        if (archetype.source_id.has_value()) {
            cells.push_back(archetype.source_id.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
