// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/audio_channel_count.hpp"
#include "../components/audio_channel_layout.hpp"
#include "../components/audio_codec.hpp"
#include "../components/audio_duration_samples.hpp"
#include "../components/audio_sample_rate.hpp"
#include "../components/audio_source_id.hpp"
#include "../components/blob.hpp"
#include "../components/media_type.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: A complete audio asset.
    ///
    /// Represents a self-describing audio container (Ogg, FLAC, MP4/M4A, …) or
    /// a raw encoded blob accompanied by explicit codec and rate metadata.
    ///
    /// Supported container media types initially:
    /// * `audio/ogg` — Opus in Ogg, fully playable.
    /// * `audio/flac` — lossless, fully playable.
    ///
    /// To place the asset on a timeline, log a companion
    /// `archetypes::AudioSampleReference` on the same (or a referencing) entity
    /// at each playhead position you want the asset aligned to.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AssetAudio {
        /// The raw bytes of the audio asset.
        std::optional<ComponentBatch> blob;

        /// The IANA media type of the asset.
        ///
        /// If omitted, the viewer will try to sniff from the first bytes of the blob.
        /// If sniffing fails the asset is stored but playback is disabled.
        std::optional<ComponentBatch> media_type;

        /// Audio codec of the enclosed samples.
        ///
        /// When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
        /// this is redundant; logging it makes analysis queries cheaper.
        std::optional<ComponentBatch> codec;

        /// Decoded sample rate in Hz.
        std::optional<ComponentBatch> sample_rate;

        /// Decoded channel count.
        std::optional<ComponentBatch> channel_count;

        /// Speaker arrangement for the channels.
        std::optional<ComponentBatch> channel_layout;

        /// Total decoded duration, in samples per channel, if known.
        ///
        /// This lets the Audio View and external queries reason about the asset's
        /// playable range without decoding the blob.
        std::optional<ComponentBatch> duration_samples;

        /// Stable identity of the logical audio source.
        ///
        /// This lets waveform summaries, seek indexes, annotations, and exported
        /// clips refer to the same source even when they are logged on separate
        /// entities or materialized in different passes.
        std::optional<ComponentBatch> source_id;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.AssetAudio";

        /// `ComponentDescriptor` for the `blob` field.
        static constexpr auto Descriptor_blob = ComponentDescriptor(
            ArchetypeName, "AssetAudio:blob", Loggable<rerun::components::Blob>::ComponentType
        );
        /// `ComponentDescriptor` for the `media_type` field.
        static constexpr auto Descriptor_media_type = ComponentDescriptor(
            ArchetypeName, "AssetAudio:media_type",
            Loggable<rerun::components::MediaType>::ComponentType
        );
        /// `ComponentDescriptor` for the `codec` field.
        static constexpr auto Descriptor_codec = ComponentDescriptor(
            ArchetypeName, "AssetAudio:codec",
            Loggable<rerun::components::AudioCodec>::ComponentType
        );
        /// `ComponentDescriptor` for the `sample_rate` field.
        static constexpr auto Descriptor_sample_rate = ComponentDescriptor(
            ArchetypeName, "AssetAudio:sample_rate",
            Loggable<rerun::components::AudioSampleRate>::ComponentType
        );
        /// `ComponentDescriptor` for the `channel_count` field.
        static constexpr auto Descriptor_channel_count = ComponentDescriptor(
            ArchetypeName, "AssetAudio:channel_count",
            Loggable<rerun::components::AudioChannelCount>::ComponentType
        );
        /// `ComponentDescriptor` for the `channel_layout` field.
        static constexpr auto Descriptor_channel_layout = ComponentDescriptor(
            ArchetypeName, "AssetAudio:channel_layout",
            Loggable<rerun::components::AudioChannelLayout>::ComponentType
        );
        /// `ComponentDescriptor` for the `duration_samples` field.
        static constexpr auto Descriptor_duration_samples = ComponentDescriptor(
            ArchetypeName, "AssetAudio:duration_samples",
            Loggable<rerun::components::AudioDurationSamples>::ComponentType
        );
        /// `ComponentDescriptor` for the `source_id` field.
        static constexpr auto Descriptor_source_id = ComponentDescriptor(
            ArchetypeName, "AssetAudio:source_id",
            Loggable<rerun::components::AudioSourceId>::ComponentType
        );

      public:
        AssetAudio() = default;
        AssetAudio(AssetAudio&& other) = default;
        AssetAudio(const AssetAudio& other) = default;
        AssetAudio& operator=(const AssetAudio& other) = default;
        AssetAudio& operator=(AssetAudio&& other) = default;

        explicit AssetAudio(rerun::components::Blob _blob)
            : blob(ComponentBatch::from_loggable(std::move(_blob), Descriptor_blob).value_or_throw()
              ) {}

        /// Update only some specific fields of a `AssetAudio`.
        static AssetAudio update_fields() {
            return AssetAudio();
        }

        /// Clear all the fields of a `AssetAudio`.
        static AssetAudio clear_fields();

        /// The raw bytes of the audio asset.
        AssetAudio with_blob(const rerun::components::Blob& _blob) && {
            blob = ComponentBatch::from_loggable(_blob, Descriptor_blob).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `blob` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_blob` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_blob(const Collection<rerun::components::Blob>& _blob) && {
            blob = ComponentBatch::from_loggable(_blob, Descriptor_blob).value_or_throw();
            return std::move(*this);
        }

        /// The IANA media type of the asset.
        ///
        /// If omitted, the viewer will try to sniff from the first bytes of the blob.
        /// If sniffing fails the asset is stored but playback is disabled.
        AssetAudio with_media_type(const rerun::components::MediaType& _media_type) && {
            media_type =
                ComponentBatch::from_loggable(_media_type, Descriptor_media_type).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `media_type` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_media_type` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_media_type(const Collection<rerun::components::MediaType>& _media_type
        ) && {
            media_type =
                ComponentBatch::from_loggable(_media_type, Descriptor_media_type).value_or_throw();
            return std::move(*this);
        }

        /// Audio codec of the enclosed samples.
        ///
        /// When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
        /// this is redundant; logging it makes analysis queries cheaper.
        AssetAudio with_codec(const rerun::components::AudioCodec& _codec) && {
            codec = ComponentBatch::from_loggable(_codec, Descriptor_codec).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `codec` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_codec` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_codec(const Collection<rerun::components::AudioCodec>& _codec) && {
            codec = ComponentBatch::from_loggable(_codec, Descriptor_codec).value_or_throw();
            return std::move(*this);
        }

        /// Decoded sample rate in Hz.
        AssetAudio with_sample_rate(const rerun::components::AudioSampleRate& _sample_rate) && {
            sample_rate = ComponentBatch::from_loggable(_sample_rate, Descriptor_sample_rate)
                              .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `sample_rate` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_sample_rate` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_sample_rate(
            const Collection<rerun::components::AudioSampleRate>& _sample_rate
        ) && {
            sample_rate = ComponentBatch::from_loggable(_sample_rate, Descriptor_sample_rate)
                              .value_or_throw();
            return std::move(*this);
        }

        /// Decoded channel count.
        AssetAudio with_channel_count(const rerun::components::AudioChannelCount& _channel_count
        ) && {
            channel_count = ComponentBatch::from_loggable(_channel_count, Descriptor_channel_count)
                                .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `channel_count` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_channel_count` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_channel_count(
            const Collection<rerun::components::AudioChannelCount>& _channel_count
        ) && {
            channel_count = ComponentBatch::from_loggable(_channel_count, Descriptor_channel_count)
                                .value_or_throw();
            return std::move(*this);
        }

        /// Speaker arrangement for the channels.
        AssetAudio with_channel_layout(const rerun::components::AudioChannelLayout& _channel_layout
        ) && {
            channel_layout =
                ComponentBatch::from_loggable(_channel_layout, Descriptor_channel_layout)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `channel_layout` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_channel_layout` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_channel_layout(
            const Collection<rerun::components::AudioChannelLayout>& _channel_layout
        ) && {
            channel_layout =
                ComponentBatch::from_loggable(_channel_layout, Descriptor_channel_layout)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Total decoded duration, in samples per channel, if known.
        ///
        /// This lets the Audio View and external queries reason about the asset's
        /// playable range without decoding the blob.
        AssetAudio with_duration_samples(
            const rerun::components::AudioDurationSamples& _duration_samples
        ) && {
            duration_samples =
                ComponentBatch::from_loggable(_duration_samples, Descriptor_duration_samples)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `duration_samples` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_duration_samples` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_duration_samples(
            const Collection<rerun::components::AudioDurationSamples>& _duration_samples
        ) && {
            duration_samples =
                ComponentBatch::from_loggable(_duration_samples, Descriptor_duration_samples)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Stable identity of the logical audio source.
        ///
        /// This lets waveform summaries, seek indexes, annotations, and exported
        /// clips refer to the same source even when they are logged on separate
        /// entities or materialized in different passes.
        AssetAudio with_source_id(const rerun::components::AudioSourceId& _source_id) && {
            source_id =
                ComponentBatch::from_loggable(_source_id, Descriptor_source_id).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `source_id` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_source_id` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_source_id(
            const Collection<rerun::components::AudioSourceId>& _source_id
        ) && {
            source_id =
                ComponentBatch::from_loggable(_source_id, Descriptor_source_id).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::AssetAudio> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(const archetypes::AssetAudio& archetype
        );
    };
} // namespace rerun
