// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_waveform_summary.fbs".

#include "audio_waveform_summary.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioWaveformSummary AudioWaveformSummary::clear_fields() {
        auto archetype = AudioWaveformSummary();
        archetype.bucket_start =
            ComponentBatch::empty<rerun::components::AudioTimestamp>(Descriptor_bucket_start)
                .value_or_throw();
        archetype.bucket_duration_samples =
            ComponentBatch::empty<rerun::components::AudioDurationSamples>(
                Descriptor_bucket_duration_samples
            )
                .value_or_throw();
        archetype.min_amplitude =
            ComponentBatch::empty<rerun::components::Scalar>(Descriptor_min_amplitude)
                .value_or_throw();
        archetype.max_amplitude =
            ComponentBatch::empty<rerun::components::Scalar>(Descriptor_max_amplitude)
                .value_or_throw();
        archetype.rms_amplitude =
            ComponentBatch::empty<rerun::components::Scalar>(Descriptor_rms_amplitude)
                .value_or_throw();
        archetype.activity =
            ComponentBatch::empty<rerun::components::Scalar>(Descriptor_activity).value_or_throw();
        archetype.source_id =
            ComponentBatch::empty<rerun::components::AudioSourceId>(Descriptor_source_id)
                .value_or_throw();
        archetype.audio_reference =
            ComponentBatch::empty<rerun::components::EntityPath>(Descriptor_audio_reference)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioWaveformSummary::columns(const Collection<uint32_t>& lengths_
    ) {
        std::vector<ComponentColumn> columns;
        columns.reserve(8);
        if (bucket_start.has_value()) {
            columns.push_back(bucket_start.value().partitioned(lengths_).value_or_throw());
        }
        if (bucket_duration_samples.has_value()) {
            columns.push_back(bucket_duration_samples.value().partitioned(lengths_).value_or_throw()
            );
        }
        if (min_amplitude.has_value()) {
            columns.push_back(min_amplitude.value().partitioned(lengths_).value_or_throw());
        }
        if (max_amplitude.has_value()) {
            columns.push_back(max_amplitude.value().partitioned(lengths_).value_or_throw());
        }
        if (rms_amplitude.has_value()) {
            columns.push_back(rms_amplitude.value().partitioned(lengths_).value_or_throw());
        }
        if (activity.has_value()) {
            columns.push_back(activity.value().partitioned(lengths_).value_or_throw());
        }
        if (source_id.has_value()) {
            columns.push_back(source_id.value().partitioned(lengths_).value_or_throw());
        }
        if (audio_reference.has_value()) {
            columns.push_back(audio_reference.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioWaveformSummary::columns() {
        if (bucket_start.has_value()) {
            return columns(std::vector<uint32_t>(bucket_start.value().length(), 1));
        }
        if (bucket_duration_samples.has_value()) {
            return columns(std::vector<uint32_t>(bucket_duration_samples.value().length(), 1));
        }
        if (min_amplitude.has_value()) {
            return columns(std::vector<uint32_t>(min_amplitude.value().length(), 1));
        }
        if (max_amplitude.has_value()) {
            return columns(std::vector<uint32_t>(max_amplitude.value().length(), 1));
        }
        if (rms_amplitude.has_value()) {
            return columns(std::vector<uint32_t>(rms_amplitude.value().length(), 1));
        }
        if (activity.has_value()) {
            return columns(std::vector<uint32_t>(activity.value().length(), 1));
        }
        if (source_id.has_value()) {
            return columns(std::vector<uint32_t>(source_id.value().length(), 1));
        }
        if (audio_reference.has_value()) {
            return columns(std::vector<uint32_t>(audio_reference.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioWaveformSummary>::as_batches(
        const archetypes::AudioWaveformSummary& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(8);

        if (archetype.bucket_start.has_value()) {
            cells.push_back(archetype.bucket_start.value());
        }
        if (archetype.bucket_duration_samples.has_value()) {
            cells.push_back(archetype.bucket_duration_samples.value());
        }
        if (archetype.min_amplitude.has_value()) {
            cells.push_back(archetype.min_amplitude.value());
        }
        if (archetype.max_amplitude.has_value()) {
            cells.push_back(archetype.max_amplitude.value());
        }
        if (archetype.rms_amplitude.has_value()) {
            cells.push_back(archetype.rms_amplitude.value());
        }
        if (archetype.activity.has_value()) {
            cells.push_back(archetype.activity.value());
        }
        if (archetype.source_id.has_value()) {
            cells.push_back(archetype.source_id.value());
        }
        if (archetype.audio_reference.has_value()) {
            cells.push_back(archetype.audio_reference.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
