// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_annotation_span.fbs".

#include "audio_annotation_span.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioAnnotationSpan AudioAnnotationSpan::clear_fields() {
        auto archetype = AudioAnnotationSpan();
        archetype.start_time =
            ComponentBatch::empty<rerun::components::AudioTimestamp>(Descriptor_start_time)
                .value_or_throw();
        archetype.end_time =
            ComponentBatch::empty<rerun::components::AudioTimestamp>(Descriptor_end_time)
                .value_or_throw();
        archetype.kind =
            ComponentBatch::empty<rerun::components::AudioAnnotationKind>(Descriptor_kind)
                .value_or_throw();
        archetype.labels =
            ComponentBatch::empty<rerun::components::Text>(Descriptor_labels).value_or_throw();
        archetype.confidence =
            ComponentBatch::empty<rerun::components::Scalar>(Descriptor_confidence)
                .value_or_throw();
        archetype.speaker =
            ComponentBatch::empty<rerun::components::Text>(Descriptor_speaker).value_or_throw();
        archetype.source_id =
            ComponentBatch::empty<rerun::components::AudioSourceId>(Descriptor_source_id)
                .value_or_throw();
        archetype.audio_reference =
            ComponentBatch::empty<rerun::components::EntityPath>(Descriptor_audio_reference)
                .value_or_throw();
        archetype.related = ComponentBatch::empty<rerun::components::EntityPath>(Descriptor_related)
                                .value_or_throw();
        archetype.metadata =
            ComponentBatch::empty<rerun::components::KeyValuePairs>(Descriptor_metadata)
                .value_or_throw();
        archetype.colors =
            ComponentBatch::empty<rerun::components::Color>(Descriptor_colors).value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioAnnotationSpan::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(11);
        if (start_time.has_value()) {
            columns.push_back(start_time.value().partitioned(lengths_).value_or_throw());
        }
        if (end_time.has_value()) {
            columns.push_back(end_time.value().partitioned(lengths_).value_or_throw());
        }
        if (kind.has_value()) {
            columns.push_back(kind.value().partitioned(lengths_).value_or_throw());
        }
        if (labels.has_value()) {
            columns.push_back(labels.value().partitioned(lengths_).value_or_throw());
        }
        if (confidence.has_value()) {
            columns.push_back(confidence.value().partitioned(lengths_).value_or_throw());
        }
        if (speaker.has_value()) {
            columns.push_back(speaker.value().partitioned(lengths_).value_or_throw());
        }
        if (source_id.has_value()) {
            columns.push_back(source_id.value().partitioned(lengths_).value_or_throw());
        }
        if (audio_reference.has_value()) {
            columns.push_back(audio_reference.value().partitioned(lengths_).value_or_throw());
        }
        if (related.has_value()) {
            columns.push_back(related.value().partitioned(lengths_).value_or_throw());
        }
        if (metadata.has_value()) {
            columns.push_back(metadata.value().partitioned(lengths_).value_or_throw());
        }
        if (colors.has_value()) {
            columns.push_back(colors.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioAnnotationSpan::columns() {
        if (start_time.has_value()) {
            return columns(std::vector<uint32_t>(start_time.value().length(), 1));
        }
        if (end_time.has_value()) {
            return columns(std::vector<uint32_t>(end_time.value().length(), 1));
        }
        if (kind.has_value()) {
            return columns(std::vector<uint32_t>(kind.value().length(), 1));
        }
        if (labels.has_value()) {
            return columns(std::vector<uint32_t>(labels.value().length(), 1));
        }
        if (confidence.has_value()) {
            return columns(std::vector<uint32_t>(confidence.value().length(), 1));
        }
        if (speaker.has_value()) {
            return columns(std::vector<uint32_t>(speaker.value().length(), 1));
        }
        if (source_id.has_value()) {
            return columns(std::vector<uint32_t>(source_id.value().length(), 1));
        }
        if (audio_reference.has_value()) {
            return columns(std::vector<uint32_t>(audio_reference.value().length(), 1));
        }
        if (related.has_value()) {
            return columns(std::vector<uint32_t>(related.value().length(), 1));
        }
        if (metadata.has_value()) {
            return columns(std::vector<uint32_t>(metadata.value().length(), 1));
        }
        if (colors.has_value()) {
            return columns(std::vector<uint32_t>(colors.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioAnnotationSpan>::as_batches(
        const archetypes::AudioAnnotationSpan& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(11);

        if (archetype.start_time.has_value()) {
            cells.push_back(archetype.start_time.value());
        }
        if (archetype.end_time.has_value()) {
            cells.push_back(archetype.end_time.value());
        }
        if (archetype.kind.has_value()) {
            cells.push_back(archetype.kind.value());
        }
        if (archetype.labels.has_value()) {
            cells.push_back(archetype.labels.value());
        }
        if (archetype.confidence.has_value()) {
            cells.push_back(archetype.confidence.value());
        }
        if (archetype.speaker.has_value()) {
            cells.push_back(archetype.speaker.value());
        }
        if (archetype.source_id.has_value()) {
            cells.push_back(archetype.source_id.value());
        }
        if (archetype.audio_reference.has_value()) {
            cells.push_back(archetype.audio_reference.value());
        }
        if (archetype.related.has_value()) {
            cells.push_back(archetype.related.value());
        }
        if (archetype.metadata.has_value()) {
            cells.push_back(archetype.metadata.value());
        }
        if (archetype.colors.has_value()) {
            cells.push_back(archetype.colors.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
