// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_event.fbs".

#include "audio_event.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioEvent AudioEvent::clear_fields() {
        auto archetype = AudioEvent();
        archetype.event_time =
            ComponentBatch::empty<rerun::components::AudioTimestamp>(Descriptor_event_time)
                .value_or_throw();
        archetype.kind = ComponentBatch::empty<rerun::components::AudioEventKind>(Descriptor_kind)
                             .value_or_throw();
        archetype.labels =
            ComponentBatch::empty<rerun::components::Text>(Descriptor_labels).value_or_throw();
        archetype.source_id =
            ComponentBatch::empty<rerun::components::AudioSourceId>(Descriptor_source_id)
                .value_or_throw();
        archetype.audio_reference =
            ComponentBatch::empty<rerun::components::EntityPath>(Descriptor_audio_reference)
                .value_or_throw();
        archetype.related = ComponentBatch::empty<rerun::components::EntityPath>(Descriptor_related)
                                .value_or_throw();
        archetype.payload =
            ComponentBatch::empty<rerun::components::KeyValuePairs>(Descriptor_payload)
                .value_or_throw();
        archetype.colors =
            ComponentBatch::empty<rerun::components::Color>(Descriptor_colors).value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioEvent::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(8);
        if (event_time.has_value()) {
            columns.push_back(event_time.value().partitioned(lengths_).value_or_throw());
        }
        if (kind.has_value()) {
            columns.push_back(kind.value().partitioned(lengths_).value_or_throw());
        }
        if (labels.has_value()) {
            columns.push_back(labels.value().partitioned(lengths_).value_or_throw());
        }
        if (source_id.has_value()) {
            columns.push_back(source_id.value().partitioned(lengths_).value_or_throw());
        }
        if (audio_reference.has_value()) {
            columns.push_back(audio_reference.value().partitioned(lengths_).value_or_throw());
        }
        if (related.has_value()) {
            columns.push_back(related.value().partitioned(lengths_).value_or_throw());
        }
        if (payload.has_value()) {
            columns.push_back(payload.value().partitioned(lengths_).value_or_throw());
        }
        if (colors.has_value()) {
            columns.push_back(colors.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioEvent::columns() {
        if (event_time.has_value()) {
            return columns(std::vector<uint32_t>(event_time.value().length(), 1));
        }
        if (kind.has_value()) {
            return columns(std::vector<uint32_t>(kind.value().length(), 1));
        }
        if (labels.has_value()) {
            return columns(std::vector<uint32_t>(labels.value().length(), 1));
        }
        if (source_id.has_value()) {
            return columns(std::vector<uint32_t>(source_id.value().length(), 1));
        }
        if (audio_reference.has_value()) {
            return columns(std::vector<uint32_t>(audio_reference.value().length(), 1));
        }
        if (related.has_value()) {
            return columns(std::vector<uint32_t>(related.value().length(), 1));
        }
        if (payload.has_value()) {
            return columns(std::vector<uint32_t>(payload.value().length(), 1));
        }
        if (colors.has_value()) {
            return columns(std::vector<uint32_t>(colors.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioEvent>::as_batches(
        const archetypes::AudioEvent& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(8);

        if (archetype.event_time.has_value()) {
            cells.push_back(archetype.event_time.value());
        }
        if (archetype.kind.has_value()) {
            cells.push_back(archetype.kind.value());
        }
        if (archetype.labels.has_value()) {
            cells.push_back(archetype.labels.value());
        }
        if (archetype.source_id.has_value()) {
            cells.push_back(archetype.source_id.value());
        }
        if (archetype.audio_reference.has_value()) {
            cells.push_back(archetype.audio_reference.value());
        }
        if (archetype.related.has_value()) {
            cells.push_back(archetype.related.value());
        }
        if (archetype.payload.has_value()) {
            cells.push_back(archetype.payload.value());
        }
        if (archetype.colors.has_value()) {
            cells.push_back(archetype.colors.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
