// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_seek_index.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/audio_discontinuity.hpp"
#include "../components/audio_duration_samples.hpp"
#include "../components/audio_sequence_number.hpp"
#include "../components/audio_source_id.hpp"
#include "../components/audio_stream_id.hpp"
#include "../components/audio_timestamp.hpp"
#include "../components/entity_path.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: Materialized seek index for an audio source.
    ///
    /// Each row stores one batch of entries. The `media_time`, `decode_time`, and
    /// `trim_samples` arrays are parallel arrays. A playback runtime resolves a
    /// requested media time by choosing the nearest preceding `decode_time`,
    /// decoding forward, then trimming `trim_samples` samples from the decoded PCM.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioSeekIndex {
        /// Media time that this index entry accelerates.
        std::optional<ComponentBatch> media_time;

        /// Nearest preceding decoder reset / key / seekable boundary.
        std::optional<ComponentBatch> decode_time;

        /// Number of samples per channel to discard after decoding from `decode_time`.
        std::optional<ComponentBatch> trim_samples;

        /// Sequence number of the segment containing `decode_time`, if known.
        std::optional<ComponentBatch> sequence_number;

        /// Whether the entry crosses or starts at a discontinuity.
        std::optional<ComponentBatch> discontinuity;

        /// Stable identity of the audio source this index was derived from.
        std::optional<ComponentBatch> source_id;

        /// Entity carrying the source `archetypes::AudioStream` or `archetypes::AssetAudio`.
        std::optional<ComponentBatch> audio_reference;

        /// Continuity stream id associated with this index batch.
        std::optional<ComponentBatch> stream_id;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.AudioSeekIndex";

        /// `ComponentDescriptor` for the `media_time` field.
        static constexpr auto Descriptor_media_time = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:media_time",
            Loggable<rerun::components::AudioTimestamp>::ComponentType
        );
        /// `ComponentDescriptor` for the `decode_time` field.
        static constexpr auto Descriptor_decode_time = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:decode_time",
            Loggable<rerun::components::AudioTimestamp>::ComponentType
        );
        /// `ComponentDescriptor` for the `trim_samples` field.
        static constexpr auto Descriptor_trim_samples = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:trim_samples",
            Loggable<rerun::components::AudioDurationSamples>::ComponentType
        );
        /// `ComponentDescriptor` for the `sequence_number` field.
        static constexpr auto Descriptor_sequence_number = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:sequence_number",
            Loggable<rerun::components::AudioSequenceNumber>::ComponentType
        );
        /// `ComponentDescriptor` for the `discontinuity` field.
        static constexpr auto Descriptor_discontinuity = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:discontinuity",
            Loggable<rerun::components::AudioDiscontinuity>::ComponentType
        );
        /// `ComponentDescriptor` for the `source_id` field.
        static constexpr auto Descriptor_source_id = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:source_id",
            Loggable<rerun::components::AudioSourceId>::ComponentType
        );
        /// `ComponentDescriptor` for the `audio_reference` field.
        static constexpr auto Descriptor_audio_reference = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:audio_reference",
            Loggable<rerun::components::EntityPath>::ComponentType
        );
        /// `ComponentDescriptor` for the `stream_id` field.
        static constexpr auto Descriptor_stream_id = ComponentDescriptor(
            ArchetypeName, "AudioSeekIndex:stream_id",
            Loggable<rerun::components::AudioStreamId>::ComponentType
        );

      public:
        AudioSeekIndex() = default;
        AudioSeekIndex(AudioSeekIndex&& other) = default;
        AudioSeekIndex(const AudioSeekIndex& other) = default;
        AudioSeekIndex& operator=(const AudioSeekIndex& other) = default;
        AudioSeekIndex& operator=(AudioSeekIndex&& other) = default;

        explicit AudioSeekIndex(
            Collection<rerun::components::AudioTimestamp> _media_time,
            Collection<rerun::components::AudioTimestamp> _decode_time,
            Collection<rerun::components::AudioDurationSamples> _trim_samples
        )
            : media_time(
                  ComponentBatch::from_loggable(std::move(_media_time), Descriptor_media_time)
                      .value_or_throw()
              ),
              decode_time(
                  ComponentBatch::from_loggable(std::move(_decode_time), Descriptor_decode_time)
                      .value_or_throw()
              ),
              trim_samples(
                  ComponentBatch::from_loggable(std::move(_trim_samples), Descriptor_trim_samples)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `AudioSeekIndex`.
        static AudioSeekIndex update_fields() {
            return AudioSeekIndex();
        }

        /// Clear all the fields of a `AudioSeekIndex`.
        static AudioSeekIndex clear_fields();

        /// Media time that this index entry accelerates.
        AudioSeekIndex with_media_time(
            const Collection<rerun::components::AudioTimestamp>& _media_time
        ) && {
            media_time =
                ComponentBatch::from_loggable(_media_time, Descriptor_media_time).value_or_throw();
            return std::move(*this);
        }

        /// Nearest preceding decoder reset / key / seekable boundary.
        AudioSeekIndex with_decode_time(
            const Collection<rerun::components::AudioTimestamp>& _decode_time
        ) && {
            decode_time = ComponentBatch::from_loggable(_decode_time, Descriptor_decode_time)
                              .value_or_throw();
            return std::move(*this);
        }

        /// Number of samples per channel to discard after decoding from `decode_time`.
        AudioSeekIndex with_trim_samples(
            const Collection<rerun::components::AudioDurationSamples>& _trim_samples
        ) && {
            trim_samples = ComponentBatch::from_loggable(_trim_samples, Descriptor_trim_samples)
                               .value_or_throw();
            return std::move(*this);
        }

        /// Sequence number of the segment containing `decode_time`, if known.
        AudioSeekIndex with_sequence_number(
            const Collection<rerun::components::AudioSequenceNumber>& _sequence_number
        ) && {
            sequence_number =
                ComponentBatch::from_loggable(_sequence_number, Descriptor_sequence_number)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Whether the entry crosses or starts at a discontinuity.
        AudioSeekIndex with_discontinuity(
            const Collection<rerun::components::AudioDiscontinuity>& _discontinuity
        ) && {
            discontinuity = ComponentBatch::from_loggable(_discontinuity, Descriptor_discontinuity)
                                .value_or_throw();
            return std::move(*this);
        }

        /// Stable identity of the audio source this index was derived from.
        AudioSeekIndex with_source_id(const rerun::components::AudioSourceId& _source_id) && {
            source_id =
                ComponentBatch::from_loggable(_source_id, Descriptor_source_id).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `source_id` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_source_id` should
        /// be used when logging a single row's worth of data.
        AudioSeekIndex with_many_source_id(
            const Collection<rerun::components::AudioSourceId>& _source_id
        ) && {
            source_id =
                ComponentBatch::from_loggable(_source_id, Descriptor_source_id).value_or_throw();
            return std::move(*this);
        }

        /// Entity carrying the source `archetypes::AudioStream` or `archetypes::AssetAudio`.
        AudioSeekIndex with_audio_reference(const rerun::components::EntityPath& _audio_reference
        ) && {
            audio_reference =
                ComponentBatch::from_loggable(_audio_reference, Descriptor_audio_reference)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `audio_reference` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_audio_reference` should
        /// be used when logging a single row's worth of data.
        AudioSeekIndex with_many_audio_reference(
            const Collection<rerun::components::EntityPath>& _audio_reference
        ) && {
            audio_reference =
                ComponentBatch::from_loggable(_audio_reference, Descriptor_audio_reference)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Continuity stream id associated with this index batch.
        AudioSeekIndex with_stream_id(const rerun::components::AudioStreamId& _stream_id) && {
            stream_id =
                ComponentBatch::from_loggable(_stream_id, Descriptor_stream_id).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `stream_id` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_stream_id` should
        /// be used when logging a single row's worth of data.
        AudioSeekIndex with_many_stream_id(
            const Collection<rerun::components::AudioStreamId>& _stream_id
        ) && {
            stream_id =
                ComponentBatch::from_loggable(_stream_id, Descriptor_stream_id).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::AudioSeekIndex> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::AudioSeekIndex& archetype
        );
    };
} // namespace rerun
