// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_stream.fbs".

#include "audio_stream.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioStream AudioStream::clear_fields() {
        auto archetype = AudioStream();
        archetype.codec =
            ComponentBatch::empty<rerun::components::AudioCodec>(Descriptor_codec).value_or_throw();
        archetype.sample_rate =
            ComponentBatch::empty<rerun::components::AudioSampleRate>(Descriptor_sample_rate)
                .value_or_throw();
        archetype.channel_count =
            ComponentBatch::empty<rerun::components::AudioChannelCount>(Descriptor_channel_count)
                .value_or_throw();
        archetype.chunk =
            ComponentBatch::empty<rerun::components::AudioChunk>(Descriptor_chunk).value_or_throw();
        archetype.duration_samples = ComponentBatch::empty<rerun::components::AudioDurationSamples>(
                                         Descriptor_duration_samples
        )
                                         .value_or_throw();
        archetype.channel_layout =
            ComponentBatch::empty<rerun::components::AudioChannelLayout>(Descriptor_channel_layout)
                .value_or_throw();
        archetype.priming_delay =
            ComponentBatch::empty<rerun::components::AudioPrimingDelay>(Descriptor_priming_delay)
                .value_or_throw();
        archetype.stream_id =
            ComponentBatch::empty<rerun::components::AudioStreamId>(Descriptor_stream_id)
                .value_or_throw();
        archetype.sequence_number =
            ComponentBatch::empty<rerun::components::AudioSequenceNumber>(Descriptor_sequence_number
            )
                .value_or_throw();
        archetype.discontinuity =
            ComponentBatch::empty<rerun::components::AudioDiscontinuity>(Descriptor_discontinuity)
                .value_or_throw();
        archetype.seekable =
            ComponentBatch::empty<rerun::components::AudioSeekable>(Descriptor_seekable)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioStream::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(11);
        if (codec.has_value()) {
            columns.push_back(codec.value().partitioned(lengths_).value_or_throw());
        }
        if (sample_rate.has_value()) {
            columns.push_back(sample_rate.value().partitioned(lengths_).value_or_throw());
        }
        if (channel_count.has_value()) {
            columns.push_back(channel_count.value().partitioned(lengths_).value_or_throw());
        }
        if (chunk.has_value()) {
            columns.push_back(chunk.value().partitioned(lengths_).value_or_throw());
        }
        if (duration_samples.has_value()) {
            columns.push_back(duration_samples.value().partitioned(lengths_).value_or_throw());
        }
        if (channel_layout.has_value()) {
            columns.push_back(channel_layout.value().partitioned(lengths_).value_or_throw());
        }
        if (priming_delay.has_value()) {
            columns.push_back(priming_delay.value().partitioned(lengths_).value_or_throw());
        }
        if (stream_id.has_value()) {
            columns.push_back(stream_id.value().partitioned(lengths_).value_or_throw());
        }
        if (sequence_number.has_value()) {
            columns.push_back(sequence_number.value().partitioned(lengths_).value_or_throw());
        }
        if (discontinuity.has_value()) {
            columns.push_back(discontinuity.value().partitioned(lengths_).value_or_throw());
        }
        if (seekable.has_value()) {
            columns.push_back(seekable.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioStream::columns() {
        if (codec.has_value()) {
            return columns(std::vector<uint32_t>(codec.value().length(), 1));
        }
        if (sample_rate.has_value()) {
            return columns(std::vector<uint32_t>(sample_rate.value().length(), 1));
        }
        if (channel_count.has_value()) {
            return columns(std::vector<uint32_t>(channel_count.value().length(), 1));
        }
        if (chunk.has_value()) {
            return columns(std::vector<uint32_t>(chunk.value().length(), 1));
        }
        if (duration_samples.has_value()) {
            return columns(std::vector<uint32_t>(duration_samples.value().length(), 1));
        }
        if (channel_layout.has_value()) {
            return columns(std::vector<uint32_t>(channel_layout.value().length(), 1));
        }
        if (priming_delay.has_value()) {
            return columns(std::vector<uint32_t>(priming_delay.value().length(), 1));
        }
        if (stream_id.has_value()) {
            return columns(std::vector<uint32_t>(stream_id.value().length(), 1));
        }
        if (sequence_number.has_value()) {
            return columns(std::vector<uint32_t>(sequence_number.value().length(), 1));
        }
        if (discontinuity.has_value()) {
            return columns(std::vector<uint32_t>(discontinuity.value().length(), 1));
        }
        if (seekable.has_value()) {
            return columns(std::vector<uint32_t>(seekable.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioStream>::as_batches(
        const archetypes::AudioStream& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(11);

        if (archetype.codec.has_value()) {
            cells.push_back(archetype.codec.value());
        }
        if (archetype.sample_rate.has_value()) {
            cells.push_back(archetype.sample_rate.value());
        }
        if (archetype.channel_count.has_value()) {
            cells.push_back(archetype.channel_count.value());
        }
        if (archetype.chunk.has_value()) {
            cells.push_back(archetype.chunk.value());
        }
        if (archetype.duration_samples.has_value()) {
            cells.push_back(archetype.duration_samples.value());
        }
        if (archetype.channel_layout.has_value()) {
            cells.push_back(archetype.channel_layout.value());
        }
        if (archetype.priming_delay.has_value()) {
            cells.push_back(archetype.priming_delay.value());
        }
        if (archetype.stream_id.has_value()) {
            cells.push_back(archetype.stream_id.value());
        }
        if (archetype.sequence_number.has_value()) {
            cells.push_back(archetype.sequence_number.value());
        }
        if (archetype.discontinuity.has_value()) {
            cells.push_back(archetype.discontinuity.value());
        }
        if (archetype.seekable.has_value()) {
            cells.push_back(archetype.seekable.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
