// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_sample_reference.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/audio_timestamp.hpp"
#include "../components/entity_path.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: References a single position inside an `archetypes::AssetAudio`.
    ///
    /// Used to bind the media time of a complete audio asset to a Rerun timeline.
    /// Log one `archetypes::AudioSampleReference` at each timeline position where
    /// the asset should be "at" the given media timestamp; between references
    /// the viewer interpolates linearly in media-time.
    ///
    /// To play an entire asset aligned to a timeline, log a reference at the
    /// start of the asset and another at the end — or, equivalently, log a
    /// reference per visible frame for sub-frame alignment.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioSampleReference {
        /// The media-time position inside the referenced audio asset.
        ///
        /// Timestamps are nanoseconds relative to the start of the asset.
        std::optional<ComponentBatch> timestamp;

        /// Optional reference to the entity that carries the `archetypes::AssetAudio`.
        ///
        /// If omitted, the asset is assumed to be on the same entity.
        /// Blueprint overrides on the referenced asset are ignored — this is
        /// always resolved against the data store.
        std::optional<ComponentBatch> audio_reference;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.AudioSampleReference";

        /// `ComponentDescriptor` for the `timestamp` field.
        static constexpr auto Descriptor_timestamp = ComponentDescriptor(
            ArchetypeName, "AudioSampleReference:timestamp",
            Loggable<rerun::components::AudioTimestamp>::ComponentType
        );
        /// `ComponentDescriptor` for the `audio_reference` field.
        static constexpr auto Descriptor_audio_reference = ComponentDescriptor(
            ArchetypeName, "AudioSampleReference:audio_reference",
            Loggable<rerun::components::EntityPath>::ComponentType
        );

      public:
        AudioSampleReference() = default;
        AudioSampleReference(AudioSampleReference&& other) = default;
        AudioSampleReference(const AudioSampleReference& other) = default;
        AudioSampleReference& operator=(const AudioSampleReference& other) = default;
        AudioSampleReference& operator=(AudioSampleReference&& other) = default;

        explicit AudioSampleReference(rerun::components::AudioTimestamp _timestamp)
            : timestamp(ComponentBatch::from_loggable(std::move(_timestamp), Descriptor_timestamp)
                            .value_or_throw()) {}

        /// Update only some specific fields of a `AudioSampleReference`.
        static AudioSampleReference update_fields() {
            return AudioSampleReference();
        }

        /// Clear all the fields of a `AudioSampleReference`.
        static AudioSampleReference clear_fields();

        /// The media-time position inside the referenced audio asset.
        ///
        /// Timestamps are nanoseconds relative to the start of the asset.
        AudioSampleReference with_timestamp(const rerun::components::AudioTimestamp& _timestamp
        ) && {
            timestamp =
                ComponentBatch::from_loggable(_timestamp, Descriptor_timestamp).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `timestamp` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_timestamp` should
        /// be used when logging a single row's worth of data.
        AudioSampleReference with_many_timestamp(
            const Collection<rerun::components::AudioTimestamp>& _timestamp
        ) && {
            timestamp =
                ComponentBatch::from_loggable(_timestamp, Descriptor_timestamp).value_or_throw();
            return std::move(*this);
        }

        /// Optional reference to the entity that carries the `archetypes::AssetAudio`.
        ///
        /// If omitted, the asset is assumed to be on the same entity.
        /// Blueprint overrides on the referenced asset are ignored — this is
        /// always resolved against the data store.
        AudioSampleReference with_audio_reference(
            const rerun::components::EntityPath& _audio_reference
        ) && {
            audio_reference =
                ComponentBatch::from_loggable(_audio_reference, Descriptor_audio_reference)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `audio_reference` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_audio_reference` should
        /// be used when logging a single row's worth of data.
        AudioSampleReference with_many_audio_reference(
            const Collection<rerun::components::EntityPath>& _audio_reference
        ) && {
            audio_reference =
                ComponentBatch::from_loggable(_audio_reference, Descriptor_audio_reference)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::AudioSampleReference> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::AudioSampleReference& archetype
        );
    };
} // namespace rerun
