// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_seek_index.fbs".

#include "audio_seek_index.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioSeekIndex AudioSeekIndex::clear_fields() {
        auto archetype = AudioSeekIndex();
        archetype.media_time =
            ComponentBatch::empty<rerun::components::AudioTimestamp>(Descriptor_media_time)
                .value_or_throw();
        archetype.decode_time =
            ComponentBatch::empty<rerun::components::AudioTimestamp>(Descriptor_decode_time)
                .value_or_throw();
        archetype.trim_samples =
            ComponentBatch::empty<rerun::components::AudioDurationSamples>(Descriptor_trim_samples)
                .value_or_throw();
        archetype.sequence_number =
            ComponentBatch::empty<rerun::components::AudioSequenceNumber>(Descriptor_sequence_number
            )
                .value_or_throw();
        archetype.discontinuity =
            ComponentBatch::empty<rerun::components::AudioDiscontinuity>(Descriptor_discontinuity)
                .value_or_throw();
        archetype.source_id =
            ComponentBatch::empty<rerun::components::AudioSourceId>(Descriptor_source_id)
                .value_or_throw();
        archetype.audio_reference =
            ComponentBatch::empty<rerun::components::EntityPath>(Descriptor_audio_reference)
                .value_or_throw();
        archetype.stream_id =
            ComponentBatch::empty<rerun::components::AudioStreamId>(Descriptor_stream_id)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioSeekIndex::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(8);
        if (media_time.has_value()) {
            columns.push_back(media_time.value().partitioned(lengths_).value_or_throw());
        }
        if (decode_time.has_value()) {
            columns.push_back(decode_time.value().partitioned(lengths_).value_or_throw());
        }
        if (trim_samples.has_value()) {
            columns.push_back(trim_samples.value().partitioned(lengths_).value_or_throw());
        }
        if (sequence_number.has_value()) {
            columns.push_back(sequence_number.value().partitioned(lengths_).value_or_throw());
        }
        if (discontinuity.has_value()) {
            columns.push_back(discontinuity.value().partitioned(lengths_).value_or_throw());
        }
        if (source_id.has_value()) {
            columns.push_back(source_id.value().partitioned(lengths_).value_or_throw());
        }
        if (audio_reference.has_value()) {
            columns.push_back(audio_reference.value().partitioned(lengths_).value_or_throw());
        }
        if (stream_id.has_value()) {
            columns.push_back(stream_id.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioSeekIndex::columns() {
        if (media_time.has_value()) {
            return columns(std::vector<uint32_t>(media_time.value().length(), 1));
        }
        if (decode_time.has_value()) {
            return columns(std::vector<uint32_t>(decode_time.value().length(), 1));
        }
        if (trim_samples.has_value()) {
            return columns(std::vector<uint32_t>(trim_samples.value().length(), 1));
        }
        if (sequence_number.has_value()) {
            return columns(std::vector<uint32_t>(sequence_number.value().length(), 1));
        }
        if (discontinuity.has_value()) {
            return columns(std::vector<uint32_t>(discontinuity.value().length(), 1));
        }
        if (source_id.has_value()) {
            return columns(std::vector<uint32_t>(source_id.value().length(), 1));
        }
        if (audio_reference.has_value()) {
            return columns(std::vector<uint32_t>(audio_reference.value().length(), 1));
        }
        if (stream_id.has_value()) {
            return columns(std::vector<uint32_t>(stream_id.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioSeekIndex>::as_batches(
        const archetypes::AudioSeekIndex& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(8);

        if (archetype.media_time.has_value()) {
            cells.push_back(archetype.media_time.value());
        }
        if (archetype.decode_time.has_value()) {
            cells.push_back(archetype.decode_time.value());
        }
        if (archetype.trim_samples.has_value()) {
            cells.push_back(archetype.trim_samples.value());
        }
        if (archetype.sequence_number.has_value()) {
            cells.push_back(archetype.sequence_number.value());
        }
        if (archetype.discontinuity.has_value()) {
            cells.push_back(archetype.discontinuity.value());
        }
        if (archetype.source_id.has_value()) {
            cells.push_back(archetype.source_id.value());
        }
        if (archetype.audio_reference.has_value()) {
            cells.push_back(archetype.audio_reference.value());
        }
        if (archetype.stream_id.has_value()) {
            cells.push_back(archetype.stream_id.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
