// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_sample_reference.fbs".

#include "audio_sample_reference.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioSampleReference AudioSampleReference::clear_fields() {
        auto archetype = AudioSampleReference();
        archetype.timestamp =
            ComponentBatch::empty<rerun::components::AudioTimestamp>(Descriptor_timestamp)
                .value_or_throw();
        archetype.audio_reference =
            ComponentBatch::empty<rerun::components::EntityPath>(Descriptor_audio_reference)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioSampleReference::columns(const Collection<uint32_t>& lengths_
    ) {
        std::vector<ComponentColumn> columns;
        columns.reserve(2);
        if (timestamp.has_value()) {
            columns.push_back(timestamp.value().partitioned(lengths_).value_or_throw());
        }
        if (audio_reference.has_value()) {
            columns.push_back(audio_reference.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioSampleReference::columns() {
        if (timestamp.has_value()) {
            return columns(std::vector<uint32_t>(timestamp.value().length(), 1));
        }
        if (audio_reference.has_value()) {
            return columns(std::vector<uint32_t>(audio_reference.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioSampleReference>::as_batches(
        const archetypes::AudioSampleReference& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(2);

        if (archetype.timestamp.has_value()) {
            cells.push_back(archetype.timestamp.value());
        }
        if (archetype.audio_reference.has_value()) {
            cells.push_back(archetype.audio_reference.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
