// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_event.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/audio_event_kind.hpp"
#include "../components/audio_source_id.hpp"
#include "../components/audio_timestamp.hpp"
#include "../components/color.hpp"
#include "../components/entity_path.hpp"
#include "../components/key_value_pairs.hpp"
#include "../components/text.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: Audio-aligned point events.
    ///
    /// Use for decoder resets, ASR finalization, diarization switches, endpoint
    /// commits, barge-in detection, agent state transitions, and latency markers.
    ///
    /// Each row stores one or more events using parallel arrays. The row timestamp
    /// can still carry the event on a Rerun timeline; `event_time` records the
    /// source media time so events remain useful for complete audio assets and
    /// exported clips.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioEvent {
        /// Media-time timestamp of each event, in nanoseconds.
        std::optional<ComponentBatch> event_time;

        /// Semantic class of each event.
        std::optional<ComponentBatch> kind;

        /// Human-readable event label.
        std::optional<ComponentBatch> labels;

        /// Stable identity of the audio source these events refer to.
        std::optional<ComponentBatch> source_id;

        /// Entity carrying the source `archetypes::AudioStream` or `archetypes::AssetAudio`.
        std::optional<ComponentBatch> audio_reference;

        /// Optional related entities, such as the span or model response that emitted the event.
        std::optional<ComponentBatch> related;

        /// Additional event metadata shared by this row.
        std::optional<ComponentBatch> payload;

        /// Optional display color per event.
        std::optional<ComponentBatch> colors;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.AudioEvent";

        /// `ComponentDescriptor` for the `event_time` field.
        static constexpr auto Descriptor_event_time = ComponentDescriptor(
            ArchetypeName, "AudioEvent:event_time",
            Loggable<rerun::components::AudioTimestamp>::ComponentType
        );
        /// `ComponentDescriptor` for the `kind` field.
        static constexpr auto Descriptor_kind = ComponentDescriptor(
            ArchetypeName, "AudioEvent:kind",
            Loggable<rerun::components::AudioEventKind>::ComponentType
        );
        /// `ComponentDescriptor` for the `labels` field.
        static constexpr auto Descriptor_labels = ComponentDescriptor(
            ArchetypeName, "AudioEvent:labels", Loggable<rerun::components::Text>::ComponentType
        );
        /// `ComponentDescriptor` for the `source_id` field.
        static constexpr auto Descriptor_source_id = ComponentDescriptor(
            ArchetypeName, "AudioEvent:source_id",
            Loggable<rerun::components::AudioSourceId>::ComponentType
        );
        /// `ComponentDescriptor` for the `audio_reference` field.
        static constexpr auto Descriptor_audio_reference = ComponentDescriptor(
            ArchetypeName, "AudioEvent:audio_reference",
            Loggable<rerun::components::EntityPath>::ComponentType
        );
        /// `ComponentDescriptor` for the `related` field.
        static constexpr auto Descriptor_related = ComponentDescriptor(
            ArchetypeName, "AudioEvent:related",
            Loggable<rerun::components::EntityPath>::ComponentType
        );
        /// `ComponentDescriptor` for the `payload` field.
        static constexpr auto Descriptor_payload = ComponentDescriptor(
            ArchetypeName, "AudioEvent:payload",
            Loggable<rerun::components::KeyValuePairs>::ComponentType
        );
        /// `ComponentDescriptor` for the `colors` field.
        static constexpr auto Descriptor_colors = ComponentDescriptor(
            ArchetypeName, "AudioEvent:colors", Loggable<rerun::components::Color>::ComponentType
        );

      public:
        AudioEvent() = default;
        AudioEvent(AudioEvent&& other) = default;
        AudioEvent(const AudioEvent& other) = default;
        AudioEvent& operator=(const AudioEvent& other) = default;
        AudioEvent& operator=(AudioEvent&& other) = default;

        explicit AudioEvent(
            Collection<rerun::components::AudioTimestamp> _event_time,
            Collection<rerun::components::AudioEventKind> _kind
        )
            : event_time(
                  ComponentBatch::from_loggable(std::move(_event_time), Descriptor_event_time)
                      .value_or_throw()
              ),
              kind(ComponentBatch::from_loggable(std::move(_kind), Descriptor_kind).value_or_throw()
              ) {}

        /// Update only some specific fields of a `AudioEvent`.
        static AudioEvent update_fields() {
            return AudioEvent();
        }

        /// Clear all the fields of a `AudioEvent`.
        static AudioEvent clear_fields();

        /// Media-time timestamp of each event, in nanoseconds.
        AudioEvent with_event_time(const Collection<rerun::components::AudioTimestamp>& _event_time
        ) && {
            event_time =
                ComponentBatch::from_loggable(_event_time, Descriptor_event_time).value_or_throw();
            return std::move(*this);
        }

        /// Semantic class of each event.
        AudioEvent with_kind(const Collection<rerun::components::AudioEventKind>& _kind) && {
            kind = ComponentBatch::from_loggable(_kind, Descriptor_kind).value_or_throw();
            return std::move(*this);
        }

        /// Human-readable event label.
        AudioEvent with_labels(const Collection<rerun::components::Text>& _labels) && {
            labels = ComponentBatch::from_loggable(_labels, Descriptor_labels).value_or_throw();
            return std::move(*this);
        }

        /// Stable identity of the audio source these events refer to.
        AudioEvent with_source_id(const rerun::components::AudioSourceId& _source_id) && {
            source_id =
                ComponentBatch::from_loggable(_source_id, Descriptor_source_id).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `source_id` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_source_id` should
        /// be used when logging a single row's worth of data.
        AudioEvent with_many_source_id(
            const Collection<rerun::components::AudioSourceId>& _source_id
        ) && {
            source_id =
                ComponentBatch::from_loggable(_source_id, Descriptor_source_id).value_or_throw();
            return std::move(*this);
        }

        /// Entity carrying the source `archetypes::AudioStream` or `archetypes::AssetAudio`.
        AudioEvent with_audio_reference(const rerun::components::EntityPath& _audio_reference) && {
            audio_reference =
                ComponentBatch::from_loggable(_audio_reference, Descriptor_audio_reference)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `audio_reference` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_audio_reference` should
        /// be used when logging a single row's worth of data.
        AudioEvent with_many_audio_reference(
            const Collection<rerun::components::EntityPath>& _audio_reference
        ) && {
            audio_reference =
                ComponentBatch::from_loggable(_audio_reference, Descriptor_audio_reference)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Optional related entities, such as the span or model response that emitted the event.
        AudioEvent with_related(const Collection<rerun::components::EntityPath>& _related) && {
            related = ComponentBatch::from_loggable(_related, Descriptor_related).value_or_throw();
            return std::move(*this);
        }

        /// Additional event metadata shared by this row.
        AudioEvent with_payload(const rerun::components::KeyValuePairs& _payload) && {
            payload = ComponentBatch::from_loggable(_payload, Descriptor_payload).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `payload` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_payload` should
        /// be used when logging a single row's worth of data.
        AudioEvent with_many_payload(const Collection<rerun::components::KeyValuePairs>& _payload
        ) && {
            payload = ComponentBatch::from_loggable(_payload, Descriptor_payload).value_or_throw();
            return std::move(*this);
        }

        /// Optional display color per event.
        AudioEvent with_colors(const Collection<rerun::components::Color>& _colors) && {
            colors = ComponentBatch::from_loggable(_colors, Descriptor_colors).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::AudioEvent> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(const archetypes::AudioEvent& archetype
        );
    };
} // namespace rerun
