# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_sample_rate.fbs".

# You can extend this class by creating a "AudioSampleRateExt" class in "audio_sample_rate_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioSampleRate", "AudioSampleRateBatch"]


class AudioSampleRate(datatypes.UInt32, ComponentMixin):
    """
    **Component**: Audio sample rate in Hertz.

    Typical values: `8000`, `16000`, `24000`, `44100`, `48000`.

    For Opus, this is the decoder's reported output rate; libopus will
    internally resample to this value.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioSampleRateExt in audio_sample_rate_ext.py

    # Note: there are no fields here because AudioSampleRate delegates to datatypes.UInt32


class AudioSampleRateBatch(datatypes.UInt32Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioSampleRate"


# This is patched in late to avoid circular dependencies.
AudioSampleRate._BATCH_TYPE = AudioSampleRateBatch  # type: ignore[assignment]
