# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_duration_samples.fbs".

# You can extend this class by creating a "AudioDurationSamplesExt" class in "audio_duration_samples_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioDurationSamples", "AudioDurationSamplesBatch"]


class AudioDurationSamples(datatypes.UInt64, ComponentMixin):
    """
    **Component**: Number of PCM samples per channel produced by decoding a single [`components.AudioChunk`][rerun.components.AudioChunk].

    Kept as an explicit column so that the viewer and downstream queries do
    not need to decode the payload to know its span. For Opus this is
    typically `sample_rate * frame_size_ms / 1000` (e.g. 480 samples for 20 ms
    at 24 kHz).

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioDurationSamplesExt in audio_duration_samples_ext.py

    # Note: there are no fields here because AudioDurationSamples delegates to datatypes.UInt64


class AudioDurationSamplesBatch(datatypes.UInt64Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioDurationSamples"


# This is patched in late to avoid circular dependencies.
AudioDurationSamples._BATCH_TYPE = AudioDurationSamplesBatch  # type: ignore[assignment]
