# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_chunk.fbs".

# You can extend this class by creating a "AudioChunkExt" class in "audio_chunk_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioChunk", "AudioChunkBatch"]


class AudioChunk(datatypes.Blob, ComponentMixin):
    """
    **Component**: A time-bounded, decodable segment of encoded audio.

    A chunk is the fundamental temporal unit of an [`archetypes.AudioStream`][rerun.archetypes.AudioStream]:
    each logged row represents one segment that can be handed to the decoder
    without referencing data from any other row (any cross-segment decoder
    state is reset at segment boundaries marked by [`components.AudioDiscontinuity`][rerun.components.AudioDiscontinuity]
    or [`components.AudioSeekable`][rerun.components.AudioSeekable]).

    The row's timeline timestamp is treated as the presentation timestamp (PTS)
    of the first sample in the chunk. The number of PCM samples produced per
    channel is carried alongside in [`components.AudioDurationSamples`][rerun.components.AudioDurationSamples].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioChunkExt in audio_chunk_ext.py

    # Note: there are no fields here because AudioChunk delegates to datatypes.Blob


class AudioChunkBatch(datatypes.BlobBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioChunk"


# This is patched in late to avoid circular dependencies.
AudioChunk._BATCH_TYPE = AudioChunkBatch  # type: ignore[assignment]
