# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_source_id.fbs".

# You can extend this class by creating a "AudioSourceIdExt" class in "audio_source_id_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioSourceId", "AudioSourceIdBatch"]


class AudioSourceId(datatypes.Utf8, ComponentMixin):
    """
    **Component**: Stable identity for an audio source across streams, assets, summaries, and annotations.

    This is intentionally independent from entity path: an entity path names where
    data was logged, while an audio source id names the logical recording, device,
    track, or pipeline output that downstream derived data refers to.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioSourceIdExt in audio_source_id_ext.py

    # Note: there are no fields here because AudioSourceId delegates to datatypes.Utf8


class AudioSourceIdBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioSourceId"


# This is patched in late to avoid circular dependencies.
AudioSourceId._BATCH_TYPE = AudioSourceIdBatch  # type: ignore[assignment]
