# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_codec.fbs".

# You can extend this class by creating a "AudioCodecExt" class in "audio_codec_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

import pyarrow as pa

from .._baseclasses import (
    BaseBatch,
    ComponentBatchMixin,
)

__all__ = ["AudioCodec", "AudioCodecArrayLike", "AudioCodecBatch", "AudioCodecLike"]


from enum import Enum


class AudioCodec(Enum):
    """
    **Component**: The codec used to encode audio stored in [`components.AudioChunk`][rerun.components.AudioChunk].

    Enum values are the big-endian packing of the `WebCodecs` audio codec string
    (same convention used by [`components.VideoCodec`][rerun.components.VideoCodec]).

    Support of these codecs by the Rerun Viewer is platform dependent.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    Flac = 0x666C6163
    """
    Free Lossless Audio Codec (FLAC).

    Each [`components.AudioChunk`][rerun.components.AudioChunk] is expected to contain one or more complete FLAC frames.

    Enum value is the fourcc for `'flac'` (the `WebCodecs` string for FLAC) in big endian.
    """

    Opus = 0x6F707573
    """
    Opus — RFC 6716.

    Streams are expected to contain one or more raw Opus packets per
    [`components.AudioChunk`][rerun.components.AudioChunk]. Any sample rate supported by the decoder
    (8/12/16/24/48 kHz) is valid. Libopus handles internal resampling to
    48 kHz but the logged [`components.AudioSampleRate`][rerun.components.AudioSampleRate] is treated as
    authoritative for downstream analysis.

    Enum value is the fourcc for `'opus'` (the `WebCodecs` string for Opus) in big endian.
    """

    @classmethod
    def auto(cls, val: str | int | AudioCodec) -> AudioCodec:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, AudioCodec):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


AudioCodecLike = AudioCodec | Literal["Flac", "Opus", "flac", "opus"] | int
"""A type alias for any AudioCodec-like object."""

AudioCodecArrayLike = AudioCodec | Literal["Flac", "Opus", "flac", "opus"] | int | Sequence[AudioCodecLike]
"""A type alias for any AudioCodec-like array object."""


class AudioCodecBatch(BaseBatch[AudioCodecArrayLike], ComponentBatchMixin):
    _ARROW_DATATYPE = pa.uint32()
    _COMPONENT_TYPE: str = "rerun.components.AudioCodec"

    @staticmethod
    def _native_to_pa_array(data: AudioCodecArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (AudioCodec, int, str)):
            data = [data]

        pa_data = [AudioCodec.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]  # ty: ignore[not-iterable]

        return pa.array(pa_data, type=data_type)
