# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_timestamp.fbs".

# You can extend this class by creating a "AudioTimestampExt" class in "audio_timestamp_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioTimestamp", "AudioTimestampBatch"]


class AudioTimestamp(datatypes.AudioTimestamp, ComponentMixin):
    """
    **Component**: Timestamp inside an [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioTimestampExt in audio_timestamp_ext.py

    # Note: there are no fields here because AudioTimestamp delegates to datatypes.AudioTimestamp


class AudioTimestampBatch(datatypes.AudioTimestampBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioTimestamp"


# This is patched in late to avoid circular dependencies.
AudioTimestamp._BATCH_TYPE = AudioTimestampBatch  # type: ignore[assignment]
