# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_annotation_kind.fbs".

# You can extend this class by creating a "AudioAnnotationKindExt" class in "audio_annotation_kind_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

import pyarrow as pa

from .._baseclasses import (
    BaseBatch,
    ComponentBatchMixin,
)

__all__ = ["AudioAnnotationKind", "AudioAnnotationKindArrayLike", "AudioAnnotationKindBatch", "AudioAnnotationKindLike"]


from enum import Enum


class AudioAnnotationKind(Enum):
    """
    **Component**: Semantic class of an audio-aligned time span.

    These variants cover the common observability lanes for speech and agent
    replay. Use [`components.KeyValuePairs`][rerun.components.KeyValuePairs] on the archetype for domain-specific
    labels that do not need to become schema.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    AsrUtterance = 1
    """A finalized or partial ASR utterance."""

    Word = 2
    """A word-level alignment span."""

    Token = 3
    """A token-level alignment span."""

    SpeakerTurn = 4
    """A diarization speaker turn."""

    Vad = 5
    """Voice activity detection region."""

    Endpointing = 6
    """Endpointing or turn-boundary decision window."""

    Tts = 7
    """Synthesized speech emitted by a TTS/model output path."""

    Interruption = 8
    """Overlap, interruption, or barge-in region."""

    ErrorRegion = 9
    """Region marked for error analysis or review."""

    @classmethod
    def auto(cls, val: str | int | AudioAnnotationKind) -> AudioAnnotationKind:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, AudioAnnotationKind):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


AudioAnnotationKindLike = (
    AudioAnnotationKind
    | Literal[
        "AsrUtterance",
        "Endpointing",
        "ErrorRegion",
        "Interruption",
        "SpeakerTurn",
        "Token",
        "Tts",
        "Vad",
        "Word",
        "asrutterance",
        "endpointing",
        "errorregion",
        "interruption",
        "speakerturn",
        "token",
        "tts",
        "vad",
        "word",
    ]
    | int
)
"""A type alias for any AudioAnnotationKind-like object."""

AudioAnnotationKindArrayLike = (
    AudioAnnotationKind
    | Literal[
        "AsrUtterance",
        "Endpointing",
        "ErrorRegion",
        "Interruption",
        "SpeakerTurn",
        "Token",
        "Tts",
        "Vad",
        "Word",
        "asrutterance",
        "endpointing",
        "errorregion",
        "interruption",
        "speakerturn",
        "token",
        "tts",
        "vad",
        "word",
    ]
    | int
    | Sequence[AudioAnnotationKindLike]
)
"""A type alias for any AudioAnnotationKind-like array object."""


class AudioAnnotationKindBatch(BaseBatch[AudioAnnotationKindArrayLike], ComponentBatchMixin):
    _ARROW_DATATYPE = pa.uint8()
    _COMPONENT_TYPE: str = "rerun.components.AudioAnnotationKind"

    @staticmethod
    def _native_to_pa_array(data: AudioAnnotationKindArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (AudioAnnotationKind, int, str)):
            data = [data]

        pa_data = [AudioAnnotationKind.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]  # ty: ignore[not-iterable]

        return pa.array(pa_data, type=data_type)
