# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_sequence_number.fbs".

# You can extend this class by creating a "AudioSequenceNumberExt" class in "audio_sequence_number_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioSequenceNumber", "AudioSequenceNumberBatch"]


class AudioSequenceNumber(datatypes.UInt64, ComponentMixin):
    """
    **Component**: Monotonic per-stream sequence number for a chunk.

    Useful for gap detection: a jump greater than 1 between successive rows
    (within the same [`components.AudioStreamId`][rerun.components.AudioStreamId]) surfaces a missing segment
    to the viewer without requiring payload inspection.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioSequenceNumberExt in audio_sequence_number_ext.py

    # Note: there are no fields here because AudioSequenceNumber delegates to datatypes.UInt64


class AudioSequenceNumberBatch(datatypes.UInt64Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioSequenceNumber"


# This is patched in late to avoid circular dependencies.
AudioSequenceNumber._BATCH_TYPE = AudioSequenceNumberBatch  # type: ignore[assignment]
