# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_discontinuity.fbs".

# You can extend this class by creating a "AudioDiscontinuityExt" class in "audio_discontinuity_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioDiscontinuity", "AudioDiscontinuityBatch"]


class AudioDiscontinuity(datatypes.Bool, ComponentMixin):
    """
    **Component**: Marks a chunk as resuming after a gap or recorder reset.

    When true, the decoder state must be flushed before processing this chunk
    and any accumulated resampler / overlap-add state discarded. Chunks
    without this component are assumed continuous with the previous chunk on
    the same timeline + [`components.AudioStreamId`][rerun.components.AudioStreamId].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioDiscontinuityExt in audio_discontinuity_ext.py

    # Note: there are no fields here because AudioDiscontinuity delegates to datatypes.Bool


class AudioDiscontinuityBatch(datatypes.BoolBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioDiscontinuity"


# This is patched in late to avoid circular dependencies.
AudioDiscontinuity._BATCH_TYPE = AudioDiscontinuityBatch  # type: ignore[assignment]
