# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_seekable.fbs".

# You can extend this class by creating a "AudioSeekableExt" class in "audio_seekable_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioSeekable", "AudioSeekableBatch"]


class AudioSeekable(datatypes.Bool, ComponentMixin):
    """
    **Component**: Marks a chunk as an independent seek target.

    A seekable chunk can be handed to the decoder without replaying any
    earlier chunk. Default is true for codecs whose segments are always
    self-contained (e.g. Opus); codecs with inter-frame dependencies should
    set this false on non-key segments.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioSeekableExt in audio_seekable_ext.py

    # Note: there are no fields here because AudioSeekable delegates to datatypes.Bool


class AudioSeekableBatch(datatypes.BoolBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioSeekable"


# This is patched in late to avoid circular dependencies.
AudioSeekable._BATCH_TYPE = AudioSeekableBatch  # type: ignore[assignment]
