# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_priming_delay.fbs".

# You can extend this class by creating a "AudioPrimingDelayExt" class in "audio_priming_delay_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioPrimingDelay", "AudioPrimingDelayBatch"]


class AudioPrimingDelay(datatypes.UInt32, ComponentMixin):
    """
    **Component**: Number of PCM samples at the beginning of a stream to discard (encoder pre-roll).

    For Opus this is the pre-skip reported in the Ogg-Opus header (typically
    312 samples at 48 kHz). When logging raw packets without a container,
    record the value here so the decoder can trim output at stream start.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioPrimingDelayExt in audio_priming_delay_ext.py

    # Note: there are no fields here because AudioPrimingDelay delegates to datatypes.UInt32


class AudioPrimingDelayBatch(datatypes.UInt32Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioPrimingDelay"


# This is patched in late to avoid circular dependencies.
AudioPrimingDelay._BATCH_TYPE = AudioPrimingDelayBatch  # type: ignore[assignment]
