# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_stream_id.fbs".

# You can extend this class by creating a "AudioStreamIdExt" class in "audio_stream_id_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["AudioStreamId", "AudioStreamIdBatch"]


class AudioStreamId(datatypes.UInt64, ComponentMixin):
    """
    **Component**: Stream continuity marker.

    Rows that share a `stream_id` are considered parts of the same logical
    capture; a change in `stream_id` signals a recorder restart or resync and
    is treated as an implicit discontinuity.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AudioStreamIdExt in audio_stream_id_ext.py

    # Note: there are no fields here because AudioStreamId delegates to datatypes.UInt64


class AudioStreamIdBatch(datatypes.UInt64Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.AudioStreamId"


# This is patched in late to avoid circular dependencies.
AudioStreamId._BATCH_TYPE = AudioStreamIdBatch  # type: ignore[assignment]
