# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/audio_event_kind.fbs".

# You can extend this class by creating a "AudioEventKindExt" class in "audio_event_kind_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

import pyarrow as pa

from .._baseclasses import (
    BaseBatch,
    ComponentBatchMixin,
)

__all__ = ["AudioEventKind", "AudioEventKindArrayLike", "AudioEventKindBatch", "AudioEventKindLike"]


from enum import Enum


class AudioEventKind(Enum):
    """
    **Component**: Semantic class of an audio-aligned point event.

    Point events are used for instantaneous state changes and milestones that
    should be inspectable on the same timeline as audio, waveform summaries, and
    annotation spans.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    DecoderReset = 1
    """Decoder reset or reconfiguration."""

    AsrFinalized = 2
    """ASR segment finalized."""

    DiarizationSwitch = 3
    """Diarization speaker changed."""

    BargeIn = 4
    """Barge-in or interruption detected."""

    EndpointCommit = 5
    """Endpointing decision committed."""

    AgentStateTransition = 6
    """Agent/model state transition."""

    TurnPolicyChange = 7
    """Turn-taking policy changed."""

    LatencyMilestone = 8
    """Latency milestone or timing marker."""

    Discontinuity = 9
    """Source discontinuity, stream hole, or timestamp jump."""

    @classmethod
    def auto(cls, val: str | int | AudioEventKind) -> AudioEventKind:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, AudioEventKind):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


AudioEventKindLike = (
    AudioEventKind
    | Literal[
        "AgentStateTransition",
        "AsrFinalized",
        "BargeIn",
        "DecoderReset",
        "DiarizationSwitch",
        "Discontinuity",
        "EndpointCommit",
        "LatencyMilestone",
        "TurnPolicyChange",
        "agentstatetransition",
        "asrfinalized",
        "bargein",
        "decoderreset",
        "diarizationswitch",
        "discontinuity",
        "endpointcommit",
        "latencymilestone",
        "turnpolicychange",
    ]
    | int
)
"""A type alias for any AudioEventKind-like object."""

AudioEventKindArrayLike = (
    AudioEventKind
    | Literal[
        "AgentStateTransition",
        "AsrFinalized",
        "BargeIn",
        "DecoderReset",
        "DiarizationSwitch",
        "Discontinuity",
        "EndpointCommit",
        "LatencyMilestone",
        "TurnPolicyChange",
        "agentstatetransition",
        "asrfinalized",
        "bargein",
        "decoderreset",
        "diarizationswitch",
        "discontinuity",
        "endpointcommit",
        "latencymilestone",
        "turnpolicychange",
    ]
    | int
    | Sequence[AudioEventKindLike]
)
"""A type alias for any AudioEventKind-like array object."""


class AudioEventKindBatch(BaseBatch[AudioEventKindArrayLike], ComponentBatchMixin):
    _ARROW_DATATYPE = pa.uint8()
    _COMPONENT_TYPE: str = "rerun.components.AudioEventKind"

    @staticmethod
    def _native_to_pa_array(data: AudioEventKindArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (AudioEventKind, int, str)):
            data = [data]

        pa_data = [AudioEventKind.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]  # ty: ignore[not-iterable]

        return pa.array(pa_data, type=data_type)
