# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/audio_timestamp.fbs".

# You can extend this class by creating a "AudioTimestampExt" class in "audio_timestamp_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import numpy as np
import numpy.typing as npt
import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .._numpy_compatibility import asarray

__all__ = ["AudioTimestamp", "AudioTimestampArrayLike", "AudioTimestampBatch", "AudioTimestampLike"]


@define(init=False)
class AudioTimestamp:
    """
    **Datatype**: Presentation timestamp within an [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].

    Specified in nanoseconds. Typically measured as time since the start of the audio asset.
    """

    def __init__(self: Any, timestamp_ns: AudioTimestampLike) -> None:
        """
        Create a new instance of the AudioTimestamp datatype.

        Parameters
        ----------
        timestamp_ns:
            Presentation timestamp value in nanoseconds.

        """

        # You can define your own __init__ function as a member of AudioTimestampExt in audio_timestamp_ext.py
        self.__attrs_init__(timestamp_ns=timestamp_ns)

    timestamp_ns: int = field(converter=int)
    # Presentation timestamp value in nanoseconds.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    def __array__(self, dtype: npt.DTypeLike = None, copy: bool | None = None) -> npt.NDArray[Any]:
        # You can define your own __array__ function as a member of AudioTimestampExt in audio_timestamp_ext.py
        return asarray(self.timestamp_ns, dtype=dtype, copy=copy)

    def __int__(self) -> int:
        return int(self.timestamp_ns)

    def __hash__(self) -> int:
        return hash(self.timestamp_ns)


if TYPE_CHECKING:
    AudioTimestampLike = AudioTimestamp | int
    """A type alias for any AudioTimestamp-like object."""
else:
    AudioTimestampLike = Any

AudioTimestampArrayLike = AudioTimestamp | Sequence[AudioTimestampLike] | npt.NDArray[np.int64]
"""A type alias for any AudioTimestamp-like array object."""


class AudioTimestampBatch(BaseBatch[AudioTimestampArrayLike]):
    _ARROW_DATATYPE = pa.int64()

    @staticmethod
    def _native_to_pa_array(data: AudioTimestampArrayLike, data_type: pa.DataType) -> pa.Array:
        array = np.asarray(data, dtype=np.int64).flatten()
        return pa.array(array, type=data_type)
