# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

# You can extend this class by creating a "AssetAudioExt" class in "asset_audio_ext.py".

from __future__ import annotations

from typing import Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..error_utils import catch_and_log_exceptions

__all__ = ["AssetAudio"]


@define(str=False, repr=False, init=False)
class AssetAudio(Archetype):
    """
    **Archetype**: A complete audio asset.

    Represents a self-describing audio container (Ogg, FLAC, MP4/M4A, …) or
    a raw encoded blob accompanied by explicit codec and rate metadata.

    Supported container media types initially:
    * `audio/ogg` — Opus in Ogg, fully playable.
    * `audio/flac` — lossless, fully playable.

    To place the asset on a timeline, log a companion
    [`archetypes.AudioSampleReference`][rerun.archetypes.AudioSampleReference] on the same (or a referencing) entity
    at each playhead position you want the asset aligned to.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.AssetAudio"

    def __init__(
        self: Any,
        blob: datatypes.BlobLike,
        *,
        media_type: datatypes.Utf8Like | None = None,
        codec: components.AudioCodecLike | None = None,
        sample_rate: datatypes.UInt32Like | None = None,
        channel_count: datatypes.UInt16Like | None = None,
        channel_layout: components.AudioChannelLayoutLike | None = None,
    ) -> None:
        """
        Create a new instance of the AssetAudio archetype.

        Parameters
        ----------
        blob:
            The raw bytes of the audio asset.
        media_type:
            The IANA media type of the asset.

            If omitted, the viewer will try to sniff from the first bytes of the blob.
            If sniffing fails the asset is stored but playback is disabled.
        codec:
            Audio codec of the enclosed samples.

            When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
            this is redundant; logging it makes analysis queries cheaper.
        sample_rate:
            Decoded sample rate in Hz.
        channel_count:
            Decoded channel count.
        channel_layout:
            Speaker arrangement for the channels.

        """

        # You can define your own __init__ function as a member of AssetAudioExt in asset_audio_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                blob=blob,
                media_type=media_type,
                codec=codec,
                sample_rate=sample_rate,
                channel_count=channel_count,
                channel_layout=channel_layout,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            blob=None,
            media_type=None,
            codec=None,
            sample_rate=None,
            channel_count=None,
            channel_layout=None,
        )

    @classmethod
    def _clear(cls) -> AssetAudio:
        """Produce an empty AssetAudio, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        blob: datatypes.BlobLike | None = None,
        media_type: datatypes.Utf8Like | None = None,
        codec: components.AudioCodecLike | None = None,
        sample_rate: datatypes.UInt32Like | None = None,
        channel_count: datatypes.UInt16Like | None = None,
        channel_layout: components.AudioChannelLayoutLike | None = None,
    ) -> AssetAudio:
        """
        Update only some specific fields of a `AssetAudio`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        blob:
            The raw bytes of the audio asset.
        media_type:
            The IANA media type of the asset.

            If omitted, the viewer will try to sniff from the first bytes of the blob.
            If sniffing fails the asset is stored but playback is disabled.
        codec:
            Audio codec of the enclosed samples.

            When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
            this is redundant; logging it makes analysis queries cheaper.
        sample_rate:
            Decoded sample rate in Hz.
        channel_count:
            Decoded channel count.
        channel_layout:
            Speaker arrangement for the channels.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "blob": blob,
                "media_type": media_type,
                "codec": codec,
                "sample_rate": sample_rate,
                "channel_count": channel_count,
                "channel_layout": channel_layout,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> AssetAudio:
        """Clear all the fields of a `AssetAudio`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_blob() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AssetAudio:blob",
            archetype=AssetAudio.NAME,
            component_type=components.BlobBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_media_type() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AssetAudio:media_type",
            archetype=AssetAudio.NAME,
            component_type=components.MediaTypeBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_codec() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AssetAudio:codec",
            archetype=AssetAudio.NAME,
            component_type=components.AudioCodecBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_sample_rate() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AssetAudio:sample_rate",
            archetype=AssetAudio.NAME,
            component_type=components.AudioSampleRateBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_channel_count() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AssetAudio:channel_count",
            archetype=AssetAudio.NAME,
            component_type=components.AudioChannelCountBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_channel_layout() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AssetAudio:channel_layout",
            archetype=AssetAudio.NAME,
            component_type=components.AudioChannelLayoutBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        blob: datatypes.BlobArrayLike | None = None,
        media_type: datatypes.Utf8ArrayLike | None = None,
        codec: components.AudioCodecArrayLike | None = None,
        sample_rate: datatypes.UInt32ArrayLike | None = None,
        channel_count: datatypes.UInt16ArrayLike | None = None,
        channel_layout: components.AudioChannelLayoutArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        blob:
            The raw bytes of the audio asset.
        media_type:
            The IANA media type of the asset.

            If omitted, the viewer will try to sniff from the first bytes of the blob.
            If sniffing fails the asset is stored but playback is disabled.
        codec:
            Audio codec of the enclosed samples.

            When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
            this is redundant; logging it makes analysis queries cheaper.
        sample_rate:
            Decoded sample rate in Hz.
        channel_count:
            Decoded channel count.
        channel_layout:
            Speaker arrangement for the channels.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                blob=blob,
                media_type=media_type,
                codec=codec,
                sample_rate=sample_rate,
                channel_count=channel_count,
                channel_layout=channel_layout,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "AssetAudio:blob": blob,
            "AssetAudio:media_type": media_type,
            "AssetAudio:codec": codec,
            "AssetAudio:sample_rate": sample_rate,
            "AssetAudio:channel_count": channel_count,
            "AssetAudio:channel_layout": channel_layout,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    blob: components.BlobBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.BlobBatch._converter,  # type: ignore[misc]
    )
    # The raw bytes of the audio asset.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    media_type: components.MediaTypeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.MediaTypeBatch._converter,  # type: ignore[misc]
    )
    # The IANA media type of the asset.
    #
    # If omitted, the viewer will try to sniff from the first bytes of the blob.
    # If sniffing fails the asset is stored but playback is disabled.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    codec: components.AudioCodecBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioCodecBatch._converter,  # type: ignore[misc]
    )
    # Audio codec of the enclosed samples.
    #
    # When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
    # this is redundant; logging it makes analysis queries cheaper.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sample_rate: components.AudioSampleRateBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioSampleRateBatch._converter,  # type: ignore[misc]
    )
    # Decoded sample rate in Hz.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    channel_count: components.AudioChannelCountBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioChannelCountBatch._converter,  # type: ignore[misc]
    )
    # Decoded channel count.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    channel_layout: components.AudioChannelLayoutBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioChannelLayoutBatch._converter,  # type: ignore[misc]
    )
    # Speaker arrangement for the channels.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
