# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_waveform_summary.fbs".

# You can extend this class by creating a "AudioWaveformSummaryExt" class in "audio_waveform_summary_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["AudioWaveformSummary"]


@define(str=False, repr=False, init=False)
class AudioWaveformSummary(Archetype, VisualizableArchetype):
    """
    **Archetype**: Multi-resolution waveform summary buckets for an audio source.

    Each row stores one batch of summary buckets. The `bucket_start`,
    `bucket_duration_samples`, `min_amplitude`, and `max_amplitude` arrays are
    parallel arrays and should have the same length. Optional arrays such as
    `rms_amplitude` and `activity` are also parallel when present.

    These summaries are durable derived data: they can be logged, cached,
    queried, exported, and rendered without decoding source audio on every pan
    or zoom.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.AudioWaveformSummary"

    def __init__(
        self: Any,
        *,
        bucket_start: datatypes.AudioTimestampArrayLike,
        bucket_duration_samples: datatypes.UInt64ArrayLike,
        min_amplitude: datatypes.Float64ArrayLike,
        max_amplitude: datatypes.Float64ArrayLike,
        rms_amplitude: datatypes.Float64ArrayLike | None = None,
        activity: datatypes.Float64ArrayLike | None = None,
        source_id: datatypes.Utf8Like | None = None,
        audio_reference: datatypes.EntityPathLike | None = None,
    ) -> None:
        """
        Create a new instance of the AudioWaveformSummary archetype.

        Parameters
        ----------
        bucket_start:
            Media-time start of each summary bucket, in nanoseconds.
        bucket_duration_samples:
            Duration of each summary bucket, in samples per channel.
        min_amplitude:
            Minimum normalized amplitude in each bucket.
        max_amplitude:
            Maximum normalized amplitude in each bucket.
        rms_amplitude:
            Optional RMS or loudness-like summary for each bucket.
        activity:
            Optional activity/silence score for each bucket. Convention: 0 is silent, 1 is active.
        source_id:
            Stable identity of the audio source this summary was derived from.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].

        """

        # You can define your own __init__ function as a member of AudioWaveformSummaryExt in audio_waveform_summary_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                bucket_start=bucket_start,
                bucket_duration_samples=bucket_duration_samples,
                min_amplitude=min_amplitude,
                max_amplitude=max_amplitude,
                rms_amplitude=rms_amplitude,
                activity=activity,
                source_id=source_id,
                audio_reference=audio_reference,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            bucket_start=None,
            bucket_duration_samples=None,
            min_amplitude=None,
            max_amplitude=None,
            rms_amplitude=None,
            activity=None,
            source_id=None,
            audio_reference=None,
        )

    @classmethod
    def _clear(cls) -> AudioWaveformSummary:
        """Produce an empty AudioWaveformSummary, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        bucket_start: datatypes.AudioTimestampArrayLike | None = None,
        bucket_duration_samples: datatypes.UInt64ArrayLike | None = None,
        min_amplitude: datatypes.Float64ArrayLike | None = None,
        max_amplitude: datatypes.Float64ArrayLike | None = None,
        rms_amplitude: datatypes.Float64ArrayLike | None = None,
        activity: datatypes.Float64ArrayLike | None = None,
        source_id: datatypes.Utf8Like | None = None,
        audio_reference: datatypes.EntityPathLike | None = None,
    ) -> AudioWaveformSummary:
        """
        Update only some specific fields of a `AudioWaveformSummary`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        bucket_start:
            Media-time start of each summary bucket, in nanoseconds.
        bucket_duration_samples:
            Duration of each summary bucket, in samples per channel.
        min_amplitude:
            Minimum normalized amplitude in each bucket.
        max_amplitude:
            Maximum normalized amplitude in each bucket.
        rms_amplitude:
            Optional RMS or loudness-like summary for each bucket.
        activity:
            Optional activity/silence score for each bucket. Convention: 0 is silent, 1 is active.
        source_id:
            Stable identity of the audio source this summary was derived from.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "bucket_start": bucket_start,
                "bucket_duration_samples": bucket_duration_samples,
                "min_amplitude": min_amplitude,
                "max_amplitude": max_amplitude,
                "rms_amplitude": rms_amplitude,
                "activity": activity,
                "source_id": source_id,
                "audio_reference": audio_reference,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> AudioWaveformSummary:
        """Clear all the fields of a `AudioWaveformSummary`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_bucket_start() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:bucket_start",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.AudioTimestampBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_bucket_duration_samples() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:bucket_duration_samples",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.AudioDurationSamplesBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_min_amplitude() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:min_amplitude",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.ScalarBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_max_amplitude() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:max_amplitude",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.ScalarBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_rms_amplitude() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:rms_amplitude",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.ScalarBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_activity() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:activity",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.ScalarBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_source_id() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:source_id",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.AudioSourceIdBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_audio_reference() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioWaveformSummary:audio_reference",
            archetype=AudioWaveformSummary.NAME,
            component_type=components.EntityPathBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        bucket_start: datatypes.AudioTimestampArrayLike | None = None,
        bucket_duration_samples: datatypes.UInt64ArrayLike | None = None,
        min_amplitude: datatypes.Float64ArrayLike | None = None,
        max_amplitude: datatypes.Float64ArrayLike | None = None,
        rms_amplitude: datatypes.Float64ArrayLike | None = None,
        activity: datatypes.Float64ArrayLike | None = None,
        source_id: datatypes.Utf8ArrayLike | None = None,
        audio_reference: datatypes.EntityPathArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        bucket_start:
            Media-time start of each summary bucket, in nanoseconds.
        bucket_duration_samples:
            Duration of each summary bucket, in samples per channel.
        min_amplitude:
            Minimum normalized amplitude in each bucket.
        max_amplitude:
            Maximum normalized amplitude in each bucket.
        rms_amplitude:
            Optional RMS or loudness-like summary for each bucket.
        activity:
            Optional activity/silence score for each bucket. Convention: 0 is silent, 1 is active.
        source_id:
            Stable identity of the audio source this summary was derived from.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                bucket_start=bucket_start,
                bucket_duration_samples=bucket_duration_samples,
                min_amplitude=min_amplitude,
                max_amplitude=max_amplitude,
                rms_amplitude=rms_amplitude,
                activity=activity,
                source_id=source_id,
                audio_reference=audio_reference,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "AudioWaveformSummary:bucket_start": bucket_start,
            "AudioWaveformSummary:bucket_duration_samples": bucket_duration_samples,
            "AudioWaveformSummary:min_amplitude": min_amplitude,
            "AudioWaveformSummary:max_amplitude": max_amplitude,
            "AudioWaveformSummary:rms_amplitude": rms_amplitude,
            "AudioWaveformSummary:activity": activity,
            "AudioWaveformSummary:source_id": source_id,
            "AudioWaveformSummary:audio_reference": audio_reference,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    bucket_start: components.AudioTimestampBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioTimestampBatch._converter,  # type: ignore[misc]
    )
    # Media-time start of each summary bucket, in nanoseconds.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    bucket_duration_samples: components.AudioDurationSamplesBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioDurationSamplesBatch._converter,  # type: ignore[misc]
    )
    # Duration of each summary bucket, in samples per channel.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    min_amplitude: components.ScalarBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ScalarBatch._converter,  # type: ignore[misc]
    )
    # Minimum normalized amplitude in each bucket.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    max_amplitude: components.ScalarBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ScalarBatch._converter,  # type: ignore[misc]
    )
    # Maximum normalized amplitude in each bucket.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    rms_amplitude: components.ScalarBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ScalarBatch._converter,  # type: ignore[misc]
    )
    # Optional RMS or loudness-like summary for each bucket.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    activity: components.ScalarBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ScalarBatch._converter,  # type: ignore[misc]
    )
    # Optional activity/silence score for each bucket. Convention: 0 is silent, 1 is active.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    source_id: components.AudioSourceIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioSourceIdBatch._converter,  # type: ignore[misc]
    )
    # Stable identity of the audio source this summary was derived from.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    audio_reference: components.EntityPathBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.EntityPathBatch._converter,  # type: ignore[misc]
    )
    # Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("AudioWaveformSummary", overrides=self.as_component_batches(), mappings=mappings)
