# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_seek_index.fbs".

# You can extend this class by creating a "AudioSeekIndexExt" class in "audio_seek_index_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["AudioSeekIndex"]


@define(str=False, repr=False, init=False)
class AudioSeekIndex(Archetype, VisualizableArchetype):
    """
    **Archetype**: Materialized seek index for an audio source.

    Each row stores one batch of entries. The `media_time`, `decode_time`, and
    `trim_samples` arrays are parallel arrays. A playback runtime resolves a
    requested media time by choosing the nearest preceding `decode_time`,
    decoding forward, then trimming `trim_samples` samples from the decoded PCM.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.AudioSeekIndex"

    def __init__(
        self: Any,
        *,
        media_time: datatypes.AudioTimestampArrayLike,
        decode_time: datatypes.AudioTimestampArrayLike,
        trim_samples: datatypes.UInt64ArrayLike,
        sequence_number: datatypes.UInt64ArrayLike | None = None,
        discontinuity: datatypes.BoolArrayLike | None = None,
        source_id: datatypes.Utf8Like | None = None,
        audio_reference: datatypes.EntityPathLike | None = None,
        stream_id: datatypes.UInt64Like | None = None,
    ) -> None:
        """
        Create a new instance of the AudioSeekIndex archetype.

        Parameters
        ----------
        media_time:
            Media time that this index entry accelerates.
        decode_time:
            Nearest preceding decoder reset / key / seekable boundary.
        trim_samples:
            Number of samples per channel to discard after decoding from `decode_time`.
        sequence_number:
            Sequence number of the segment containing `decode_time`, if known.
        discontinuity:
            Whether the entry crosses or starts at a discontinuity.
        source_id:
            Stable identity of the audio source this index was derived from.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
        stream_id:
            Continuity stream id associated with this index batch.

        """

        # You can define your own __init__ function as a member of AudioSeekIndexExt in audio_seek_index_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                media_time=media_time,
                decode_time=decode_time,
                trim_samples=trim_samples,
                sequence_number=sequence_number,
                discontinuity=discontinuity,
                source_id=source_id,
                audio_reference=audio_reference,
                stream_id=stream_id,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            media_time=None,
            decode_time=None,
            trim_samples=None,
            sequence_number=None,
            discontinuity=None,
            source_id=None,
            audio_reference=None,
            stream_id=None,
        )

    @classmethod
    def _clear(cls) -> AudioSeekIndex:
        """Produce an empty AudioSeekIndex, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        media_time: datatypes.AudioTimestampArrayLike | None = None,
        decode_time: datatypes.AudioTimestampArrayLike | None = None,
        trim_samples: datatypes.UInt64ArrayLike | None = None,
        sequence_number: datatypes.UInt64ArrayLike | None = None,
        discontinuity: datatypes.BoolArrayLike | None = None,
        source_id: datatypes.Utf8Like | None = None,
        audio_reference: datatypes.EntityPathLike | None = None,
        stream_id: datatypes.UInt64Like | None = None,
    ) -> AudioSeekIndex:
        """
        Update only some specific fields of a `AudioSeekIndex`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        media_time:
            Media time that this index entry accelerates.
        decode_time:
            Nearest preceding decoder reset / key / seekable boundary.
        trim_samples:
            Number of samples per channel to discard after decoding from `decode_time`.
        sequence_number:
            Sequence number of the segment containing `decode_time`, if known.
        discontinuity:
            Whether the entry crosses or starts at a discontinuity.
        source_id:
            Stable identity of the audio source this index was derived from.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
        stream_id:
            Continuity stream id associated with this index batch.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "media_time": media_time,
                "decode_time": decode_time,
                "trim_samples": trim_samples,
                "sequence_number": sequence_number,
                "discontinuity": discontinuity,
                "source_id": source_id,
                "audio_reference": audio_reference,
                "stream_id": stream_id,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> AudioSeekIndex:
        """Clear all the fields of a `AudioSeekIndex`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_media_time() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:media_time",
            archetype=AudioSeekIndex.NAME,
            component_type=components.AudioTimestampBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_decode_time() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:decode_time",
            archetype=AudioSeekIndex.NAME,
            component_type=components.AudioTimestampBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_trim_samples() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:trim_samples",
            archetype=AudioSeekIndex.NAME,
            component_type=components.AudioDurationSamplesBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_sequence_number() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:sequence_number",
            archetype=AudioSeekIndex.NAME,
            component_type=components.AudioSequenceNumberBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_discontinuity() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:discontinuity",
            archetype=AudioSeekIndex.NAME,
            component_type=components.AudioDiscontinuityBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_source_id() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:source_id",
            archetype=AudioSeekIndex.NAME,
            component_type=components.AudioSourceIdBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_audio_reference() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:audio_reference",
            archetype=AudioSeekIndex.NAME,
            component_type=components.EntityPathBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_stream_id() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioSeekIndex:stream_id",
            archetype=AudioSeekIndex.NAME,
            component_type=components.AudioStreamIdBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        media_time: datatypes.AudioTimestampArrayLike | None = None,
        decode_time: datatypes.AudioTimestampArrayLike | None = None,
        trim_samples: datatypes.UInt64ArrayLike | None = None,
        sequence_number: datatypes.UInt64ArrayLike | None = None,
        discontinuity: datatypes.BoolArrayLike | None = None,
        source_id: datatypes.Utf8ArrayLike | None = None,
        audio_reference: datatypes.EntityPathArrayLike | None = None,
        stream_id: datatypes.UInt64ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        media_time:
            Media time that this index entry accelerates.
        decode_time:
            Nearest preceding decoder reset / key / seekable boundary.
        trim_samples:
            Number of samples per channel to discard after decoding from `decode_time`.
        sequence_number:
            Sequence number of the segment containing `decode_time`, if known.
        discontinuity:
            Whether the entry crosses or starts at a discontinuity.
        source_id:
            Stable identity of the audio source this index was derived from.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
        stream_id:
            Continuity stream id associated with this index batch.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                media_time=media_time,
                decode_time=decode_time,
                trim_samples=trim_samples,
                sequence_number=sequence_number,
                discontinuity=discontinuity,
                source_id=source_id,
                audio_reference=audio_reference,
                stream_id=stream_id,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "AudioSeekIndex:media_time": media_time,
            "AudioSeekIndex:decode_time": decode_time,
            "AudioSeekIndex:trim_samples": trim_samples,
            "AudioSeekIndex:sequence_number": sequence_number,
            "AudioSeekIndex:discontinuity": discontinuity,
            "AudioSeekIndex:source_id": source_id,
            "AudioSeekIndex:audio_reference": audio_reference,
            "AudioSeekIndex:stream_id": stream_id,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    media_time: components.AudioTimestampBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioTimestampBatch._converter,  # type: ignore[misc]
    )
    # Media time that this index entry accelerates.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    decode_time: components.AudioTimestampBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioTimestampBatch._converter,  # type: ignore[misc]
    )
    # Nearest preceding decoder reset / key / seekable boundary.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    trim_samples: components.AudioDurationSamplesBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioDurationSamplesBatch._converter,  # type: ignore[misc]
    )
    # Number of samples per channel to discard after decoding from `decode_time`.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sequence_number: components.AudioSequenceNumberBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioSequenceNumberBatch._converter,  # type: ignore[misc]
    )
    # Sequence number of the segment containing `decode_time`, if known.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    discontinuity: components.AudioDiscontinuityBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioDiscontinuityBatch._converter,  # type: ignore[misc]
    )
    # Whether the entry crosses or starts at a discontinuity.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    source_id: components.AudioSourceIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioSourceIdBatch._converter,  # type: ignore[misc]
    )
    # Stable identity of the audio source this index was derived from.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    audio_reference: components.EntityPathBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.EntityPathBatch._converter,  # type: ignore[misc]
    )
    # Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    stream_id: components.AudioStreamIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioStreamIdBatch._converter,  # type: ignore[misc]
    )
    # Continuity stream id associated with this index batch.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("AudioSeekIndex", overrides=self.as_component_batches(), mappings=mappings)
