# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_event.fbs".

# You can extend this class by creating a "AudioEventExt" class in "audio_event_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["AudioEvent"]


@define(str=False, repr=False, init=False)
class AudioEvent(Archetype, VisualizableArchetype):
    """
    **Archetype**: Audio-aligned point events.

    Use for decoder resets, ASR finalization, diarization switches, endpoint
    commits, barge-in detection, agent state transitions, and latency markers.

    Each row stores one or more events using parallel arrays. The row timestamp
    can still carry the event on a Rerun timeline; `event_time` records the
    source media time so events remain useful for complete audio assets and
    exported clips.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.AudioEvent"

    def __init__(
        self: Any,
        event_time: datatypes.AudioTimestampArrayLike,
        kind: components.AudioEventKindArrayLike,
        *,
        labels: datatypes.Utf8ArrayLike | None = None,
        source_id: datatypes.Utf8Like | None = None,
        audio_reference: datatypes.EntityPathLike | None = None,
        related: datatypes.EntityPathArrayLike | None = None,
        payload: components.KeyValuePairsLike | None = None,
        colors: datatypes.Rgba32ArrayLike | None = None,
    ) -> None:
        """
        Create a new instance of the AudioEvent archetype.

        Parameters
        ----------
        event_time:
            Media-time timestamp of each event, in nanoseconds.
        kind:
            Semantic class of each event.
        labels:
            Human-readable event label.
        source_id:
            Stable identity of the audio source these events refer to.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
        related:
            Optional related entities, such as the span or model response that emitted the event.
        payload:
            Additional event metadata shared by this row.
        colors:
            Optional display color per event.

        """

        # You can define your own __init__ function as a member of AudioEventExt in audio_event_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                event_time=event_time,
                kind=kind,
                labels=labels,
                source_id=source_id,
                audio_reference=audio_reference,
                related=related,
                payload=payload,
                colors=colors,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            event_time=None,
            kind=None,
            labels=None,
            source_id=None,
            audio_reference=None,
            related=None,
            payload=None,
            colors=None,
        )

    @classmethod
    def _clear(cls) -> AudioEvent:
        """Produce an empty AudioEvent, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        event_time: datatypes.AudioTimestampArrayLike | None = None,
        kind: components.AudioEventKindArrayLike | None = None,
        labels: datatypes.Utf8ArrayLike | None = None,
        source_id: datatypes.Utf8Like | None = None,
        audio_reference: datatypes.EntityPathLike | None = None,
        related: datatypes.EntityPathArrayLike | None = None,
        payload: components.KeyValuePairsLike | None = None,
        colors: datatypes.Rgba32ArrayLike | None = None,
    ) -> AudioEvent:
        """
        Update only some specific fields of a `AudioEvent`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        event_time:
            Media-time timestamp of each event, in nanoseconds.
        kind:
            Semantic class of each event.
        labels:
            Human-readable event label.
        source_id:
            Stable identity of the audio source these events refer to.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
        related:
            Optional related entities, such as the span or model response that emitted the event.
        payload:
            Additional event metadata shared by this row.
        colors:
            Optional display color per event.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "event_time": event_time,
                "kind": kind,
                "labels": labels,
                "source_id": source_id,
                "audio_reference": audio_reference,
                "related": related,
                "payload": payload,
                "colors": colors,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> AudioEvent:
        """Clear all the fields of a `AudioEvent`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_event_time() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:event_time",
            archetype=AudioEvent.NAME,
            component_type=components.AudioTimestampBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_kind() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:kind",
            archetype=AudioEvent.NAME,
            component_type=components.AudioEventKindBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_labels() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:labels",
            archetype=AudioEvent.NAME,
            component_type=components.TextBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_source_id() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:source_id",
            archetype=AudioEvent.NAME,
            component_type=components.AudioSourceIdBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_audio_reference() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:audio_reference",
            archetype=AudioEvent.NAME,
            component_type=components.EntityPathBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_related() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:related",
            archetype=AudioEvent.NAME,
            component_type=components.EntityPathBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_payload() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:payload",
            archetype=AudioEvent.NAME,
            component_type=components.KeyValuePairsBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_colors() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioEvent:colors",
            archetype=AudioEvent.NAME,
            component_type=components.ColorBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        event_time: datatypes.AudioTimestampArrayLike | None = None,
        kind: components.AudioEventKindArrayLike | None = None,
        labels: datatypes.Utf8ArrayLike | None = None,
        source_id: datatypes.Utf8ArrayLike | None = None,
        audio_reference: datatypes.EntityPathArrayLike | None = None,
        related: datatypes.EntityPathArrayLike | None = None,
        payload: components.KeyValuePairsArrayLike | None = None,
        colors: datatypes.Rgba32ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        event_time:
            Media-time timestamp of each event, in nanoseconds.
        kind:
            Semantic class of each event.
        labels:
            Human-readable event label.
        source_id:
            Stable identity of the audio source these events refer to.
        audio_reference:
            Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
        related:
            Optional related entities, such as the span or model response that emitted the event.
        payload:
            Additional event metadata shared by this row.
        colors:
            Optional display color per event.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                event_time=event_time,
                kind=kind,
                labels=labels,
                source_id=source_id,
                audio_reference=audio_reference,
                related=related,
                payload=payload,
                colors=colors,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "AudioEvent:event_time": event_time,
            "AudioEvent:kind": kind,
            "AudioEvent:labels": labels,
            "AudioEvent:source_id": source_id,
            "AudioEvent:audio_reference": audio_reference,
            "AudioEvent:related": related,
            "AudioEvent:payload": payload,
            "AudioEvent:colors": colors,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    event_time: components.AudioTimestampBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioTimestampBatch._converter,  # type: ignore[misc]
    )
    # Media-time timestamp of each event, in nanoseconds.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    kind: components.AudioEventKindBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioEventKindBatch._converter,  # type: ignore[misc]
    )
    # Semantic class of each event.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    labels: components.TextBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TextBatch._converter,  # type: ignore[misc]
    )
    # Human-readable event label.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    source_id: components.AudioSourceIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.AudioSourceIdBatch._converter,  # type: ignore[misc]
    )
    # Stable identity of the audio source these events refer to.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    audio_reference: components.EntityPathBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.EntityPathBatch._converter,  # type: ignore[misc]
    )
    # Entity carrying the source [`archetypes.AudioStream`][rerun.archetypes.AudioStream] or [`archetypes.AssetAudio`][rerun.archetypes.AssetAudio].
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    related: components.EntityPathBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.EntityPathBatch._converter,  # type: ignore[misc]
    )
    # Optional related entities, such as the span or model response that emitted the event.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    payload: components.KeyValuePairsBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.KeyValuePairsBatch._converter,  # type: ignore[misc]
    )
    # Additional event metadata shared by this row.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    colors: components.ColorBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ColorBatch._converter,  # type: ignore[misc]
    )
    # Optional display color per event.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("AudioEvent", overrides=self.as_component_batches(), mappings=mappings)
