// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A complete audio asset.
///
/// Represents a self-describing audio container (Ogg, FLAC, MP4/M4A, …) or
/// a raw encoded blob accompanied by explicit codec and rate metadata.
///
/// Supported container media types initially:
/// * `audio/ogg` — Opus in Ogg, fully playable.
/// * `audio/flac` — lossless, fully playable.
///
/// To place the asset on a timeline, log a companion
/// [`archetypes::AudioSampleReference`][crate::archetypes::AudioSampleReference] on the same (or a referencing) entity
/// at each playhead position you want the asset aligned to.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default)]
pub struct AssetAudio {
    /// The raw bytes of the audio asset.
    pub blob: Option<SerializedComponentBatch>,

    /// The IANA media type of the asset.
    ///
    /// If omitted, the viewer will try to sniff from the first bytes of the blob.
    /// If sniffing fails the asset is stored but playback is disabled.
    pub media_type: Option<SerializedComponentBatch>,

    /// Audio codec of the enclosed samples.
    ///
    /// When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
    /// this is redundant; logging it makes analysis queries cheaper.
    pub codec: Option<SerializedComponentBatch>,

    /// Decoded sample rate in Hz.
    pub sample_rate: Option<SerializedComponentBatch>,

    /// Decoded channel count.
    pub channel_count: Option<SerializedComponentBatch>,

    /// Speaker arrangement for the channels.
    pub channel_layout: Option<SerializedComponentBatch>,
}

impl AssetAudio {
    /// Returns the [`ComponentDescriptor`] for [`Self::blob`].
    ///
    /// The corresponding component is [`crate::components::Blob`].
    #[inline]
    pub fn descriptor_blob() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:blob".into(),
            component_type: Some("rerun.components.Blob".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::media_type`].
    ///
    /// The corresponding component is [`crate::components::MediaType`].
    #[inline]
    pub fn descriptor_media_type() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:media_type".into(),
            component_type: Some("rerun.components.MediaType".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::codec`].
    ///
    /// The corresponding component is [`crate::components::AudioCodec`].
    #[inline]
    pub fn descriptor_codec() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:codec".into(),
            component_type: Some("rerun.components.AudioCodec".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::sample_rate`].
    ///
    /// The corresponding component is [`crate::components::AudioSampleRate`].
    #[inline]
    pub fn descriptor_sample_rate() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:sample_rate".into(),
            component_type: Some("rerun.components.AudioSampleRate".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::channel_count`].
    ///
    /// The corresponding component is [`crate::components::AudioChannelCount`].
    #[inline]
    pub fn descriptor_channel_count() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:channel_count".into(),
            component_type: Some("rerun.components.AudioChannelCount".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::channel_layout`].
    ///
    /// The corresponding component is [`crate::components::AudioChannelLayout`].
    #[inline]
    pub fn descriptor_channel_layout() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:channel_layout".into(),
            component_type: Some("rerun.components.AudioChannelLayout".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AssetAudio::descriptor_blob()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AssetAudio::descriptor_media_type()]);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 4usize]> =
    std::sync::LazyLock::new(|| {
        [
            AssetAudio::descriptor_codec(),
            AssetAudio::descriptor_sample_rate(),
            AssetAudio::descriptor_channel_count(),
            AssetAudio::descriptor_channel_layout(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 6usize]> =
    std::sync::LazyLock::new(|| {
        [
            AssetAudio::descriptor_blob(),
            AssetAudio::descriptor_media_type(),
            AssetAudio::descriptor_codec(),
            AssetAudio::descriptor_sample_rate(),
            AssetAudio::descriptor_channel_count(),
            AssetAudio::descriptor_channel_layout(),
        ]
    });

impl AssetAudio {
    /// The total number of components in the archetype: 1 required, 1 recommended, 4 optional
    pub const NUM_COMPONENTS: usize = 6usize;
}

impl ::re_types_core::Archetype for AssetAudio {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AssetAudio".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Asset audio"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let blob = arrays_by_descr
            .get(&Self::descriptor_blob())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_blob()));
        let media_type = arrays_by_descr
            .get(&Self::descriptor_media_type())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_media_type())
            });
        let codec = arrays_by_descr
            .get(&Self::descriptor_codec())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_codec()));
        let sample_rate = arrays_by_descr
            .get(&Self::descriptor_sample_rate())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_sample_rate())
            });
        let channel_count = arrays_by_descr
            .get(&Self::descriptor_channel_count())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_channel_count())
            });
        let channel_layout = arrays_by_descr
            .get(&Self::descriptor_channel_layout())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_channel_layout())
            });
        Ok(Self {
            blob,
            media_type,
            codec,
            sample_rate,
            channel_count,
            channel_layout,
        })
    }
}

impl ::re_types_core::AsComponents for AssetAudio {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.blob.clone(),
            self.media_type.clone(),
            self.codec.clone(),
            self.sample_rate.clone(),
            self.channel_count.clone(),
            self.channel_layout.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AssetAudio {}

impl AssetAudio {
    /// Create a new `AssetAudio`.
    #[inline]
    pub fn new(blob: impl Into<crate::components::Blob>) -> Self {
        Self {
            blob: try_serialize_field(Self::descriptor_blob(), [blob]),
            media_type: None,
            codec: None,
            sample_rate: None,
            channel_count: None,
            channel_layout: None,
        }
    }

    /// Update only some specific fields of a `AssetAudio`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AssetAudio`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            blob: Some(SerializedComponentBatch::new(
                crate::components::Blob::arrow_empty(),
                Self::descriptor_blob(),
            )),
            media_type: Some(SerializedComponentBatch::new(
                crate::components::MediaType::arrow_empty(),
                Self::descriptor_media_type(),
            )),
            codec: Some(SerializedComponentBatch::new(
                crate::components::AudioCodec::arrow_empty(),
                Self::descriptor_codec(),
            )),
            sample_rate: Some(SerializedComponentBatch::new(
                crate::components::AudioSampleRate::arrow_empty(),
                Self::descriptor_sample_rate(),
            )),
            channel_count: Some(SerializedComponentBatch::new(
                crate::components::AudioChannelCount::arrow_empty(),
                Self::descriptor_channel_count(),
            )),
            channel_layout: Some(SerializedComponentBatch::new(
                crate::components::AudioChannelLayout::arrow_empty(),
                Self::descriptor_channel_layout(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.blob
                .map(|blob| blob.partitioned(_lengths.clone()))
                .transpose()?,
            self.media_type
                .map(|media_type| media_type.partitioned(_lengths.clone()))
                .transpose()?,
            self.codec
                .map(|codec| codec.partitioned(_lengths.clone()))
                .transpose()?,
            self.sample_rate
                .map(|sample_rate| sample_rate.partitioned(_lengths.clone()))
                .transpose()?,
            self.channel_count
                .map(|channel_count| channel_count.partitioned(_lengths.clone()))
                .transpose()?,
            self.channel_layout
                .map(|channel_layout| channel_layout.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_blob = self.blob.as_ref().map(|b| b.array.len());
        let len_media_type = self.media_type.as_ref().map(|b| b.array.len());
        let len_codec = self.codec.as_ref().map(|b| b.array.len());
        let len_sample_rate = self.sample_rate.as_ref().map(|b| b.array.len());
        let len_channel_count = self.channel_count.as_ref().map(|b| b.array.len());
        let len_channel_layout = self.channel_layout.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_blob)
            .or(len_media_type)
            .or(len_codec)
            .or(len_sample_rate)
            .or(len_channel_count)
            .or(len_channel_layout)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The raw bytes of the audio asset.
    #[inline]
    pub fn with_blob(mut self, blob: impl Into<crate::components::Blob>) -> Self {
        self.blob = try_serialize_field(Self::descriptor_blob(), [blob]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Blob`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_blob`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_blob(
        mut self,
        blob: impl IntoIterator<Item = impl Into<crate::components::Blob>>,
    ) -> Self {
        self.blob = try_serialize_field(Self::descriptor_blob(), blob);
        self
    }

    /// The IANA media type of the asset.
    ///
    /// If omitted, the viewer will try to sniff from the first bytes of the blob.
    /// If sniffing fails the asset is stored but playback is disabled.
    #[inline]
    pub fn with_media_type(mut self, media_type: impl Into<crate::components::MediaType>) -> Self {
        self.media_type = try_serialize_field(Self::descriptor_media_type(), [media_type]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::MediaType`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_media_type`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_media_type(
        mut self,
        media_type: impl IntoIterator<Item = impl Into<crate::components::MediaType>>,
    ) -> Self {
        self.media_type = try_serialize_field(Self::descriptor_media_type(), media_type);
        self
    }

    /// Audio codec of the enclosed samples.
    ///
    /// When the asset is a self-describing container (`audio/ogg`, `audio/flac`, …)
    /// this is redundant; logging it makes analysis queries cheaper.
    #[inline]
    pub fn with_codec(mut self, codec: impl Into<crate::components::AudioCodec>) -> Self {
        self.codec = try_serialize_field(Self::descriptor_codec(), [codec]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioCodec`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_codec`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_codec(
        mut self,
        codec: impl IntoIterator<Item = impl Into<crate::components::AudioCodec>>,
    ) -> Self {
        self.codec = try_serialize_field(Self::descriptor_codec(), codec);
        self
    }

    /// Decoded sample rate in Hz.
    #[inline]
    pub fn with_sample_rate(
        mut self,
        sample_rate: impl Into<crate::components::AudioSampleRate>,
    ) -> Self {
        self.sample_rate = try_serialize_field(Self::descriptor_sample_rate(), [sample_rate]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioSampleRate`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_sample_rate`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_sample_rate(
        mut self,
        sample_rate: impl IntoIterator<Item = impl Into<crate::components::AudioSampleRate>>,
    ) -> Self {
        self.sample_rate = try_serialize_field(Self::descriptor_sample_rate(), sample_rate);
        self
    }

    /// Decoded channel count.
    #[inline]
    pub fn with_channel_count(
        mut self,
        channel_count: impl Into<crate::components::AudioChannelCount>,
    ) -> Self {
        self.channel_count = try_serialize_field(Self::descriptor_channel_count(), [channel_count]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioChannelCount`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_channel_count`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_channel_count(
        mut self,
        channel_count: impl IntoIterator<Item = impl Into<crate::components::AudioChannelCount>>,
    ) -> Self {
        self.channel_count = try_serialize_field(Self::descriptor_channel_count(), channel_count);
        self
    }

    /// Speaker arrangement for the channels.
    #[inline]
    pub fn with_channel_layout(
        mut self,
        channel_layout: impl Into<crate::components::AudioChannelLayout>,
    ) -> Self {
        self.channel_layout =
            try_serialize_field(Self::descriptor_channel_layout(), [channel_layout]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioChannelLayout`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_channel_layout`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_channel_layout(
        mut self,
        channel_layout: impl IntoIterator<Item = impl Into<crate::components::AudioChannelLayout>>,
    ) -> Self {
        self.channel_layout =
            try_serialize_field(Self::descriptor_channel_layout(), channel_layout);
        self
    }
}

impl ::re_byte_size::SizeBytes for AssetAudio {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.blob.heap_size_bytes()
            + self.media_type.heap_size_bytes()
            + self.codec.heap_size_bytes()
            + self.sample_rate.heap_size_bytes()
            + self.channel_count.heap_size_bytes()
            + self.channel_layout.heap_size_bytes()
    }
}
