// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_sample_reference.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: References a single position inside an [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
///
/// Used to bind the media time of a complete audio asset to a Rerun timeline.
/// Log one [`archetypes::AudioSampleReference`][crate::archetypes::AudioSampleReference] at each timeline position where
/// the asset should be "at" the given media timestamp; between references
/// the viewer interpolates linearly in media-time.
///
/// To play an entire asset aligned to a timeline, log a reference at the
/// start of the asset and another at the end — or, equivalently, log a
/// reference per visible frame for sub-frame alignment.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default)]
pub struct AudioSampleReference {
    /// The media-time position inside the referenced audio asset.
    ///
    /// Timestamps are nanoseconds relative to the start of the asset.
    pub timestamp: Option<SerializedComponentBatch>,

    /// Optional reference to the entity that carries the [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    ///
    /// If omitted, the asset is assumed to be on the same entity.
    /// Blueprint overrides on the referenced asset are ignored — this is
    /// always resolved against the data store.
    pub audio_reference: Option<SerializedComponentBatch>,
}

impl AudioSampleReference {
    /// Returns the [`ComponentDescriptor`] for [`Self::timestamp`].
    ///
    /// The corresponding component is [`crate::components::AudioTimestamp`].
    #[inline]
    pub fn descriptor_timestamp() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSampleReference".into()),
            component: "AudioSampleReference:timestamp".into(),
            component_type: Some("rerun.components.AudioTimestamp".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::audio_reference`].
    ///
    /// The corresponding component is [`crate::components::EntityPath`].
    #[inline]
    pub fn descriptor_audio_reference() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSampleReference".into()),
            component: "AudioSampleReference:audio_reference".into(),
            component_type: Some("rerun.components.EntityPath".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AudioSampleReference::descriptor_timestamp()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AudioSampleReference::descriptor_audio_reference()]);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioSampleReference::descriptor_timestamp(),
            AudioSampleReference::descriptor_audio_reference(),
        ]
    });

impl AudioSampleReference {
    /// The total number of components in the archetype: 1 required, 0 recommended, 1 optional
    pub const NUM_COMPONENTS: usize = 2usize;
}

impl ::re_types_core::Archetype for AudioSampleReference {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AudioSampleReference".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Audio sample reference"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let timestamp = arrays_by_descr
            .get(&Self::descriptor_timestamp())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_timestamp())
            });
        let audio_reference = arrays_by_descr
            .get(&Self::descriptor_audio_reference())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_audio_reference())
            });
        Ok(Self {
            timestamp,
            audio_reference,
        })
    }
}

impl ::re_types_core::AsComponents for AudioSampleReference {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [self.timestamp.clone(), self.audio_reference.clone()]
            .into_iter()
            .flatten()
            .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AudioSampleReference {}

impl crate::VisualizableArchetype for AudioSampleReference {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("AudioSampleReference").with_overrides(self)
    }
}

impl AudioSampleReference {
    /// Create a new `AudioSampleReference`.
    #[inline]
    pub fn new(timestamp: impl Into<crate::components::AudioTimestamp>) -> Self {
        Self {
            timestamp: try_serialize_field(Self::descriptor_timestamp(), [timestamp]),
            audio_reference: None,
        }
    }

    /// Update only some specific fields of a `AudioSampleReference`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AudioSampleReference`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            timestamp: Some(SerializedComponentBatch::new(
                crate::components::AudioTimestamp::arrow_empty(),
                Self::descriptor_timestamp(),
            )),
            audio_reference: Some(SerializedComponentBatch::new(
                crate::components::EntityPath::arrow_empty(),
                Self::descriptor_audio_reference(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.timestamp
                .map(|timestamp| timestamp.partitioned(_lengths.clone()))
                .transpose()?,
            self.audio_reference
                .map(|audio_reference| audio_reference.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_timestamp = self.timestamp.as_ref().map(|b| b.array.len());
        let len_audio_reference = self.audio_reference.as_ref().map(|b| b.array.len());
        let len = None.or(len_timestamp).or(len_audio_reference).unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The media-time position inside the referenced audio asset.
    ///
    /// Timestamps are nanoseconds relative to the start of the asset.
    #[inline]
    pub fn with_timestamp(
        mut self,
        timestamp: impl Into<crate::components::AudioTimestamp>,
    ) -> Self {
        self.timestamp = try_serialize_field(Self::descriptor_timestamp(), [timestamp]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioTimestamp`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_timestamp`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_timestamp(
        mut self,
        timestamp: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
    ) -> Self {
        self.timestamp = try_serialize_field(Self::descriptor_timestamp(), timestamp);
        self
    }

    /// Optional reference to the entity that carries the [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    ///
    /// If omitted, the asset is assumed to be on the same entity.
    /// Blueprint overrides on the referenced asset are ignored — this is
    /// always resolved against the data store.
    #[inline]
    pub fn with_audio_reference(
        mut self,
        audio_reference: impl Into<crate::components::EntityPath>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), [audio_reference]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::EntityPath`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_audio_reference`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_audio_reference(
        mut self,
        audio_reference: impl IntoIterator<Item = impl Into<crate::components::EntityPath>>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), audio_reference);
        self
    }
}

impl ::re_byte_size::SizeBytes for AudioSampleReference {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.timestamp.heap_size_bytes() + self.audio_reference.heap_size_bytes()
    }
}
