// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_stream.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A time-evolving stream of encoded audio chunks.
///
/// [`archetypes::AudioStream`][crate::archetypes::AudioStream] is the streaming counterpart of [`archetypes::AssetAudio`][crate::archetypes::AssetAudio]:
/// each logged row is a self-contained, decodable segment and the row's
/// timeline timestamp is treated as the presentation timestamp (PTS) of the
/// first PCM sample in the segment.
///
/// Static components (`codec`, `sample_rate`, `channel_count`, `channel_layout`,
/// `priming_delay`) are expected to be constant over the lifetime of the
/// stream and are typically logged once with `static=True`. The per-row
/// components (`chunk`, `duration_samples`, `stream_id`, `sequence_number`,
/// `discontinuity`, `seekable`) are logged with each segment.
///
/// Segments may arrive out of order in the log but the viewer resumes
/// playback from the nearest preceding seekable boundary on any seek.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default)]
pub struct AudioStream {
    /// The codec used to encode chunks.
    pub codec: Option<SerializedComponentBatch>,

    /// Sample rate reported by / requested of the decoder, in Hz.
    pub sample_rate: Option<SerializedComponentBatch>,

    /// Number of audio channels.
    pub channel_count: Option<SerializedComponentBatch>,

    /// One decodable segment of encoded audio.
    ///
    /// The current row timestamp is used as PTS for the first sample. There is
    /// no separate DTS — Opus has no decode-order reordering; codecs that need
    /// it may be added later with an additional component.
    pub chunk: Option<SerializedComponentBatch>,

    /// Number of PCM samples per channel produced by decoding this chunk.
    ///
    /// Logged per row so the viewer never has to decode the payload to know
    /// the span length. Enables fast gap detection and scrubbing.
    pub duration_samples: Option<SerializedComponentBatch>,

    /// Speaker arrangement for the channels.
    pub channel_layout: Option<SerializedComponentBatch>,

    /// Encoder pre-roll, in samples. Discarded by the decoder at stream start.
    pub priming_delay: Option<SerializedComponentBatch>,

    /// Stream continuity marker.
    ///
    /// A change in value signals a recorder restart and is treated as an
    /// implicit discontinuity.
    pub stream_id: Option<SerializedComponentBatch>,

    /// Monotonic per-stream sequence number. Gaps surface as a diagnostic.
    pub sequence_number: Option<SerializedComponentBatch>,

    /// If true, the decoder is reset before this chunk is processed.
    pub discontinuity: Option<SerializedComponentBatch>,

    /// If true, this chunk is an independent seek target.
    ///
    /// Defaults to `true` for Opus; codecs with inter-frame dependencies may
    /// set it false on non-key segments.
    pub seekable: Option<SerializedComponentBatch>,
}

impl AudioStream {
    /// Returns the [`ComponentDescriptor`] for [`Self::codec`].
    ///
    /// The corresponding component is [`crate::components::AudioCodec`].
    #[inline]
    pub fn descriptor_codec() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:codec".into(),
            component_type: Some("rerun.components.AudioCodec".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::sample_rate`].
    ///
    /// The corresponding component is [`crate::components::AudioSampleRate`].
    #[inline]
    pub fn descriptor_sample_rate() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:sample_rate".into(),
            component_type: Some("rerun.components.AudioSampleRate".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::channel_count`].
    ///
    /// The corresponding component is [`crate::components::AudioChannelCount`].
    #[inline]
    pub fn descriptor_channel_count() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:channel_count".into(),
            component_type: Some("rerun.components.AudioChannelCount".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::chunk`].
    ///
    /// The corresponding component is [`crate::components::AudioChunk`].
    #[inline]
    pub fn descriptor_chunk() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:chunk".into(),
            component_type: Some("rerun.components.AudioChunk".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::duration_samples`].
    ///
    /// The corresponding component is [`crate::components::AudioDurationSamples`].
    #[inline]
    pub fn descriptor_duration_samples() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:duration_samples".into(),
            component_type: Some("rerun.components.AudioDurationSamples".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::channel_layout`].
    ///
    /// The corresponding component is [`crate::components::AudioChannelLayout`].
    #[inline]
    pub fn descriptor_channel_layout() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:channel_layout".into(),
            component_type: Some("rerun.components.AudioChannelLayout".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::priming_delay`].
    ///
    /// The corresponding component is [`crate::components::AudioPrimingDelay`].
    #[inline]
    pub fn descriptor_priming_delay() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:priming_delay".into(),
            component_type: Some("rerun.components.AudioPrimingDelay".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::stream_id`].
    ///
    /// The corresponding component is [`crate::components::AudioStreamId`].
    #[inline]
    pub fn descriptor_stream_id() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:stream_id".into(),
            component_type: Some("rerun.components.AudioStreamId".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::sequence_number`].
    ///
    /// The corresponding component is [`crate::components::AudioSequenceNumber`].
    #[inline]
    pub fn descriptor_sequence_number() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:sequence_number".into(),
            component_type: Some("rerun.components.AudioSequenceNumber".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::discontinuity`].
    ///
    /// The corresponding component is [`crate::components::AudioDiscontinuity`].
    #[inline]
    pub fn descriptor_discontinuity() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:discontinuity".into(),
            component_type: Some("rerun.components.AudioDiscontinuity".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::seekable`].
    ///
    /// The corresponding component is [`crate::components::AudioSeekable`].
    #[inline]
    pub fn descriptor_seekable() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioStream".into()),
            component: "AudioStream:seekable".into(),
            component_type: Some("rerun.components.AudioSeekable".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioStream::descriptor_codec(),
            AudioStream::descriptor_sample_rate(),
            AudioStream::descriptor_channel_count(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioStream::descriptor_chunk(),
            AudioStream::descriptor_duration_samples(),
        ]
    });

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 6usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioStream::descriptor_channel_layout(),
            AudioStream::descriptor_priming_delay(),
            AudioStream::descriptor_stream_id(),
            AudioStream::descriptor_sequence_number(),
            AudioStream::descriptor_discontinuity(),
            AudioStream::descriptor_seekable(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 11usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioStream::descriptor_codec(),
            AudioStream::descriptor_sample_rate(),
            AudioStream::descriptor_channel_count(),
            AudioStream::descriptor_chunk(),
            AudioStream::descriptor_duration_samples(),
            AudioStream::descriptor_channel_layout(),
            AudioStream::descriptor_priming_delay(),
            AudioStream::descriptor_stream_id(),
            AudioStream::descriptor_sequence_number(),
            AudioStream::descriptor_discontinuity(),
            AudioStream::descriptor_seekable(),
        ]
    });

impl AudioStream {
    /// The total number of components in the archetype: 3 required, 2 recommended, 6 optional
    pub const NUM_COMPONENTS: usize = 11usize;
}

impl ::re_types_core::Archetype for AudioStream {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AudioStream".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Audio stream"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let codec = arrays_by_descr
            .get(&Self::descriptor_codec())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_codec()));
        let sample_rate = arrays_by_descr
            .get(&Self::descriptor_sample_rate())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_sample_rate())
            });
        let channel_count = arrays_by_descr
            .get(&Self::descriptor_channel_count())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_channel_count())
            });
        let chunk = arrays_by_descr
            .get(&Self::descriptor_chunk())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_chunk()));
        let duration_samples = arrays_by_descr
            .get(&Self::descriptor_duration_samples())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_duration_samples())
            });
        let channel_layout = arrays_by_descr
            .get(&Self::descriptor_channel_layout())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_channel_layout())
            });
        let priming_delay = arrays_by_descr
            .get(&Self::descriptor_priming_delay())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_priming_delay())
            });
        let stream_id = arrays_by_descr
            .get(&Self::descriptor_stream_id())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_stream_id())
            });
        let sequence_number = arrays_by_descr
            .get(&Self::descriptor_sequence_number())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_sequence_number())
            });
        let discontinuity = arrays_by_descr
            .get(&Self::descriptor_discontinuity())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_discontinuity())
            });
        let seekable = arrays_by_descr
            .get(&Self::descriptor_seekable())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_seekable()));
        Ok(Self {
            codec,
            sample_rate,
            channel_count,
            chunk,
            duration_samples,
            channel_layout,
            priming_delay,
            stream_id,
            sequence_number,
            discontinuity,
            seekable,
        })
    }
}

impl ::re_types_core::AsComponents for AudioStream {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.codec.clone(),
            self.sample_rate.clone(),
            self.channel_count.clone(),
            self.chunk.clone(),
            self.duration_samples.clone(),
            self.channel_layout.clone(),
            self.priming_delay.clone(),
            self.stream_id.clone(),
            self.sequence_number.clone(),
            self.discontinuity.clone(),
            self.seekable.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AudioStream {}

impl crate::VisualizableArchetype for AudioStream {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("AudioStream").with_overrides(self)
    }
}

impl AudioStream {
    /// Create a new `AudioStream`.
    #[inline]
    pub fn new(
        codec: impl Into<crate::components::AudioCodec>,
        sample_rate: impl Into<crate::components::AudioSampleRate>,
        channel_count: impl Into<crate::components::AudioChannelCount>,
    ) -> Self {
        Self {
            codec: try_serialize_field(Self::descriptor_codec(), [codec]),
            sample_rate: try_serialize_field(Self::descriptor_sample_rate(), [sample_rate]),
            channel_count: try_serialize_field(Self::descriptor_channel_count(), [channel_count]),
            chunk: None,
            duration_samples: None,
            channel_layout: None,
            priming_delay: None,
            stream_id: None,
            sequence_number: None,
            discontinuity: None,
            seekable: None,
        }
    }

    /// Update only some specific fields of a `AudioStream`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AudioStream`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            codec: Some(SerializedComponentBatch::new(
                crate::components::AudioCodec::arrow_empty(),
                Self::descriptor_codec(),
            )),
            sample_rate: Some(SerializedComponentBatch::new(
                crate::components::AudioSampleRate::arrow_empty(),
                Self::descriptor_sample_rate(),
            )),
            channel_count: Some(SerializedComponentBatch::new(
                crate::components::AudioChannelCount::arrow_empty(),
                Self::descriptor_channel_count(),
            )),
            chunk: Some(SerializedComponentBatch::new(
                crate::components::AudioChunk::arrow_empty(),
                Self::descriptor_chunk(),
            )),
            duration_samples: Some(SerializedComponentBatch::new(
                crate::components::AudioDurationSamples::arrow_empty(),
                Self::descriptor_duration_samples(),
            )),
            channel_layout: Some(SerializedComponentBatch::new(
                crate::components::AudioChannelLayout::arrow_empty(),
                Self::descriptor_channel_layout(),
            )),
            priming_delay: Some(SerializedComponentBatch::new(
                crate::components::AudioPrimingDelay::arrow_empty(),
                Self::descriptor_priming_delay(),
            )),
            stream_id: Some(SerializedComponentBatch::new(
                crate::components::AudioStreamId::arrow_empty(),
                Self::descriptor_stream_id(),
            )),
            sequence_number: Some(SerializedComponentBatch::new(
                crate::components::AudioSequenceNumber::arrow_empty(),
                Self::descriptor_sequence_number(),
            )),
            discontinuity: Some(SerializedComponentBatch::new(
                crate::components::AudioDiscontinuity::arrow_empty(),
                Self::descriptor_discontinuity(),
            )),
            seekable: Some(SerializedComponentBatch::new(
                crate::components::AudioSeekable::arrow_empty(),
                Self::descriptor_seekable(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.codec
                .map(|codec| codec.partitioned(_lengths.clone()))
                .transpose()?,
            self.sample_rate
                .map(|sample_rate| sample_rate.partitioned(_lengths.clone()))
                .transpose()?,
            self.channel_count
                .map(|channel_count| channel_count.partitioned(_lengths.clone()))
                .transpose()?,
            self.chunk
                .map(|chunk| chunk.partitioned(_lengths.clone()))
                .transpose()?,
            self.duration_samples
                .map(|duration_samples| duration_samples.partitioned(_lengths.clone()))
                .transpose()?,
            self.channel_layout
                .map(|channel_layout| channel_layout.partitioned(_lengths.clone()))
                .transpose()?,
            self.priming_delay
                .map(|priming_delay| priming_delay.partitioned(_lengths.clone()))
                .transpose()?,
            self.stream_id
                .map(|stream_id| stream_id.partitioned(_lengths.clone()))
                .transpose()?,
            self.sequence_number
                .map(|sequence_number| sequence_number.partitioned(_lengths.clone()))
                .transpose()?,
            self.discontinuity
                .map(|discontinuity| discontinuity.partitioned(_lengths.clone()))
                .transpose()?,
            self.seekable
                .map(|seekable| seekable.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_codec = self.codec.as_ref().map(|b| b.array.len());
        let len_sample_rate = self.sample_rate.as_ref().map(|b| b.array.len());
        let len_channel_count = self.channel_count.as_ref().map(|b| b.array.len());
        let len_chunk = self.chunk.as_ref().map(|b| b.array.len());
        let len_duration_samples = self.duration_samples.as_ref().map(|b| b.array.len());
        let len_channel_layout = self.channel_layout.as_ref().map(|b| b.array.len());
        let len_priming_delay = self.priming_delay.as_ref().map(|b| b.array.len());
        let len_stream_id = self.stream_id.as_ref().map(|b| b.array.len());
        let len_sequence_number = self.sequence_number.as_ref().map(|b| b.array.len());
        let len_discontinuity = self.discontinuity.as_ref().map(|b| b.array.len());
        let len_seekable = self.seekable.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_codec)
            .or(len_sample_rate)
            .or(len_channel_count)
            .or(len_chunk)
            .or(len_duration_samples)
            .or(len_channel_layout)
            .or(len_priming_delay)
            .or(len_stream_id)
            .or(len_sequence_number)
            .or(len_discontinuity)
            .or(len_seekable)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The codec used to encode chunks.
    #[inline]
    pub fn with_codec(mut self, codec: impl Into<crate::components::AudioCodec>) -> Self {
        self.codec = try_serialize_field(Self::descriptor_codec(), [codec]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioCodec`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_codec`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_codec(
        mut self,
        codec: impl IntoIterator<Item = impl Into<crate::components::AudioCodec>>,
    ) -> Self {
        self.codec = try_serialize_field(Self::descriptor_codec(), codec);
        self
    }

    /// Sample rate reported by / requested of the decoder, in Hz.
    #[inline]
    pub fn with_sample_rate(
        mut self,
        sample_rate: impl Into<crate::components::AudioSampleRate>,
    ) -> Self {
        self.sample_rate = try_serialize_field(Self::descriptor_sample_rate(), [sample_rate]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioSampleRate`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_sample_rate`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_sample_rate(
        mut self,
        sample_rate: impl IntoIterator<Item = impl Into<crate::components::AudioSampleRate>>,
    ) -> Self {
        self.sample_rate = try_serialize_field(Self::descriptor_sample_rate(), sample_rate);
        self
    }

    /// Number of audio channels.
    #[inline]
    pub fn with_channel_count(
        mut self,
        channel_count: impl Into<crate::components::AudioChannelCount>,
    ) -> Self {
        self.channel_count = try_serialize_field(Self::descriptor_channel_count(), [channel_count]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioChannelCount`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_channel_count`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_channel_count(
        mut self,
        channel_count: impl IntoIterator<Item = impl Into<crate::components::AudioChannelCount>>,
    ) -> Self {
        self.channel_count = try_serialize_field(Self::descriptor_channel_count(), channel_count);
        self
    }

    /// One decodable segment of encoded audio.
    ///
    /// The current row timestamp is used as PTS for the first sample. There is
    /// no separate DTS — Opus has no decode-order reordering; codecs that need
    /// it may be added later with an additional component.
    #[inline]
    pub fn with_chunk(mut self, chunk: impl Into<crate::components::AudioChunk>) -> Self {
        self.chunk = try_serialize_field(Self::descriptor_chunk(), [chunk]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioChunk`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_chunk`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_chunk(
        mut self,
        chunk: impl IntoIterator<Item = impl Into<crate::components::AudioChunk>>,
    ) -> Self {
        self.chunk = try_serialize_field(Self::descriptor_chunk(), chunk);
        self
    }

    /// Number of PCM samples per channel produced by decoding this chunk.
    ///
    /// Logged per row so the viewer never has to decode the payload to know
    /// the span length. Enables fast gap detection and scrubbing.
    #[inline]
    pub fn with_duration_samples(
        mut self,
        duration_samples: impl Into<crate::components::AudioDurationSamples>,
    ) -> Self {
        self.duration_samples =
            try_serialize_field(Self::descriptor_duration_samples(), [duration_samples]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioDurationSamples`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_duration_samples`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_duration_samples(
        mut self,
        duration_samples: impl IntoIterator<Item = impl Into<crate::components::AudioDurationSamples>>,
    ) -> Self {
        self.duration_samples =
            try_serialize_field(Self::descriptor_duration_samples(), duration_samples);
        self
    }

    /// Speaker arrangement for the channels.
    #[inline]
    pub fn with_channel_layout(
        mut self,
        channel_layout: impl Into<crate::components::AudioChannelLayout>,
    ) -> Self {
        self.channel_layout =
            try_serialize_field(Self::descriptor_channel_layout(), [channel_layout]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioChannelLayout`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_channel_layout`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_channel_layout(
        mut self,
        channel_layout: impl IntoIterator<Item = impl Into<crate::components::AudioChannelLayout>>,
    ) -> Self {
        self.channel_layout =
            try_serialize_field(Self::descriptor_channel_layout(), channel_layout);
        self
    }

    /// Encoder pre-roll, in samples. Discarded by the decoder at stream start.
    #[inline]
    pub fn with_priming_delay(
        mut self,
        priming_delay: impl Into<crate::components::AudioPrimingDelay>,
    ) -> Self {
        self.priming_delay = try_serialize_field(Self::descriptor_priming_delay(), [priming_delay]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioPrimingDelay`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_priming_delay`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_priming_delay(
        mut self,
        priming_delay: impl IntoIterator<Item = impl Into<crate::components::AudioPrimingDelay>>,
    ) -> Self {
        self.priming_delay = try_serialize_field(Self::descriptor_priming_delay(), priming_delay);
        self
    }

    /// Stream continuity marker.
    ///
    /// A change in value signals a recorder restart and is treated as an
    /// implicit discontinuity.
    #[inline]
    pub fn with_stream_id(
        mut self,
        stream_id: impl Into<crate::components::AudioStreamId>,
    ) -> Self {
        self.stream_id = try_serialize_field(Self::descriptor_stream_id(), [stream_id]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioStreamId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_stream_id`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_stream_id(
        mut self,
        stream_id: impl IntoIterator<Item = impl Into<crate::components::AudioStreamId>>,
    ) -> Self {
        self.stream_id = try_serialize_field(Self::descriptor_stream_id(), stream_id);
        self
    }

    /// Monotonic per-stream sequence number. Gaps surface as a diagnostic.
    #[inline]
    pub fn with_sequence_number(
        mut self,
        sequence_number: impl Into<crate::components::AudioSequenceNumber>,
    ) -> Self {
        self.sequence_number =
            try_serialize_field(Self::descriptor_sequence_number(), [sequence_number]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioSequenceNumber`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_sequence_number`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_sequence_number(
        mut self,
        sequence_number: impl IntoIterator<Item = impl Into<crate::components::AudioSequenceNumber>>,
    ) -> Self {
        self.sequence_number =
            try_serialize_field(Self::descriptor_sequence_number(), sequence_number);
        self
    }

    /// If true, the decoder is reset before this chunk is processed.
    #[inline]
    pub fn with_discontinuity(
        mut self,
        discontinuity: impl Into<crate::components::AudioDiscontinuity>,
    ) -> Self {
        self.discontinuity = try_serialize_field(Self::descriptor_discontinuity(), [discontinuity]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioDiscontinuity`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_discontinuity`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_discontinuity(
        mut self,
        discontinuity: impl IntoIterator<Item = impl Into<crate::components::AudioDiscontinuity>>,
    ) -> Self {
        self.discontinuity = try_serialize_field(Self::descriptor_discontinuity(), discontinuity);
        self
    }

    /// If true, this chunk is an independent seek target.
    ///
    /// Defaults to `true` for Opus; codecs with inter-frame dependencies may
    /// set it false on non-key segments.
    #[inline]
    pub fn with_seekable(mut self, seekable: impl Into<crate::components::AudioSeekable>) -> Self {
        self.seekable = try_serialize_field(Self::descriptor_seekable(), [seekable]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioSeekable`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_seekable`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_seekable(
        mut self,
        seekable: impl IntoIterator<Item = impl Into<crate::components::AudioSeekable>>,
    ) -> Self {
        self.seekable = try_serialize_field(Self::descriptor_seekable(), seekable);
        self
    }
}

impl ::re_byte_size::SizeBytes for AudioStream {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.codec.heap_size_bytes()
            + self.sample_rate.heap_size_bytes()
            + self.channel_count.heap_size_bytes()
            + self.chunk.heap_size_bytes()
            + self.duration_samples.heap_size_bytes()
            + self.channel_layout.heap_size_bytes()
            + self.priming_delay.heap_size_bytes()
            + self.stream_id.heap_size_bytes()
            + self.sequence_number.heap_size_bytes()
            + self.discontinuity.heap_size_bytes()
            + self.seekable.heap_size_bytes()
    }
}
