// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_annotation_span.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Audio-aligned annotation spans.
///
/// Use for ASR words, utterances, speaker turns, VAD regions, TTS emissions,
/// interruption windows, and other span-like evidence.
///
/// Each row stores one or more spans using parallel arrays. Spans are logged as
/// queryable data, not private UI state, so downstream tooling can overlap-query
/// and export them alongside audio summaries and source metadata.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Default)]
pub struct AudioAnnotationSpan {
    /// Media-time start of each span, in nanoseconds.
    pub start_time: Option<SerializedComponentBatch>,

    /// Media-time end of each span, in nanoseconds.
    pub end_time: Option<SerializedComponentBatch>,

    /// Semantic class of each span.
    pub kind: Option<SerializedComponentBatch>,

    /// Human-readable text for each span.
    pub labels: Option<SerializedComponentBatch>,

    /// Confidence score per span. Convention: 0 is lowest confidence, 1 is highest.
    pub confidence: Option<SerializedComponentBatch>,

    /// Speaker identity or diarization label per span.
    pub speaker: Option<SerializedComponentBatch>,

    /// Stable identity of the audio source these spans refer to.
    pub source_id: Option<SerializedComponentBatch>,

    /// Entity carrying the source [`archetypes::AudioStream`][crate::archetypes::AudioStream] or [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    pub audio_reference: Option<SerializedComponentBatch>,

    /// Optional related or parent entities, e.g. words belonging to an utterance.
    pub related: Option<SerializedComponentBatch>,

    /// Additional span metadata shared by this row.
    pub metadata: Option<SerializedComponentBatch>,

    /// Optional display color per span.
    pub colors: Option<SerializedComponentBatch>,
}

impl AudioAnnotationSpan {
    /// Returns the [`ComponentDescriptor`] for [`Self::start_time`].
    ///
    /// The corresponding component is [`crate::components::AudioTimestamp`].
    #[inline]
    pub fn descriptor_start_time() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:start_time".into(),
            component_type: Some("rerun.components.AudioTimestamp".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::end_time`].
    ///
    /// The corresponding component is [`crate::components::AudioTimestamp`].
    #[inline]
    pub fn descriptor_end_time() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:end_time".into(),
            component_type: Some("rerun.components.AudioTimestamp".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::kind`].
    ///
    /// The corresponding component is [`crate::components::AudioAnnotationKind`].
    #[inline]
    pub fn descriptor_kind() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:kind".into(),
            component_type: Some("rerun.components.AudioAnnotationKind".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::labels`].
    ///
    /// The corresponding component is [`crate::components::Text`].
    #[inline]
    pub fn descriptor_labels() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:labels".into(),
            component_type: Some("rerun.components.Text".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::confidence`].
    ///
    /// The corresponding component is [`crate::components::Scalar`].
    #[inline]
    pub fn descriptor_confidence() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:confidence".into(),
            component_type: Some("rerun.components.Scalar".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::speaker`].
    ///
    /// The corresponding component is [`crate::components::Text`].
    #[inline]
    pub fn descriptor_speaker() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:speaker".into(),
            component_type: Some("rerun.components.Text".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::source_id`].
    ///
    /// The corresponding component is [`crate::components::AudioSourceId`].
    #[inline]
    pub fn descriptor_source_id() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:source_id".into(),
            component_type: Some("rerun.components.AudioSourceId".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::audio_reference`].
    ///
    /// The corresponding component is [`crate::components::EntityPath`].
    #[inline]
    pub fn descriptor_audio_reference() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:audio_reference".into(),
            component_type: Some("rerun.components.EntityPath".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::related`].
    ///
    /// The corresponding component is [`crate::components::EntityPath`].
    #[inline]
    pub fn descriptor_related() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:related".into(),
            component_type: Some("rerun.components.EntityPath".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::metadata`].
    ///
    /// The corresponding component is [`crate::components::KeyValuePairs`].
    #[inline]
    pub fn descriptor_metadata() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:metadata".into(),
            component_type: Some("rerun.components.KeyValuePairs".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::colors`].
    ///
    /// The corresponding component is [`crate::components::Color`].
    #[inline]
    pub fn descriptor_colors() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioAnnotationSpan".into()),
            component: "AudioAnnotationSpan:colors".into(),
            component_type: Some("rerun.components.Color".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioAnnotationSpan::descriptor_start_time(),
            AudioAnnotationSpan::descriptor_end_time(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 4usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioAnnotationSpan::descriptor_kind(),
            AudioAnnotationSpan::descriptor_labels(),
            AudioAnnotationSpan::descriptor_confidence(),
            AudioAnnotationSpan::descriptor_speaker(),
        ]
    });

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 5usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioAnnotationSpan::descriptor_source_id(),
            AudioAnnotationSpan::descriptor_audio_reference(),
            AudioAnnotationSpan::descriptor_related(),
            AudioAnnotationSpan::descriptor_metadata(),
            AudioAnnotationSpan::descriptor_colors(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 11usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioAnnotationSpan::descriptor_start_time(),
            AudioAnnotationSpan::descriptor_end_time(),
            AudioAnnotationSpan::descriptor_kind(),
            AudioAnnotationSpan::descriptor_labels(),
            AudioAnnotationSpan::descriptor_confidence(),
            AudioAnnotationSpan::descriptor_speaker(),
            AudioAnnotationSpan::descriptor_source_id(),
            AudioAnnotationSpan::descriptor_audio_reference(),
            AudioAnnotationSpan::descriptor_related(),
            AudioAnnotationSpan::descriptor_metadata(),
            AudioAnnotationSpan::descriptor_colors(),
        ]
    });

impl AudioAnnotationSpan {
    /// The total number of components in the archetype: 2 required, 4 recommended, 5 optional
    pub const NUM_COMPONENTS: usize = 11usize;
}

impl ::re_types_core::Archetype for AudioAnnotationSpan {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AudioAnnotationSpan".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Audio annotation span"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let start_time = arrays_by_descr
            .get(&Self::descriptor_start_time())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_start_time())
            });
        let end_time = arrays_by_descr
            .get(&Self::descriptor_end_time())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_end_time()));
        let kind = arrays_by_descr
            .get(&Self::descriptor_kind())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_kind()));
        let labels = arrays_by_descr
            .get(&Self::descriptor_labels())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_labels()));
        let confidence = arrays_by_descr
            .get(&Self::descriptor_confidence())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_confidence())
            });
        let speaker = arrays_by_descr
            .get(&Self::descriptor_speaker())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_speaker()));
        let source_id = arrays_by_descr
            .get(&Self::descriptor_source_id())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_source_id())
            });
        let audio_reference = arrays_by_descr
            .get(&Self::descriptor_audio_reference())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_audio_reference())
            });
        let related = arrays_by_descr
            .get(&Self::descriptor_related())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_related()));
        let metadata = arrays_by_descr
            .get(&Self::descriptor_metadata())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_metadata()));
        let colors = arrays_by_descr
            .get(&Self::descriptor_colors())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_colors()));
        Ok(Self {
            start_time,
            end_time,
            kind,
            labels,
            confidence,
            speaker,
            source_id,
            audio_reference,
            related,
            metadata,
            colors,
        })
    }
}

impl ::re_types_core::AsComponents for AudioAnnotationSpan {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.start_time.clone(),
            self.end_time.clone(),
            self.kind.clone(),
            self.labels.clone(),
            self.confidence.clone(),
            self.speaker.clone(),
            self.source_id.clone(),
            self.audio_reference.clone(),
            self.related.clone(),
            self.metadata.clone(),
            self.colors.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AudioAnnotationSpan {}

impl crate::VisualizableArchetype for AudioAnnotationSpan {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("AudioAnnotationSpan").with_overrides(self)
    }
}

impl AudioAnnotationSpan {
    /// Create a new `AudioAnnotationSpan`.
    #[inline]
    pub fn new(
        start_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
        end_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
    ) -> Self {
        Self {
            start_time: try_serialize_field(Self::descriptor_start_time(), start_time),
            end_time: try_serialize_field(Self::descriptor_end_time(), end_time),
            kind: None,
            labels: None,
            confidence: None,
            speaker: None,
            source_id: None,
            audio_reference: None,
            related: None,
            metadata: None,
            colors: None,
        }
    }

    /// Update only some specific fields of a `AudioAnnotationSpan`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AudioAnnotationSpan`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            start_time: Some(SerializedComponentBatch::new(
                crate::components::AudioTimestamp::arrow_empty(),
                Self::descriptor_start_time(),
            )),
            end_time: Some(SerializedComponentBatch::new(
                crate::components::AudioTimestamp::arrow_empty(),
                Self::descriptor_end_time(),
            )),
            kind: Some(SerializedComponentBatch::new(
                crate::components::AudioAnnotationKind::arrow_empty(),
                Self::descriptor_kind(),
            )),
            labels: Some(SerializedComponentBatch::new(
                crate::components::Text::arrow_empty(),
                Self::descriptor_labels(),
            )),
            confidence: Some(SerializedComponentBatch::new(
                crate::components::Scalar::arrow_empty(),
                Self::descriptor_confidence(),
            )),
            speaker: Some(SerializedComponentBatch::new(
                crate::components::Text::arrow_empty(),
                Self::descriptor_speaker(),
            )),
            source_id: Some(SerializedComponentBatch::new(
                crate::components::AudioSourceId::arrow_empty(),
                Self::descriptor_source_id(),
            )),
            audio_reference: Some(SerializedComponentBatch::new(
                crate::components::EntityPath::arrow_empty(),
                Self::descriptor_audio_reference(),
            )),
            related: Some(SerializedComponentBatch::new(
                crate::components::EntityPath::arrow_empty(),
                Self::descriptor_related(),
            )),
            metadata: Some(SerializedComponentBatch::new(
                crate::components::KeyValuePairs::arrow_empty(),
                Self::descriptor_metadata(),
            )),
            colors: Some(SerializedComponentBatch::new(
                crate::components::Color::arrow_empty(),
                Self::descriptor_colors(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.start_time
                .map(|start_time| start_time.partitioned(_lengths.clone()))
                .transpose()?,
            self.end_time
                .map(|end_time| end_time.partitioned(_lengths.clone()))
                .transpose()?,
            self.kind
                .map(|kind| kind.partitioned(_lengths.clone()))
                .transpose()?,
            self.labels
                .map(|labels| labels.partitioned(_lengths.clone()))
                .transpose()?,
            self.confidence
                .map(|confidence| confidence.partitioned(_lengths.clone()))
                .transpose()?,
            self.speaker
                .map(|speaker| speaker.partitioned(_lengths.clone()))
                .transpose()?,
            self.source_id
                .map(|source_id| source_id.partitioned(_lengths.clone()))
                .transpose()?,
            self.audio_reference
                .map(|audio_reference| audio_reference.partitioned(_lengths.clone()))
                .transpose()?,
            self.related
                .map(|related| related.partitioned(_lengths.clone()))
                .transpose()?,
            self.metadata
                .map(|metadata| metadata.partitioned(_lengths.clone()))
                .transpose()?,
            self.colors
                .map(|colors| colors.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_start_time = self.start_time.as_ref().map(|b| b.array.len());
        let len_end_time = self.end_time.as_ref().map(|b| b.array.len());
        let len_kind = self.kind.as_ref().map(|b| b.array.len());
        let len_labels = self.labels.as_ref().map(|b| b.array.len());
        let len_confidence = self.confidence.as_ref().map(|b| b.array.len());
        let len_speaker = self.speaker.as_ref().map(|b| b.array.len());
        let len_source_id = self.source_id.as_ref().map(|b| b.array.len());
        let len_audio_reference = self.audio_reference.as_ref().map(|b| b.array.len());
        let len_related = self.related.as_ref().map(|b| b.array.len());
        let len_metadata = self.metadata.as_ref().map(|b| b.array.len());
        let len_colors = self.colors.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_start_time)
            .or(len_end_time)
            .or(len_kind)
            .or(len_labels)
            .or(len_confidence)
            .or(len_speaker)
            .or(len_source_id)
            .or(len_audio_reference)
            .or(len_related)
            .or(len_metadata)
            .or(len_colors)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Media-time start of each span, in nanoseconds.
    #[inline]
    pub fn with_start_time(
        mut self,
        start_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
    ) -> Self {
        self.start_time = try_serialize_field(Self::descriptor_start_time(), start_time);
        self
    }

    /// Media-time end of each span, in nanoseconds.
    #[inline]
    pub fn with_end_time(
        mut self,
        end_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
    ) -> Self {
        self.end_time = try_serialize_field(Self::descriptor_end_time(), end_time);
        self
    }

    /// Semantic class of each span.
    #[inline]
    pub fn with_kind(
        mut self,
        kind: impl IntoIterator<Item = impl Into<crate::components::AudioAnnotationKind>>,
    ) -> Self {
        self.kind = try_serialize_field(Self::descriptor_kind(), kind);
        self
    }

    /// Human-readable text for each span.
    #[inline]
    pub fn with_labels(
        mut self,
        labels: impl IntoIterator<Item = impl Into<crate::components::Text>>,
    ) -> Self {
        self.labels = try_serialize_field(Self::descriptor_labels(), labels);
        self
    }

    /// Confidence score per span. Convention: 0 is lowest confidence, 1 is highest.
    #[inline]
    pub fn with_confidence(
        mut self,
        confidence: impl IntoIterator<Item = impl Into<crate::components::Scalar>>,
    ) -> Self {
        self.confidence = try_serialize_field(Self::descriptor_confidence(), confidence);
        self
    }

    /// Speaker identity or diarization label per span.
    #[inline]
    pub fn with_speaker(
        mut self,
        speaker: impl IntoIterator<Item = impl Into<crate::components::Text>>,
    ) -> Self {
        self.speaker = try_serialize_field(Self::descriptor_speaker(), speaker);
        self
    }

    /// Stable identity of the audio source these spans refer to.
    #[inline]
    pub fn with_source_id(
        mut self,
        source_id: impl Into<crate::components::AudioSourceId>,
    ) -> Self {
        self.source_id = try_serialize_field(Self::descriptor_source_id(), [source_id]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioSourceId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_source_id`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_source_id(
        mut self,
        source_id: impl IntoIterator<Item = impl Into<crate::components::AudioSourceId>>,
    ) -> Self {
        self.source_id = try_serialize_field(Self::descriptor_source_id(), source_id);
        self
    }

    /// Entity carrying the source [`archetypes::AudioStream`][crate::archetypes::AudioStream] or [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    #[inline]
    pub fn with_audio_reference(
        mut self,
        audio_reference: impl Into<crate::components::EntityPath>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), [audio_reference]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::EntityPath`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_audio_reference`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_audio_reference(
        mut self,
        audio_reference: impl IntoIterator<Item = impl Into<crate::components::EntityPath>>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), audio_reference);
        self
    }

    /// Optional related or parent entities, e.g. words belonging to an utterance.
    #[inline]
    pub fn with_related(
        mut self,
        related: impl IntoIterator<Item = impl Into<crate::components::EntityPath>>,
    ) -> Self {
        self.related = try_serialize_field(Self::descriptor_related(), related);
        self
    }

    /// Additional span metadata shared by this row.
    #[inline]
    pub fn with_metadata(mut self, metadata: impl Into<crate::components::KeyValuePairs>) -> Self {
        self.metadata = try_serialize_field(Self::descriptor_metadata(), [metadata]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::KeyValuePairs`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_metadata`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_metadata(
        mut self,
        metadata: impl IntoIterator<Item = impl Into<crate::components::KeyValuePairs>>,
    ) -> Self {
        self.metadata = try_serialize_field(Self::descriptor_metadata(), metadata);
        self
    }

    /// Optional display color per span.
    #[inline]
    pub fn with_colors(
        mut self,
        colors: impl IntoIterator<Item = impl Into<crate::components::Color>>,
    ) -> Self {
        self.colors = try_serialize_field(Self::descriptor_colors(), colors);
        self
    }
}

impl ::re_byte_size::SizeBytes for AudioAnnotationSpan {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.start_time.heap_size_bytes()
            + self.end_time.heap_size_bytes()
            + self.kind.heap_size_bytes()
            + self.labels.heap_size_bytes()
            + self.confidence.heap_size_bytes()
            + self.speaker.heap_size_bytes()
            + self.source_id.heap_size_bytes()
            + self.audio_reference.heap_size_bytes()
            + self.related.heap_size_bytes()
            + self.metadata.heap_size_bytes()
            + self.colors.heap_size_bytes()
    }
}
