// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_waveform_summary.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Multi-resolution waveform summary buckets for an audio source.
///
/// Each row stores one batch of summary buckets. The `bucket_start`,
/// `bucket_duration_samples`, `min_amplitude`, and `max_amplitude` arrays are
/// parallel arrays and should have the same length. Optional arrays such as
/// `rms_amplitude` and `activity` are also parallel when present.
///
/// These summaries are durable derived data: they can be logged, cached,
/// queried, exported, and rendered without decoding source audio on every pan
/// or zoom.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Default)]
pub struct AudioWaveformSummary {
    /// Media-time start of each summary bucket, in nanoseconds.
    pub bucket_start: Option<SerializedComponentBatch>,

    /// Duration of each summary bucket, in samples per channel.
    pub bucket_duration_samples: Option<SerializedComponentBatch>,

    /// Minimum normalized amplitude in each bucket.
    pub min_amplitude: Option<SerializedComponentBatch>,

    /// Maximum normalized amplitude in each bucket.
    pub max_amplitude: Option<SerializedComponentBatch>,

    /// Optional RMS or loudness-like summary for each bucket.
    pub rms_amplitude: Option<SerializedComponentBatch>,

    /// Optional activity/silence score for each bucket. Convention: 0 is silent, 1 is active.
    pub activity: Option<SerializedComponentBatch>,

    /// Stable identity of the audio source this summary was derived from.
    pub source_id: Option<SerializedComponentBatch>,

    /// Entity carrying the source [`archetypes::AudioStream`][crate::archetypes::AudioStream] or [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    pub audio_reference: Option<SerializedComponentBatch>,
}

impl AudioWaveformSummary {
    /// Returns the [`ComponentDescriptor`] for [`Self::bucket_start`].
    ///
    /// The corresponding component is [`crate::components::AudioTimestamp`].
    #[inline]
    pub fn descriptor_bucket_start() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:bucket_start".into(),
            component_type: Some("rerun.components.AudioTimestamp".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::bucket_duration_samples`].
    ///
    /// The corresponding component is [`crate::components::AudioDurationSamples`].
    #[inline]
    pub fn descriptor_bucket_duration_samples() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:bucket_duration_samples".into(),
            component_type: Some("rerun.components.AudioDurationSamples".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::min_amplitude`].
    ///
    /// The corresponding component is [`crate::components::Scalar`].
    #[inline]
    pub fn descriptor_min_amplitude() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:min_amplitude".into(),
            component_type: Some("rerun.components.Scalar".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::max_amplitude`].
    ///
    /// The corresponding component is [`crate::components::Scalar`].
    #[inline]
    pub fn descriptor_max_amplitude() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:max_amplitude".into(),
            component_type: Some("rerun.components.Scalar".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::rms_amplitude`].
    ///
    /// The corresponding component is [`crate::components::Scalar`].
    #[inline]
    pub fn descriptor_rms_amplitude() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:rms_amplitude".into(),
            component_type: Some("rerun.components.Scalar".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::activity`].
    ///
    /// The corresponding component is [`crate::components::Scalar`].
    #[inline]
    pub fn descriptor_activity() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:activity".into(),
            component_type: Some("rerun.components.Scalar".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::source_id`].
    ///
    /// The corresponding component is [`crate::components::AudioSourceId`].
    #[inline]
    pub fn descriptor_source_id() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:source_id".into(),
            component_type: Some("rerun.components.AudioSourceId".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::audio_reference`].
    ///
    /// The corresponding component is [`crate::components::EntityPath`].
    #[inline]
    pub fn descriptor_audio_reference() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioWaveformSummary".into()),
            component: "AudioWaveformSummary:audio_reference".into(),
            component_type: Some("rerun.components.EntityPath".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 4usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioWaveformSummary::descriptor_bucket_start(),
            AudioWaveformSummary::descriptor_bucket_duration_samples(),
            AudioWaveformSummary::descriptor_min_amplitude(),
            AudioWaveformSummary::descriptor_max_amplitude(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioWaveformSummary::descriptor_rms_amplitude(),
            AudioWaveformSummary::descriptor_activity(),
        ]
    });

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioWaveformSummary::descriptor_source_id(),
            AudioWaveformSummary::descriptor_audio_reference(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 8usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioWaveformSummary::descriptor_bucket_start(),
            AudioWaveformSummary::descriptor_bucket_duration_samples(),
            AudioWaveformSummary::descriptor_min_amplitude(),
            AudioWaveformSummary::descriptor_max_amplitude(),
            AudioWaveformSummary::descriptor_rms_amplitude(),
            AudioWaveformSummary::descriptor_activity(),
            AudioWaveformSummary::descriptor_source_id(),
            AudioWaveformSummary::descriptor_audio_reference(),
        ]
    });

impl AudioWaveformSummary {
    /// The total number of components in the archetype: 4 required, 2 recommended, 2 optional
    pub const NUM_COMPONENTS: usize = 8usize;
}

impl ::re_types_core::Archetype for AudioWaveformSummary {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AudioWaveformSummary".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Audio waveform summary"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let bucket_start = arrays_by_descr
            .get(&Self::descriptor_bucket_start())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_bucket_start())
            });
        let bucket_duration_samples = arrays_by_descr
            .get(&Self::descriptor_bucket_duration_samples())
            .map(|array| {
                SerializedComponentBatch::new(
                    array.clone(),
                    Self::descriptor_bucket_duration_samples(),
                )
            });
        let min_amplitude = arrays_by_descr
            .get(&Self::descriptor_min_amplitude())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_min_amplitude())
            });
        let max_amplitude = arrays_by_descr
            .get(&Self::descriptor_max_amplitude())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_max_amplitude())
            });
        let rms_amplitude = arrays_by_descr
            .get(&Self::descriptor_rms_amplitude())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_rms_amplitude())
            });
        let activity = arrays_by_descr
            .get(&Self::descriptor_activity())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_activity()));
        let source_id = arrays_by_descr
            .get(&Self::descriptor_source_id())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_source_id())
            });
        let audio_reference = arrays_by_descr
            .get(&Self::descriptor_audio_reference())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_audio_reference())
            });
        Ok(Self {
            bucket_start,
            bucket_duration_samples,
            min_amplitude,
            max_amplitude,
            rms_amplitude,
            activity,
            source_id,
            audio_reference,
        })
    }
}

impl ::re_types_core::AsComponents for AudioWaveformSummary {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.bucket_start.clone(),
            self.bucket_duration_samples.clone(),
            self.min_amplitude.clone(),
            self.max_amplitude.clone(),
            self.rms_amplitude.clone(),
            self.activity.clone(),
            self.source_id.clone(),
            self.audio_reference.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AudioWaveformSummary {}

impl crate::VisualizableArchetype for AudioWaveformSummary {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("AudioWaveformSummary").with_overrides(self)
    }
}

impl AudioWaveformSummary {
    /// Create a new `AudioWaveformSummary`.
    #[inline]
    pub fn new(
        bucket_start: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
        bucket_duration_samples: impl IntoIterator<
            Item = impl Into<crate::components::AudioDurationSamples>,
        >,
        min_amplitude: impl IntoIterator<Item = impl Into<crate::components::Scalar>>,
        max_amplitude: impl IntoIterator<Item = impl Into<crate::components::Scalar>>,
    ) -> Self {
        Self {
            bucket_start: try_serialize_field(Self::descriptor_bucket_start(), bucket_start),
            bucket_duration_samples: try_serialize_field(
                Self::descriptor_bucket_duration_samples(),
                bucket_duration_samples,
            ),
            min_amplitude: try_serialize_field(Self::descriptor_min_amplitude(), min_amplitude),
            max_amplitude: try_serialize_field(Self::descriptor_max_amplitude(), max_amplitude),
            rms_amplitude: None,
            activity: None,
            source_id: None,
            audio_reference: None,
        }
    }

    /// Update only some specific fields of a `AudioWaveformSummary`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AudioWaveformSummary`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            bucket_start: Some(SerializedComponentBatch::new(
                crate::components::AudioTimestamp::arrow_empty(),
                Self::descriptor_bucket_start(),
            )),
            bucket_duration_samples: Some(SerializedComponentBatch::new(
                crate::components::AudioDurationSamples::arrow_empty(),
                Self::descriptor_bucket_duration_samples(),
            )),
            min_amplitude: Some(SerializedComponentBatch::new(
                crate::components::Scalar::arrow_empty(),
                Self::descriptor_min_amplitude(),
            )),
            max_amplitude: Some(SerializedComponentBatch::new(
                crate::components::Scalar::arrow_empty(),
                Self::descriptor_max_amplitude(),
            )),
            rms_amplitude: Some(SerializedComponentBatch::new(
                crate::components::Scalar::arrow_empty(),
                Self::descriptor_rms_amplitude(),
            )),
            activity: Some(SerializedComponentBatch::new(
                crate::components::Scalar::arrow_empty(),
                Self::descriptor_activity(),
            )),
            source_id: Some(SerializedComponentBatch::new(
                crate::components::AudioSourceId::arrow_empty(),
                Self::descriptor_source_id(),
            )),
            audio_reference: Some(SerializedComponentBatch::new(
                crate::components::EntityPath::arrow_empty(),
                Self::descriptor_audio_reference(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.bucket_start
                .map(|bucket_start| bucket_start.partitioned(_lengths.clone()))
                .transpose()?,
            self.bucket_duration_samples
                .map(|bucket_duration_samples| {
                    bucket_duration_samples.partitioned(_lengths.clone())
                })
                .transpose()?,
            self.min_amplitude
                .map(|min_amplitude| min_amplitude.partitioned(_lengths.clone()))
                .transpose()?,
            self.max_amplitude
                .map(|max_amplitude| max_amplitude.partitioned(_lengths.clone()))
                .transpose()?,
            self.rms_amplitude
                .map(|rms_amplitude| rms_amplitude.partitioned(_lengths.clone()))
                .transpose()?,
            self.activity
                .map(|activity| activity.partitioned(_lengths.clone()))
                .transpose()?,
            self.source_id
                .map(|source_id| source_id.partitioned(_lengths.clone()))
                .transpose()?,
            self.audio_reference
                .map(|audio_reference| audio_reference.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_bucket_start = self.bucket_start.as_ref().map(|b| b.array.len());
        let len_bucket_duration_samples =
            self.bucket_duration_samples.as_ref().map(|b| b.array.len());
        let len_min_amplitude = self.min_amplitude.as_ref().map(|b| b.array.len());
        let len_max_amplitude = self.max_amplitude.as_ref().map(|b| b.array.len());
        let len_rms_amplitude = self.rms_amplitude.as_ref().map(|b| b.array.len());
        let len_activity = self.activity.as_ref().map(|b| b.array.len());
        let len_source_id = self.source_id.as_ref().map(|b| b.array.len());
        let len_audio_reference = self.audio_reference.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_bucket_start)
            .or(len_bucket_duration_samples)
            .or(len_min_amplitude)
            .or(len_max_amplitude)
            .or(len_rms_amplitude)
            .or(len_activity)
            .or(len_source_id)
            .or(len_audio_reference)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Media-time start of each summary bucket, in nanoseconds.
    #[inline]
    pub fn with_bucket_start(
        mut self,
        bucket_start: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
    ) -> Self {
        self.bucket_start = try_serialize_field(Self::descriptor_bucket_start(), bucket_start);
        self
    }

    /// Duration of each summary bucket, in samples per channel.
    #[inline]
    pub fn with_bucket_duration_samples(
        mut self,
        bucket_duration_samples: impl IntoIterator<
            Item = impl Into<crate::components::AudioDurationSamples>,
        >,
    ) -> Self {
        self.bucket_duration_samples = try_serialize_field(
            Self::descriptor_bucket_duration_samples(),
            bucket_duration_samples,
        );
        self
    }

    /// Minimum normalized amplitude in each bucket.
    #[inline]
    pub fn with_min_amplitude(
        mut self,
        min_amplitude: impl IntoIterator<Item = impl Into<crate::components::Scalar>>,
    ) -> Self {
        self.min_amplitude = try_serialize_field(Self::descriptor_min_amplitude(), min_amplitude);
        self
    }

    /// Maximum normalized amplitude in each bucket.
    #[inline]
    pub fn with_max_amplitude(
        mut self,
        max_amplitude: impl IntoIterator<Item = impl Into<crate::components::Scalar>>,
    ) -> Self {
        self.max_amplitude = try_serialize_field(Self::descriptor_max_amplitude(), max_amplitude);
        self
    }

    /// Optional RMS or loudness-like summary for each bucket.
    #[inline]
    pub fn with_rms_amplitude(
        mut self,
        rms_amplitude: impl IntoIterator<Item = impl Into<crate::components::Scalar>>,
    ) -> Self {
        self.rms_amplitude = try_serialize_field(Self::descriptor_rms_amplitude(), rms_amplitude);
        self
    }

    /// Optional activity/silence score for each bucket. Convention: 0 is silent, 1 is active.
    #[inline]
    pub fn with_activity(
        mut self,
        activity: impl IntoIterator<Item = impl Into<crate::components::Scalar>>,
    ) -> Self {
        self.activity = try_serialize_field(Self::descriptor_activity(), activity);
        self
    }

    /// Stable identity of the audio source this summary was derived from.
    #[inline]
    pub fn with_source_id(
        mut self,
        source_id: impl Into<crate::components::AudioSourceId>,
    ) -> Self {
        self.source_id = try_serialize_field(Self::descriptor_source_id(), [source_id]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioSourceId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_source_id`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_source_id(
        mut self,
        source_id: impl IntoIterator<Item = impl Into<crate::components::AudioSourceId>>,
    ) -> Self {
        self.source_id = try_serialize_field(Self::descriptor_source_id(), source_id);
        self
    }

    /// Entity carrying the source [`archetypes::AudioStream`][crate::archetypes::AudioStream] or [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    #[inline]
    pub fn with_audio_reference(
        mut self,
        audio_reference: impl Into<crate::components::EntityPath>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), [audio_reference]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::EntityPath`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_audio_reference`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_audio_reference(
        mut self,
        audio_reference: impl IntoIterator<Item = impl Into<crate::components::EntityPath>>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), audio_reference);
        self
    }
}

impl ::re_byte_size::SizeBytes for AudioWaveformSummary {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.bucket_start.heap_size_bytes()
            + self.bucket_duration_samples.heap_size_bytes()
            + self.min_amplitude.heap_size_bytes()
            + self.max_amplitude.heap_size_bytes()
            + self.rms_amplitude.heap_size_bytes()
            + self.activity.heap_size_bytes()
            + self.source_id.heap_size_bytes()
            + self.audio_reference.heap_size_bytes()
    }
}
