// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_seek_index.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Materialized seek index for an audio source.
///
/// Each row stores one batch of entries. The `media_time`, `decode_time`, and
/// `trim_samples` arrays are parallel arrays. A playback runtime resolves a
/// requested media time by choosing the nearest preceding `decode_time`,
/// decoding forward, then trimming `trim_samples` samples from the decoded PCM.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Default)]
pub struct AudioSeekIndex {
    /// Media time that this index entry accelerates.
    pub media_time: Option<SerializedComponentBatch>,

    /// Nearest preceding decoder reset / key / seekable boundary.
    pub decode_time: Option<SerializedComponentBatch>,

    /// Number of samples per channel to discard after decoding from `decode_time`.
    pub trim_samples: Option<SerializedComponentBatch>,

    /// Sequence number of the segment containing `decode_time`, if known.
    pub sequence_number: Option<SerializedComponentBatch>,

    /// Whether the entry crosses or starts at a discontinuity.
    pub discontinuity: Option<SerializedComponentBatch>,

    /// Stable identity of the audio source this index was derived from.
    pub source_id: Option<SerializedComponentBatch>,

    /// Entity carrying the source [`archetypes::AudioStream`][crate::archetypes::AudioStream] or [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    pub audio_reference: Option<SerializedComponentBatch>,

    /// Continuity stream id associated with this index batch.
    pub stream_id: Option<SerializedComponentBatch>,
}

impl AudioSeekIndex {
    /// Returns the [`ComponentDescriptor`] for [`Self::media_time`].
    ///
    /// The corresponding component is [`crate::components::AudioTimestamp`].
    #[inline]
    pub fn descriptor_media_time() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:media_time".into(),
            component_type: Some("rerun.components.AudioTimestamp".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::decode_time`].
    ///
    /// The corresponding component is [`crate::components::AudioTimestamp`].
    #[inline]
    pub fn descriptor_decode_time() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:decode_time".into(),
            component_type: Some("rerun.components.AudioTimestamp".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::trim_samples`].
    ///
    /// The corresponding component is [`crate::components::AudioDurationSamples`].
    #[inline]
    pub fn descriptor_trim_samples() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:trim_samples".into(),
            component_type: Some("rerun.components.AudioDurationSamples".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::sequence_number`].
    ///
    /// The corresponding component is [`crate::components::AudioSequenceNumber`].
    #[inline]
    pub fn descriptor_sequence_number() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:sequence_number".into(),
            component_type: Some("rerun.components.AudioSequenceNumber".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::discontinuity`].
    ///
    /// The corresponding component is [`crate::components::AudioDiscontinuity`].
    #[inline]
    pub fn descriptor_discontinuity() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:discontinuity".into(),
            component_type: Some("rerun.components.AudioDiscontinuity".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::source_id`].
    ///
    /// The corresponding component is [`crate::components::AudioSourceId`].
    #[inline]
    pub fn descriptor_source_id() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:source_id".into(),
            component_type: Some("rerun.components.AudioSourceId".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::audio_reference`].
    ///
    /// The corresponding component is [`crate::components::EntityPath`].
    #[inline]
    pub fn descriptor_audio_reference() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:audio_reference".into(),
            component_type: Some("rerun.components.EntityPath".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::stream_id`].
    ///
    /// The corresponding component is [`crate::components::AudioStreamId`].
    #[inline]
    pub fn descriptor_stream_id() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSeekIndex".into()),
            component: "AudioSeekIndex:stream_id".into(),
            component_type: Some("rerun.components.AudioStreamId".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioSeekIndex::descriptor_media_time(),
            AudioSeekIndex::descriptor_decode_time(),
            AudioSeekIndex::descriptor_trim_samples(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioSeekIndex::descriptor_sequence_number(),
            AudioSeekIndex::descriptor_discontinuity(),
        ]
    });

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioSeekIndex::descriptor_source_id(),
            AudioSeekIndex::descriptor_audio_reference(),
            AudioSeekIndex::descriptor_stream_id(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 8usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioSeekIndex::descriptor_media_time(),
            AudioSeekIndex::descriptor_decode_time(),
            AudioSeekIndex::descriptor_trim_samples(),
            AudioSeekIndex::descriptor_sequence_number(),
            AudioSeekIndex::descriptor_discontinuity(),
            AudioSeekIndex::descriptor_source_id(),
            AudioSeekIndex::descriptor_audio_reference(),
            AudioSeekIndex::descriptor_stream_id(),
        ]
    });

impl AudioSeekIndex {
    /// The total number of components in the archetype: 3 required, 2 recommended, 3 optional
    pub const NUM_COMPONENTS: usize = 8usize;
}

impl ::re_types_core::Archetype for AudioSeekIndex {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AudioSeekIndex".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Audio seek index"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let media_time = arrays_by_descr
            .get(&Self::descriptor_media_time())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_media_time())
            });
        let decode_time = arrays_by_descr
            .get(&Self::descriptor_decode_time())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_decode_time())
            });
        let trim_samples = arrays_by_descr
            .get(&Self::descriptor_trim_samples())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_trim_samples())
            });
        let sequence_number = arrays_by_descr
            .get(&Self::descriptor_sequence_number())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_sequence_number())
            });
        let discontinuity = arrays_by_descr
            .get(&Self::descriptor_discontinuity())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_discontinuity())
            });
        let source_id = arrays_by_descr
            .get(&Self::descriptor_source_id())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_source_id())
            });
        let audio_reference = arrays_by_descr
            .get(&Self::descriptor_audio_reference())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_audio_reference())
            });
        let stream_id = arrays_by_descr
            .get(&Self::descriptor_stream_id())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_stream_id())
            });
        Ok(Self {
            media_time,
            decode_time,
            trim_samples,
            sequence_number,
            discontinuity,
            source_id,
            audio_reference,
            stream_id,
        })
    }
}

impl ::re_types_core::AsComponents for AudioSeekIndex {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.media_time.clone(),
            self.decode_time.clone(),
            self.trim_samples.clone(),
            self.sequence_number.clone(),
            self.discontinuity.clone(),
            self.source_id.clone(),
            self.audio_reference.clone(),
            self.stream_id.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AudioSeekIndex {}

impl crate::VisualizableArchetype for AudioSeekIndex {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("AudioSeekIndex").with_overrides(self)
    }
}

impl AudioSeekIndex {
    /// Create a new `AudioSeekIndex`.
    #[inline]
    pub fn new(
        media_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
        decode_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
        trim_samples: impl IntoIterator<Item = impl Into<crate::components::AudioDurationSamples>>,
    ) -> Self {
        Self {
            media_time: try_serialize_field(Self::descriptor_media_time(), media_time),
            decode_time: try_serialize_field(Self::descriptor_decode_time(), decode_time),
            trim_samples: try_serialize_field(Self::descriptor_trim_samples(), trim_samples),
            sequence_number: None,
            discontinuity: None,
            source_id: None,
            audio_reference: None,
            stream_id: None,
        }
    }

    /// Update only some specific fields of a `AudioSeekIndex`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AudioSeekIndex`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            media_time: Some(SerializedComponentBatch::new(
                crate::components::AudioTimestamp::arrow_empty(),
                Self::descriptor_media_time(),
            )),
            decode_time: Some(SerializedComponentBatch::new(
                crate::components::AudioTimestamp::arrow_empty(),
                Self::descriptor_decode_time(),
            )),
            trim_samples: Some(SerializedComponentBatch::new(
                crate::components::AudioDurationSamples::arrow_empty(),
                Self::descriptor_trim_samples(),
            )),
            sequence_number: Some(SerializedComponentBatch::new(
                crate::components::AudioSequenceNumber::arrow_empty(),
                Self::descriptor_sequence_number(),
            )),
            discontinuity: Some(SerializedComponentBatch::new(
                crate::components::AudioDiscontinuity::arrow_empty(),
                Self::descriptor_discontinuity(),
            )),
            source_id: Some(SerializedComponentBatch::new(
                crate::components::AudioSourceId::arrow_empty(),
                Self::descriptor_source_id(),
            )),
            audio_reference: Some(SerializedComponentBatch::new(
                crate::components::EntityPath::arrow_empty(),
                Self::descriptor_audio_reference(),
            )),
            stream_id: Some(SerializedComponentBatch::new(
                crate::components::AudioStreamId::arrow_empty(),
                Self::descriptor_stream_id(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.media_time
                .map(|media_time| media_time.partitioned(_lengths.clone()))
                .transpose()?,
            self.decode_time
                .map(|decode_time| decode_time.partitioned(_lengths.clone()))
                .transpose()?,
            self.trim_samples
                .map(|trim_samples| trim_samples.partitioned(_lengths.clone()))
                .transpose()?,
            self.sequence_number
                .map(|sequence_number| sequence_number.partitioned(_lengths.clone()))
                .transpose()?,
            self.discontinuity
                .map(|discontinuity| discontinuity.partitioned(_lengths.clone()))
                .transpose()?,
            self.source_id
                .map(|source_id| source_id.partitioned(_lengths.clone()))
                .transpose()?,
            self.audio_reference
                .map(|audio_reference| audio_reference.partitioned(_lengths.clone()))
                .transpose()?,
            self.stream_id
                .map(|stream_id| stream_id.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_media_time = self.media_time.as_ref().map(|b| b.array.len());
        let len_decode_time = self.decode_time.as_ref().map(|b| b.array.len());
        let len_trim_samples = self.trim_samples.as_ref().map(|b| b.array.len());
        let len_sequence_number = self.sequence_number.as_ref().map(|b| b.array.len());
        let len_discontinuity = self.discontinuity.as_ref().map(|b| b.array.len());
        let len_source_id = self.source_id.as_ref().map(|b| b.array.len());
        let len_audio_reference = self.audio_reference.as_ref().map(|b| b.array.len());
        let len_stream_id = self.stream_id.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_media_time)
            .or(len_decode_time)
            .or(len_trim_samples)
            .or(len_sequence_number)
            .or(len_discontinuity)
            .or(len_source_id)
            .or(len_audio_reference)
            .or(len_stream_id)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Media time that this index entry accelerates.
    #[inline]
    pub fn with_media_time(
        mut self,
        media_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
    ) -> Self {
        self.media_time = try_serialize_field(Self::descriptor_media_time(), media_time);
        self
    }

    /// Nearest preceding decoder reset / key / seekable boundary.
    #[inline]
    pub fn with_decode_time(
        mut self,
        decode_time: impl IntoIterator<Item = impl Into<crate::components::AudioTimestamp>>,
    ) -> Self {
        self.decode_time = try_serialize_field(Self::descriptor_decode_time(), decode_time);
        self
    }

    /// Number of samples per channel to discard after decoding from `decode_time`.
    #[inline]
    pub fn with_trim_samples(
        mut self,
        trim_samples: impl IntoIterator<Item = impl Into<crate::components::AudioDurationSamples>>,
    ) -> Self {
        self.trim_samples = try_serialize_field(Self::descriptor_trim_samples(), trim_samples);
        self
    }

    /// Sequence number of the segment containing `decode_time`, if known.
    #[inline]
    pub fn with_sequence_number(
        mut self,
        sequence_number: impl IntoIterator<Item = impl Into<crate::components::AudioSequenceNumber>>,
    ) -> Self {
        self.sequence_number =
            try_serialize_field(Self::descriptor_sequence_number(), sequence_number);
        self
    }

    /// Whether the entry crosses or starts at a discontinuity.
    #[inline]
    pub fn with_discontinuity(
        mut self,
        discontinuity: impl IntoIterator<Item = impl Into<crate::components::AudioDiscontinuity>>,
    ) -> Self {
        self.discontinuity = try_serialize_field(Self::descriptor_discontinuity(), discontinuity);
        self
    }

    /// Stable identity of the audio source this index was derived from.
    #[inline]
    pub fn with_source_id(
        mut self,
        source_id: impl Into<crate::components::AudioSourceId>,
    ) -> Self {
        self.source_id = try_serialize_field(Self::descriptor_source_id(), [source_id]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioSourceId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_source_id`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_source_id(
        mut self,
        source_id: impl IntoIterator<Item = impl Into<crate::components::AudioSourceId>>,
    ) -> Self {
        self.source_id = try_serialize_field(Self::descriptor_source_id(), source_id);
        self
    }

    /// Entity carrying the source [`archetypes::AudioStream`][crate::archetypes::AudioStream] or [`archetypes::AssetAudio`][crate::archetypes::AssetAudio].
    #[inline]
    pub fn with_audio_reference(
        mut self,
        audio_reference: impl Into<crate::components::EntityPath>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), [audio_reference]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::EntityPath`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_audio_reference`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_audio_reference(
        mut self,
        audio_reference: impl IntoIterator<Item = impl Into<crate::components::EntityPath>>,
    ) -> Self {
        self.audio_reference =
            try_serialize_field(Self::descriptor_audio_reference(), audio_reference);
        self
    }

    /// Continuity stream id associated with this index batch.
    #[inline]
    pub fn with_stream_id(
        mut self,
        stream_id: impl Into<crate::components::AudioStreamId>,
    ) -> Self {
        self.stream_id = try_serialize_field(Self::descriptor_stream_id(), [stream_id]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::AudioStreamId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_stream_id`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_stream_id(
        mut self,
        stream_id: impl IntoIterator<Item = impl Into<crate::components::AudioStreamId>>,
    ) -> Self {
        self.stream_id = try_serialize_field(Self::descriptor_stream_id(), stream_id);
        self
    }
}

impl ::re_byte_size::SizeBytes for AudioSeekIndex {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.media_time.heap_size_bytes()
            + self.decode_time.heap_size_bytes()
            + self.trim_samples.heap_size_bytes()
            + self.sequence_number.heap_size_bytes()
            + self.discontinuity.heap_size_bytes()
            + self.source_id.heap_size_bytes()
            + self.audio_reference.heap_size_bytes()
            + self.stream_id.heap_size_bytes()
    }
}
