// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/audio_timestamp.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class Int64Type;
    using Int64Builder = NumericBuilder<Int64Type>;
} // namespace arrow

namespace rerun::datatypes {
    /// **Datatype**: Presentation timestamp within an `archetypes::AssetAudio`.
    ///
    /// Specified in nanoseconds. Typically measured as time since the start of the audio asset.
    struct AudioTimestamp {
        /// Presentation timestamp value in nanoseconds.
        int64_t timestamp_ns;

      public:
        AudioTimestamp() = default;

        AudioTimestamp(int64_t timestamp_ns_) : timestamp_ns(timestamp_ns_) {}

        AudioTimestamp& operator=(int64_t timestamp_ns_) {
            timestamp_ns = timestamp_ns_;
            return *this;
        }
    };
} // namespace rerun::datatypes

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::AudioTimestamp> {
        static constexpr std::string_view ComponentType = "rerun.datatypes.AudioTimestamp";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::datatypes::AudioTimestamp` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::AudioTimestamp* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::Int64Builder* builder, const datatypes::AudioTimestamp* elements,
            size_t num_elements
        );
    };
} // namespace rerun
